#!/usr/bin/env bash

_I="%{T1}%{T-}"

IDL=$(top -b -n1 | sed -n 's/.* ni, \([^ ]*\).*/\1/p')
ILN=$(echo $IDL | tr ' ' '\n' | wc -l)
ITT=$(echo $IDL | tr ' ' '\n' | awk '{s+=$1} END {print s}')

CPU=$(echo "100-(${ITT}/$ILN)" | bc)

if [[ $CPU -ge 80 ]]; then
	echo "%{B#ff0000}$_I $CPU%{B-}"
elif [[ $CPU -ge 50 ]]; then
	echo "%{B#ffff00}$_I $CPU%{B-}"
else
	echo "$_I $CPU"
fi
