#!/usr/bin/env bash

_I="%{T1}%{T-}"
DIR="${BLOCK_INSTANCE:-$HOME}"

FREE=$(df -h -P -l "$DIR" | grep 'dev' | awk '{print $4}')
PCNT=$(df -h -P -l "$DIR" | grep 'dev' | awk '{print $5}')
NCNT=${PCNT/%/}

echo "$_I $FREE"
