#!/usr/bin/env bash

mpris=$(pidof spotify)
mpv=$(pidof mpv)
BLDR="$HOME/scr/pb"
CNTL=$HOME/scr/i3media

_P="%{A1:$CNTL prev:}%{T1} %{T-}%{A}"
_N="%{A1:$CNTL next:}%{T1} %{T-}%{A}"
_T="%{A1:$CNTL togg:}%{T1} %{T-}%{A}"
_S="%{A1:$CNTL stop:}%{T1} %{T-}%{A}"
_CONTROLS=" $_P$_T$_S$_N"

clr=$(xrdb -query | grep '*color7' | awk '{print $NF}')

if [[ -n $mpv ]]; then
	CRPL=mpmpv
elif [[ -n $mpris ]]; then
	CRPL=mpgui
else
	CRPL=mpmpd
fi
echo "$(${BLDR}/${CRPL})$_CONTROLS"
