#!/usr/bin/env bash

mpris=$(pidof spotify)
mpv=$(pidof mpv)

blocksDir="$HOME/scr/pb"

clr=$(xrdb -query | grep '*color7' | awk '{print $NF}')

if [[ -n $mpv ]]; then
	mpvtitle="$(xdotool getwindowname $(xdotool search --class mpv))"
	mpvlen=$(expr ${#mpvtitle} - 38)
	mpvtitle=${mpvtitle%.*}
	[[ ${#mpvtitle} -ge 35 ]] && mpvtitle=${mpvtitle:0:-${mpvlen}} && mpvtitle="${mpvtitle}..."
	echo "%{T1}%{T-} ${mpvtitle}"
elif [[ -n $mpris ]]; then
	$blocksDir/mpgui
else
	$blocksDir/mpcblk
fi
