#!/usr/bin/env bash

_I="<span face='Font Awesome 5 Free'>&#xf538;</span>"

TOT=$(free | awk '/Mem/{print $2}')
USD=$(free | awk '/Mem/{print $3}')

_C=$(echo "(${USD}/${TOT})*100" | bc)

if [[ $_C -ge 80 ]]; then
	echo "%{B#ff0000}$_I $_C%{B-}"
elif [[ $_C -ge 50 ]]; then
	echo "%{B#ffff00}$_I $_C%{B-}"
else
	echo "$_I $_C"
fi
