#!/usr/bin/env bash

_TMP=$(sensors coretemp-isa-0000 | grep '^Core 0' | awk '{ print $3 }')
_TMP=${_TMP/+/}
RTMP=${_TMP%.*}
_ICN="%{T1}%{T-}"
#_BCL="$(themer -v "acc ")"
#_FCL="$(themer -v "bg0 ")"
[[ $RTMP -ge 50 ]] && _ICN="%{T1}%{T-}" && _BCL="#ffcc00" && _FCL="$(themer -v "fg0 ")"
[[ $RTMP -ge 65 ]] && _ICN="%{T1}%{T-}" && _BCL="#cc0000" && _FCL="$(themer -v "fg0 ")"
FSTR="%{B$_BCL}%{F$_FCL} ${_ICN} ${RTMP} %{B- F-}"
echo $FSTR
