#!/usr/bin/env bash

_TMP=$(sensors coretemp-isa-0000 | awk '/Core 0/ {print $3}')
_TMP=${_TMP/+/}
RTMP=${_TMP%.*}
_ICN="%{T1}%{T-}"
[[ $RTMP -ge 70  ]] && _ICN="%{T1}%{T-}" REV="%{R}"
FSTR="$REV ${_ICN} ${RTMP} "
echo $FSTR
