#!/bin/bash

# OA: Gavin Vales

CRLN=$(readlink -f $HOME/pic/i3wallpaper/current)
i3wall=$HOME/scr/i3wallpaper

_P="%{A1:$i3wall -w PREV}%{T1} %{T-}%{A}"
_N="%{A1:$i3wall -w NEXT}%{T1} %{T-}%{A}"
_R="%{A1:$i3wall -w RANDOM}%{T1} %{T-}%{A}"
_D="%{A1:$i3wall -d ""}%{T1} %{T-}%{A}"
_E="%{A1:$i3wall -r "$(~/scr/i3menu -r 1 -c white)"}%{T1} %{T-}%{A}"
_C="%{A1:$i3wall -w PREV} ${CRLN##*/}%{A}"

_F="%{T1}%{T-}$_P$_R$_E$_D$_N$_C "

echo "$_F"
