#!/bin/bash

# OA: Gavin Vales
# CREATED: Fri  3 May 15:34:40 GMT 2019

tit=$(xdotool getactivewindow getwindowname)
shortlen=$(expr ${#tit} - 29)
if [[ ${#tit} -gt 30 ]]; then
	echo "${tit:0:-${shortlen}}…"
else
	echo "${tit}"
fi
