#!/bin/bash

# OA: Gavin Vales
# CREATED: Fri  5 Apr 00:04:13 GMT 2019

_W=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)

_I="%{T1}%{T-}"

case $_W in
	1) _I="%{T1}%{T-}" ;;
#	2) _I="%{T1}%{T-}" ;;
#	3) _I="%{T1}%{T-}" ;;
esac

echo "${_I}"
dunstify -r 1234 " WORKSPACE $_W"
