#!/bin/bash

bkd="\033[1;30m"
bkl="\033[1;30m"
red="\033[1;31m"
grn="\033[1;32m"
rng="\033[1;33m"
ylw="\033[1;33m"
blu="\033[1;34m"
gnt="\033[1;35m"
cyn="\033[1;36m"
wtd="\033[1;37m"
wtl="\033[0m"
#xfconf-query --channel thunar --property /misc-full-path-in-title --create --type bool --set true
cd ~
echo -e "$blu"
cat << 'EOB'


================================================================================
============================= UPDATE & GET MY REPOS ============================
================================================================================
EOB
echo -e "$wtl"
#sudo pacman -Syyu
#mkdir ~/Drive
#mkdir ~/.tmp
#mkdir ~/git
#cd ~/git
#git clone https://github.com/StillANixRookie/icons_themer.git
#git clone https://github.com/StillANixRookie/numix-solarized-gtk-theme.git
#cd
echo -e "$blu"
cat << 'EOB'


================================================================================
============================ INSTALLING YOUR PROGRAMS ==========================
================================================================================
EOB
echo -e "$wtl"
#sudo pacman -S rofi otf-font-awesome ttf-font-awesome nautilus evince mupdf \
#    pinta redshift playerctl mplayer r tk gcc-fortran newsboat opencv \
#    python-matplotlib python2-matplotlib python-numpy python2-numpy hdf5 \
#    libreoffice pandoc pandoc-crossref pandoc-citeproc python-pygments \
#    python2-pygments biber texlive-most acpi lm_sensors sysstat ntfs-3g \
#    libmpdclient lxappearance sxiv ncurses fftw w3m mpd mpc ncmpcpp feh dunst \
#    unrar perl-anyevent perl-anyevent-i3 lolcat figlet youtube-dl urxvt-perls \
#    trash-cli atom python-pywal vim-latexsuite calibre jq wmctrl polybar \
#    vim-runtime gvim neovim xclip xsel firefox maim zathura-pdf-mupdf
##hsetroot xautolock
#sudo cpan AnyEvent Linux::FD common::sense
#cd ~
echo -e "$blu"
cat << 'EOB'


================================================================================
================================= FINAL STEPS! =================================
================================================================================

 - GET CONFIGS FROM GITHUB:
 - OPEN RANGER OR OTHER FILE MANAGER AND COPY SYMLINKS OF THE NECESSARY
     FOLDERS AND FILES
 - AUR APPS I GET TOO:
       slack-desktop           i3lock-color          vivaldi
       oni                     thunar-gtk2           google-chrome-beta
       chrome-remote-desktop   spotify               grive
       clipit                  pulseaudio-ctl        zathura-pdf-mupdf
       xorg-xbacklight         light                 bashmount
       i3blocks-gaps-git       mpris-ctl             figlet-fonts
       urxvt-config-reload-git urxvt-resize-font-git i3ipc-python
       cli-visualizer          pamac-aur             gtkrc-reload
       ranger-git              betterlockscreen      vim-live-latex-preview
       hideit.sh-git

EOB
echo -e "$wtl"
