#!/bin/bash

bkd="\033[1;30m"
bkl="\033[1;30m"
red="\033[1;31m"
grn="\033[1;32m"
rng="\033[1;33m"
ylw="\033[1;33m"
blu="\033[1;34m"
gnt="\033[1;35m"
cyn="\033[1;36m"
wtd="\033[1;37m"
wtl="\033[0m"
cd ~

cat <<EOB
$blu
================================================================================
============================ INSTALLING YOUR PROGRAMS ==========================
================================================================================
$wtl
sudo pacman -S rofi otf-font-awesome ttf-font-awesome nautilus evince mupdf \
	pinta redshift playerctl mplayer r tk gcc-fortran newsboat opencv \
	python-matplotlib python2-matplotlib python-numpy python2-numpy hdf5 \
	libreoffice pandoc pandoc-crossref pandoc-citeproc python-pygments \
	python2-pygments biber texlive-most acpi lm_sensors sysstat ntfs-3g \
	libmpdclient lxappearance sxiv ncurses fftw w3m mpd mpc ncmpcpp feh dunst \
	unrar perl-anyevent perl-anyevent-i3 lolcat figlet youtube-dl urxvt-perls \
	trash-cli atom python-pywal vim-latexsuite calibre jq wmctrl polybar \
	vim-runtime gvim neovim xclip xsel firefox maim zathura-pdf-mupdf id3v2 \
	hsetroot xorg-xsetroot xautolock xorg-xev sxhkd wmutils i3lock-color \
	glib2 gdk-pixbuf2 ruby-sass inkscape glava gthumb
sudo cpan AnyEvent Linux::FD common::sense
cd ~
xfconf-query --channel thunar --property /misc-full-path-in-title --create --type bool --set true
EOB


cat <<EOB
$blu
================================================================================
================================= FINAL STEPS! =================================
================================================================================

- GET CONFIGS FROM GITHUB:
- OPEN RANGER OR OTHER FILE MANAGER AND COPY SYMLINKS OF THE NECESSARY
	FOLDERS AND FILES
- AUR APPS I GET TOO:
	slack-desktop
	mmutils-git             thunar-gtk2           google-chrome-beta
	chrome-remote-desktop   spotify               grive
	clipit                  pulseaudio-ctl        zathura-pdf-mupdf
	xorg-xbacklight         light                 bashmount
	                        mpris-ctl             figlet-fonts
	urxvt-config-reload-git urxvt-resize-font-git i3ipc-python-git
	cli-visualizer          pamac-aur             gtkrc-reload
	ranger-git              wordgrinder           vim-live-latex-preview
$wtl
EOB


cat <<EOB
$blu
================================================================================
============================= UPDATE & GET MY REPOS ============================
================================================================================
$wtl
sudo pacman -Syyu
mkdir ~/Drive
mkdir ~/.tmp
mkdir ~/git
cd ~/git
git clone https://github.com/StillANixRookie/icons_themer.git
git clone https://github.com/StillANixRookie/numix-solarized-gtk-theme.git
cd
EOB
