#!/bin/bash

blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

dir=$HOME/.themes/MINE/gtk-2.0/menubar-toolbar/

cd $dir

echo -e "style \"menubar\" {" > menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  bg[NORMAL] = \"$blue\"" >> menubar-toolbar-dark.rc
echo -e "  fg[NORMAL] = \"$whited\"" >> menubar-toolbar-dark.rc
echo -e "  fg[PRELIGHT] = \"$blackl\"" >> menubar-toolbar-dark.rc
echo -e "  fg[ACTIVE] = \"$blackl\"" >> menubar-toolbar-dark.rc
echo -e "  fg[SELECTED] = \"$whitel\"" >> menubar-toolbar-dark.rc
echo -e "  fg[INSENSITIVE] = shade(1.3, \"$blackl\")" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  xthickness = 0" >> menubar-toolbar-dark.rc
echo -e "  ythickness = 0" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  engine \"pixmap\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = BOX" >> menubar-toolbar-dark.rc
echo -e "      file  = \"menubar-toolbar/menubar.png\"" >> menubar-toolbar-dark.rc
echo -e "      stretch  = TRUE" >> menubar-toolbar-dark.rc
echo -e "      border = { 1, 1, 1, 1 }" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "  }" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "style \"menubar-borderless\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  bg[NORMAL] = \"$blue\"" >> menubar-toolbar-dark.rc
echo -e "  fg[NORMAL] = \"$blackl\"" >> menubar-toolbar-dark.rc
echo -e "  fg[SELECTED] = @fg_color" >> menubar-toolbar-dark.rc
echo -e "  fg[INSENSITIVE] = shade(1.3, \"$blackl\")" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  xthickness = 0" >> menubar-toolbar-dark.rc
echo -e "  ythickness = 0" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  engine \"pixmap\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = BOX" >> menubar-toolbar-dark.rc
echo -e "      file  = \"assets/null.png\"" >> menubar-toolbar-dark.rc
echo -e "      stretch  = TRUE" >> menubar-toolbar-dark.rc
echo -e "      border = { 1, 1, 1, 1 }" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "  }" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "style \"menubar_item\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  xthickness = 2" >> menubar-toolbar-dark.rc
echo -e "  ythickness = 4" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  fg[PRELIGHT] = @selected_fg_color" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  engine \"pixmap\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = BOX" >> menubar-toolbar-dark.rc
echo -e "      state = PRELIGHT" >> menubar-toolbar-dark.rc
echo -e "      file = \"menubar-toolbar/menubar_button.png\"" >> menubar-toolbar-dark.rc
echo -e "      border = { 2, 2, 2, 2 }" >> menubar-toolbar-dark.rc
echo -e "      stretch = TRUE" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "  }" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "# Text Style Menubar" >> menubar-toolbar-dark.rc
echo -e "style \"menubar-text\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  engine \"murrine\" {" >> menubar-toolbar-dark.rc
echo -e "    text_shade = 0.0" >> menubar-toolbar-dark.rc
echo -e "    textstyle = 0" >> menubar-toolbar-dark.rc
echo -e "  }" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "style \"toolbar_entry\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  text[NORMAL] = \"$whited\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  engine \"pixmap\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = SHADOW" >> menubar-toolbar-dark.rc
echo -e "      state = NORMAL" >> menubar-toolbar-dark.rc
echo -e "      detail = \"entry\"" >> menubar-toolbar-dark.rc
echo -e "      file = \"menubar-toolbar/entry-toolbar.png\"" >> menubar-toolbar-dark.rc
echo -e "      border = {6, 6, 6, 6}" >> menubar-toolbar-dark.rc
echo -e "      stretch = TRUE" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = SHADOW" >> menubar-toolbar-dark.rc
echo -e "      state = ACTIVE" >> menubar-toolbar-dark.rc
echo -e "      detail = \"entry\"" >> menubar-toolbar-dark.rc
echo -e "      file = \"menubar-toolbar/entry-active-toolbar.png\"" >> menubar-toolbar-dark.rc
echo -e "      border = {6, 6, 6, 6}" >> menubar-toolbar-dark.rc
echo -e "      stretch = TRUE" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = SHADOW" >> menubar-toolbar-dark.rc
echo -e "      state = INSENSITIVE" >> menubar-toolbar-dark.rc
echo -e "      detail = \"entry\"" >> menubar-toolbar-dark.rc
echo -e "      file = \"menubar-toolbar/entry-disabled-toolbar.png\"" >> menubar-toolbar-dark.rc
echo -e "      border = {6, 6, 6, 6}" >> menubar-toolbar-dark.rc
echo -e "      stretch = TRUE" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = FLAT_BOX" >> menubar-toolbar-dark.rc
echo -e "      state    = ACTIVE" >> menubar-toolbar-dark.rc
echo -e "      detail   = \"entry_bg\"" >> menubar-toolbar-dark.rc
echo -e "      file     = \"assets/null.png\"" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = FLAT_BOX" >> menubar-toolbar-dark.rc
echo -e "      state    = INSENSITIVE" >> menubar-toolbar-dark.rc
echo -e "      detail   = \"entry_bg\"" >> menubar-toolbar-dark.rc
echo -e "      file     = \"assets/null.png\"" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "    image {" >> menubar-toolbar-dark.rc
echo -e "      function = FLAT_BOX" >> menubar-toolbar-dark.rc
echo -e "      detail   = \"entry_bg\"" >> menubar-toolbar-dark.rc
echo -e "      file     = \"assets/null.png\"" >> menubar-toolbar-dark.rc
echo -e "    }" >> menubar-toolbar-dark.rc
echo -e "  }" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "#Chromium" >> menubar-toolbar-dark.rc
echo -e "style \"chrome-gtk-frame\" {" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::frame-color = \"$blue\"" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::inactive-frame-color = \"$blue\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::frame-gradient-size = 0" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::frame-gradient-color = shade(0.5, @bg_color)" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::incognito-frame-color = shade(0.85, @bg_color)" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::incognito-inactive-frame-color = @bg_color" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::incognito-frame-gradient-color = @bg_color" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::scrollbar-trough-color = shade(0.912, @bg_color)" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::scrollbar-slider-prelight-color = shade(1.04, @bg_color)" >> menubar-toolbar-dark.rc
echo -e "  ChromeGtkFrame::scrollbar-slider-normal-color = @bg_color" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "}" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*<GtkMenuBar>*\"                                       style \"menubar\"" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*<GtkMenuBar>.<GtkMenuItem>*\"                         style \"menubar_item\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*ThunarWindow*<GtkToolbar>\"                           style \"menubar\"" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*CajaNavigationWindow*<GtkToolbar>\"                   style \"menubar\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "class \"ChromeGtkFrame\"                                              style \"chrome-gtk-frame\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*<GtkMenuBar>*<GtkMenuItem>*<GtkAccelLabel>\"          style \"menubar-text\"" >> menubar-toolbar-dark.rc
echo -e "" >> menubar-toolbar-dark.rc
echo -e "# Whitelist for dark toolbars" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*ThunarWindow*<GtkMenuBar>\"                           style \"menubar-borderless\"" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*CajaNavigationWindow*<GtkMenuBar>\"                   style \"menubar-borderless\"" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*ThunarWindow*<GtkToolbar>*<GtkEntry>\"                style \"toolbar_entry\"" >> menubar-toolbar-dark.rc
echo -e "widget_class \"*CajaNavigationWindow*<GtkToolbar>*<GtkEntry>\"        style \"toolbar_entry\"" >> menubar-toolbar-dark.rc
