#!/bin/bash

blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

dir=$HOME/.themes/own/gtk-2.0

cd $dir

echo -e "style \"default-style\"" > gtkrc
echo -e "{" >> gtkrc
echo -e "	fg[NORMAL]        = \"$whitel\"        # Main Menu TEXT colour" >> gtkrc
echo -e "	fg[PRELIGHT]      = \"$whitel\"        # slightly darker than main text   " >> gtkrc
echo -e "	fg[ACTIVE]        = \"$whited\"        # lighter again than above   " >> gtkrc
echo -e "	fg[SELECTED]      = \"#000000\"        # black was white - #ffffff" >> gtkrc
echo -e "	fg[INSENSITIVE]   = \"$blackl\"        # Inactive menu entries & inactive highlight)\n" >> gtkrc

echo -e "	bg[NORMAL]        = \"$blackl\"        # Main Menu BACKGROUND colour - was #424242" >> gtkrc
echo -e "	bg[PRELIGHT]      = \"$blue\"        # active highlight" >> gtkrc
echo -e "	bg[ACTIVE]        = \"$blackd\"        # darker secondary b'ground - rarely used -     where (Firefox scroll bar)??" >> gtkrc
echo -e "	bg[SELECTED]      = \"$blue\"        # active highlight - was -> #5058a0" >> gtkrc
echo -e "	bg[INSENSITIVE]   = \"$blue\"        # lighter minor background     \n" >> gtkrc

echo -e "	text[NORMAL]      = \"$whited\"        # Main Text, including fields" >> gtkrc
echo -e "	text[PRELIGHT]    = \"$whited\"        #   \"    \"       \"       \"   " >> gtkrc
echo -e "	text[ACTIVE]      = \"$whited\"        #   \"    \"       \"       \" " >> gtkrc
echo -e "	text[SELECTED]    = \"$whited\"        #   \"    \"       \"       \" " >> gtkrc
echo -e "	text[INSENSITIVE] = \"$whitel\"        # inactive highlight - was #6F6F6F\n" >> gtkrc

echo -e "	base[NORMAL]      = \"$blackd\"        # darker - secondary background colour" >> gtkrc
echo -e "	base[PRELIGHT]    = \"$blue\"        # active highlight & menu entries" >> gtkrc
echo -e "	base[ACTIVE]      = \"$whitel\"        # inactive highlight" >> gtkrc
echo -e "	base[SELECTED]    = \"$blue\"        # active highlight" >> gtkrc
echo -e "	base[INSENSITIVE] = \"$whitel\"        # lighter minor background" >> gtkrc
echo -e "}\n" >> gtkrc

echo -e "class \"GtkWidget\" style \"default-style\"" >> gtkrc
