#!/usr/bin/env bash

SPAR=$1
SCHL=1
MRKS=$(i3-msg -t get_marks)

urxvtc

if [[ $MRKS != *"_sticky_${SPAR}"* ]]; then
	CMD="i3-msg [con_id=__focused__] mark _sticky_${SPAR}"
	echo True
elif [[ $MRKS =~ "_sticky_${SPAR}" ]]; then
	while [[ $MRKS =~ "_sticky_${SPAR}_${SCHL}" ]]; do
		SCHL+=1
	done
	CMD="i3-msg [con_id=__focused__] mark _sticky_${SPAR}_${SCHL}"
fi

${CMD}
