#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Fri 17 May 18:47:08 BST 2019

NMFL=$USER_TMP_DIR/nightmode
[[ -f $NMFL ]] || echo off > $NMFL
CRMD=$(cat $NMFL)

if [[ $CRMD == "off" ]]; then
	redshift -P -O 3700
	echo on > $NMFL
elif [[ $CRMD == "on" ]]; then
	redshift -x
	echo off > $NMFL
fi
