#!/usr/bin/env bash

I3="i3-msg -q"
TTLB=22 BRDR=2 POR=0
DECH=$((TTLB + BRDR)) DECW=$((2*BRDR))
CMD="$I3 resize"

help() {
cat << 'EOB'
# NAME

__resar__ -- resize windows based on aspect ratio

# SYNOPSIS

```
resar --inc|-i|--dec|-d <w|h> <integer>
      --archange|-a <ratio>
resar --help|-h
```

# DEPENDENCIES

```
wmutils
wmctrl
```
EOB
}

archange() {
	local W H WD HD ARN DIR
	ARN=$1 FIX=$2
}

getdeets() {
#	eval "$(wmctrl -lG | \
#		awk -v FOC="$(pfw)" -v DECW="$DECW" -v DECH="$DECH" '
#			$1 ~ FOC {
#				W=$5-DECW;H=$6-DECH
#				print "OW="$5 "\nOH="$6 "\nW="W "\nH="H "
#				}')"
	W=$(wattr w $(pfw))
	H=$(wattr h $(pfw))
}

resize() {
	DIR=$1 ; AMT=$2
	getdeets
	echo $DIR $AMT
	echo $OW $OH $W $H

	if [[ $DIR == "i" ]]; then
		eval "$(echo "" | awk -v H="$H" -v W="$W" -v AMT="$AMT" -v AR="$AR" 'BEGIN{
			W=((100+AMT)/100)*W
			H=((100+AMT)/100)*H
			print "W="int(W) "\nH="int(H)
		}')"

	else
		eval "$(echo "" | awk -v H="$H" -v W="$W" -v AMT="$AMT" -v AR="$AR" 'BEGIN{
			W=((100-AMT)/100)*W
			H=((100-AMT)/100)*H
			print "W="int(W) "\nH="int(H)
		}')"

	fi
	echo $W $H
#	i3-msg resize set $((W+DECW)) $((H+DECH))
	i3-msg resize set $W $H
	exit
}

while true; do
	case $1 in
		--inc      | -i | i ) resize i ${2:-} ${3:-} ; shift ;;
		--dec      | -d | d ) resize d ${2:-} ${3:-} ; shift ;;
		--archange | -a | a ) archange "${2:-}" ${3:-} ; shift ;;
		--mark     | -m | m ) MRK="${2:-}" ; shift ;;
		--help ) help ;;
		-h ) help | \
			sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
			sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g'
			exit
			;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done
