#!/bin/bash

echo "${1}" > files
sed -e "s/'\ '/\n/g;s/'//g" -i files
IFS=$'\n'
ANS=$(cat files | i3menu -T -o -c red \
	-e "DELETE THESE FILES??? [ESC=NO; RETURN=YES]")
[[ -n $ANS ]] && {
	for i in $(cat files); do
		rm -rf "$i"
	done
	}
rm files
