#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')

bat=$(acpi | awk '{ print $4 }')

if [[ ${#bat} == 3 ]]; then
    rawbat=${bat:0:-1}
elif [[ ${bat} == "100%" ]]; then
    rawbat="100"
else
    rawbat=${bat:0:-2}
fi

statu=$(acpi | awk '{ print $3 }')
tim=$(acpi | awk '{ print $5 }')

if [[ -z "$tim" ]]; then
    tim2=
else
    tim2="${tim:0:-3}"
fi

if [[ $statu == "Charging," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf0e7;</span>"
elif [[ $statu == "Unknown," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf1e6;</span>"
elif [[ $statu == "Full," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf1e6;</span>"
else
    stat=""
fi

if [[ $rawbat -le 50 ]]; then
    echo "<span background=\"#ffff00\"> <span face='Font Awesome 5 Free'>&#xf242;</span> $stat $tim2 </span>"
elif [[ $rawbat -le 25 ]]; then
    echo "<span background=\"#ff0000\"> <span face='Font Awesome 5 Free'>&#xf243;</span> $stat $tim2 </span>"
elif [[ $rawbat -le 10 ]]; then
    echo "<span background=\"#ff0000\"> <span face='Font Awesome 5 Free'>&#xf244;</span> $stat $tim2 </span>"
elif [[ $rawbat -le 75 ]]; then
    echo "<span background=\"$white\"> <span face='Font Awesome 5 Free'>&#xf241;</span> $stat $tim2 </span>"
elif [[ $statu == "Unknown," ]]; then
    echo "<span background=\"$blue\"> <span face='Font Awesome 5 Free'>&#xf240;</span> $stat $tim2</span>"
elif [[ $statu == "Full," ]]; then
    echo "<span background=\"$blue\"> <span face='Font Awesome 5 Free'>&#xf240;</span> $stat $tim2</span>"
else
    echo "<span background=\"$blue\"> <span face='Font Awesome 5 Free'>&#xf240;</span> $tim2 </span>"
fi
