#!/bin/bash

iconFu="<span face='Font Awesome 5 Free'>&#xf240;</span>"
icon75="<span face='Font Awesome 5 Free'>&#xf241;</span>"
icon50="<span face='Font Awesome 5 Free'>&#xf242;</span>"
icon25="<span face='Font Awesome 5 Free'>&#xf243;</span>"
icon00="<span face='Font Awesome 5 Free'>&#xf244;</span>"

bat=$(acpi | awk '{ print $4 }')

if [[ ${#bat} == 3 ]]; then
    rawbat=${bat:0:-1}
elif [[ ${bat} == "100%" ]]; then
    rawbat="100"
else
    rawbat=${bat:0:-2}
fi

statu=$(acpi | awk '{ print $3 }')
tim=$(acpi | awk '{ print $5 }')

if [[ -z "$tim" ]]; then
    tim2=
else
    tim2="${tim:0:-3}"
fi

if [[ $statu == "Charging," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf1e6;</span>"
elif [[ $statu == "Unknown," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf00c;</span>"
elif [[ $statu == "Full," ]]; then
    stat="<span face='Font Awesome 5 Free'>&#xf00c;</span>"
else
    stat=""
fi

if [[ $rawbat -le 50 ]]; then
    echo "<span foreground=\"#ffff00\">${bat:0:-1} $icon50 $stat $tim2</span>"
elif [[ $rawbat -le 25 ]]; then                
    echo "<span foreground=\"#ff0000\">${bat:0:-1} $icon25 $stat $tim2</span>"
elif [[ $rawbat -le 10 ]]; then                
    echo "<span background=\"#ff0000\">${bat:0:-1} $icon00 $stat $tim2</span>"
elif [[ $rawbat -le 75 ]]; then
    echo "${bat:0:-1} $icon75 $stat $tim2"
elif [[ $statu == "Unknown," ]]; then
    echo "$iconFu $stat"
elif [[ $statu == "Full," ]]; then
    echo "$iconFu $stat"
elif [[ $rawbat == "100" ]]; then
    echo "$iconFu $stat"
else
    echo "${bat:0:-1} $iconFu $stat $tim2"
fi
