#!/usr/bin/env bash

case $BLOCK_BUTTON in
	# right click
	# set to `20
	#3) light -set 20 ;;

	# scroll up
	# raise brightness
	4) light -A 10 ;;

	# scroll down
	# lower brightness
	5) light -U 10 ;;
esac

blr=$(light -G)

bl=$(printf "%.0f" $blr)

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

echo " <span face='Font Awesome 5 Free'>&#xf042;</span> ${bl}% "
