#!/usr/bin/env bash

icon="<span face='Font Awesome 5 Free'>&#xf2db;</span>"

idle=$(top -b -n1 | sed -n 's/.* ni, \([^ ]*\).*/\1/p')
idlelen=$(echo $idle | tr ' ' '\n' | wc -l)
idletot=$(echo $idle | tr ' ' '\n' | awk '{s+=$1} END {print s}')

if [[ $idletot == *[.]* ]]; then
	cpu=$(expr 100 - ${idletot:0:-2} / $idlelen)
else
	cpu=$(expr 100 - ${idletot} / $idlelen)
fi

if [[ $cpu -ge 80 ]]; then
    echo "<span foreground=\"#ff0000\">$icon $cpu</span>"
elif [[ $cpu -ge 50 ]]; then
    echo "<span foreground=\"#ffff00\">$icon $cpu</span>"
else
    echo "$icon $cpu"
fi
