#!/bin/bash

idle=$(top -b -n1 | grep %Cpu | awk '{print $9}' | sed -e "s/^id,//")
idlelen=$(echo $idle | tr ' ' '\n' | wc -l)
idletot=$(echo $idle | tr ' ' '\n' | awk '{s+=$1} END {print s}')

if [[ $idletot == *[.]* ]]; then
	cpu=$(expr 100 - ${idletot:0:-2} / $idlelen)
else
	cpu=$(expr 100 - ${idletot} / $idlelen)
fi

#echo $cpu

if [[ $cpu -ge 80 ]]; then
    echo "<span foreground=\"#ff0000\"><span face='Font Awesome 5 Free'>&#xf2db;</span> $cpu</span>"
elif [[ $cpu -ge 50 ]]; then
    echo "<span foreground=\"#ffff00\"><span face='Font Awesome 5 Free'>&#xf2db;</span> $cpu</span>"
else
    echo "<span face='Font Awesome 5 Free'>&#xf2db;</span> $cpu"
fi
