#!/bin/bash

icon="<span face='Font Awesome 5 Free'>&#xf0a0;</span>"

DIR="${BLOCK_INSTANCE:-$HOME}"

avail=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $4}')
usep=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $5}')
use=${usep:0:-1}

if [[ $use -ge 90 ]]; then
    echo "<span foreground=\"#ff0000\">$icon $avail</span>"
else
    echo "$icon $avail"
fi
