#!/bin/bash

mpris=$(pidof spotify)
mpv=$(pidof mpv)
mpvtitle="$(xdotool getwindowname $(xdotool search --class mpv))"

blocksDir="$HOME/scripts/blocks"

if [[ -n $mpv ]]; then
	echo "<span face='Font Awesome 5 Free'>&#xf03d;</span> ${mpvtitle:0:-6}"
elif [[ -n $mpris ]]; then
	bash $blocksDir/mpgui
else
	bash $blocksDir/mpcblk
fi

case $BLOCK_BUTTON in
  1) bash $HOME/scripts/i3media togg ;;
  3) bash $HOME/scripts/i3media stop ;;
  4) bash $HOME/scripts/i3media next ;;
  5) bash $HOME/scripts/i3media prev ;;
esac
