#!/bin/bash

playing=$(mpc current)

if [ -z "$playing" ]
then
	:
else
	echo " <span face='Font Awesome 5 Free'>&#xf001;</span> ${playing} "
fi

case $BLOCK_BUTTON in
  3) mpc prev ;;  # next song
  2) mpc toggle ;;  # next song
  1) mpc next ;;  # next song
esac
