#!/bin/bash

playername=$(mpris-ctl info "%player_name")
trackname=$(mpris-ctl info "%track_name")
artistname=$(mpris-ctl info "%artist_name")
playstatus=$(mpris-ctl info "%play_status")

playing="$playername: $trackname - $artistname"

if [ $playername == "%player_name" ]; then
	:
if [ -z $playername ]; then
	:
elif [ $playstatus == "Paused" ]; then
	echo " <span face='Font Awesome 5 Free'>&#xf28b;</span> ${playing:0:50} "
else
	echo " <span face='Font Awesome 5 Free'>&#xf144;</span> ${playing:0:50} "
fi

case $BLOCK_BUTTON in
  3) playerctl previous ;;  # next song
  2) playerctl play-pause ;;  # next song
  1) playerctl next ;;  # next song
esac
