#!/bin/bash

playername=$(mpris-ctl info "%player_name")
trackname=$(mpris-ctl info "%track_name")
artistname=$(mpris-ctl info "%artist_name")
playstatus=$(mpris-ctl info "%play_status")

if [[ ${#trackname} -ge 20 ]]; then
    trackname="${trackname:0:-13}..."
else
    trackname=$trackname
fi
if [[ ${#artistname} -ge 20 ]]; then
    artistname="${artistname:0:-13}..."
else
    artistname=$artistname
fi

playing="$playername: $artistname > $trackname"

if [ $playername == "%player_name" ]; then
	:
elif [ -z $playername ]; then
	:
elif [ $playstatus == "Paused" ]; then
	echo "<span face='Font Awesome 5 Free'>&#xf28b;</span> ${playing}"
else
	echo "<span face='Font Awesome 5 Free'>&#xf144;</span> ${playing}"
fi

case $BLOCK_BUTTON in
  3) playerctl previous ;;  # next song
  2) playerctl play-pause ;;  # next song
  1) playerctl next ;;  # next song
esac
