#!/bin/bash

volraw=$(amixer get Master|grep 'Front Left:'|awk '{print $5}')
stat=$(amixer get Master|grep 'Front Left:'|awk '{print $6}')
vol=${volraw:1:-1}
volint=${volraw:1:-2}

if [[ $volint -ge 80 ]]; then
    echo "<span foreground=\"#ff0000\"><span face='Font Awesome 5 Free'>&#xf028;</span> $vol</span>"
elif [[ $volint -ge 60 ]]; then
    echo "<span foreground=\"#ffff00\"><span face='Font Awesome 5 Free'>&#xf028;</span> $vol</span>"
elif [[ $stat == "[off]" ]]; then
    echo "<span face='Font Awesome 5 Free'>&#xf6a9;</span>"
elif [[ $volint -le 30 ]]; then
    echo "<span face='Font Awesome 5 Free'>&#xf027;</span> $vol"
elif [[ $volint == 0 ]]; then
    echo "<span face='Font Awesome 5 Free'>&#xf026;</span> $vol"
else
    echo "<span face='Font Awesome 5 Free'>&#xf028;</span> $vol"
fi

case $BLOCK_BUTTON in
  3) pactl set-sink-mute 0 toggle ;;  #     right click, mute/unmute
  4) pactl set-sink-volume 0 +5% ;; # scroll up, increase
  5) pactl set-sink-volume 0 -5% ;; # scroll down, decrease 
esac
