#!/bin/bash

# OA: Gavin Vales
# CREATED: Thu  4 Jul 23:35:23 BST 2019

SCR="$HOME/scr/thunar"
FLS="$1"
COM=$(ls -l $SCR | sed -e "/thunarcommand/d;/thunarview/d;/total/d" | \
	awk '{print $NF}' | \
	$HOME/scr/i3menu -t -c black -r $(ls -l $SCR | \
	sed -e "/thunarcommand/d;/thunarview/d;/total/d" | \
	wc -l) -o vertical -p ": ")
bash ${SCR}/${COM} "${FLS}"
