#!/bin/bash

# OA: Gavin Vales
# CREATED: Thu  4 Jul 23:35:23 BST 2019

SCR="$HOME/scr/thunar"
FLS="$1"
COM=$(ls -l $SCR | sed -e "/thunarcommand/d;/total/d" | \
	awk '{print $NF}' | \
	i3menu --prompt ": " -T -c black -o vertical)
bash ${SCR}/${COM} "${FLS}"
