.TH BANNER 1 2019\-11\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]banner\f[R] - Simple figlet wrapper
.SH SYNOPSIS
.IP
.nf
\f[B]
banner [--centre|-c] \fI<text>\fP
banner [--help|-h]
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[B]
figlet
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--centre|-c \fI<text>\fP\f[R]
.PD 0
.P
.PD
centre
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
print this help
.SH IN PROGRESS
.PP
\f[B]--slant|-s\f[R]
.PD 0
.P
.PD
slant
.PP
\f[B]--banner3|-b\f[R]
.PD 0
.P
.PD
banner3
.PP
\f[B]--larry3d|-i\f[R]
.PD 0
.P
.PD
larry3d
.PP
\f[B]--letters|-l\f[R]
.PD 0
.P
.PD
letters
.PP
\f[B]--roman|-r\f[R]
.PD 0
.P
.PD
roman
.PP
\f[B]--smisome1|-m\f[R]
.PD 0
.P
.PD
smisome1
.PP
\f[B]--trek|-t\f[R]
.PD 0
.P
.PD
trek
.PP
\f[B]--speed|-f\f[R]
.PD 0
.P
.PD
speed
.PP
\f[B]--smkeyboard|-k\f[R]
.PD 0
.P
.PD
smkeyboard
