.TH CMKD 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]cmkd\f[R] - compile markdown files with pandoc by parsing the yaml
header
.SH SYNOPSIS
.IP
.nf
\f[B]
cmkd \fI<file>\fP.md
cmkd --help|-h
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[B]
pandoc
\f[R]
.fi
.SH EXAMPLE
.IP
.nf
\f[B]
---
title: __Title__
subtitle: _Subtitle_
author: Author
theme: CambridgeUS
#output pdf html word beamer  \fI<\fI<\fI< specify output(s)
#css    style.css             \fI<\fI<\fI< full path to css for html output
#engine xelatex               \fI<\fI<\fI< TeX engine for normal pdf
#bib    bibliography.bib      \fI<\fI<\fI< full path to bibliography
#yaml   settings.yaml         \fI<\fI<\fI< full path to yaml file for additional settings
#docx   reference.docx        \fI<\fI<\fI< full path to word document template
---

# A markdown file

+ bullet
    + bullet
        + bullet
+ bullet
+ bullet
\f[R]
.fi
