.TH CMKD 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]cmkd\f[R] - compile markdown files with pandoc by parsing the yaml
header
.SH SYNOPSIS
.IP
.nf
\f[C]
cmkd <file>.md
cmkd --help|-h
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[C]
pandoc
\f[R]
.fi
.SH EXAMPLE
.IP
.nf
\f[C]
---
title: __Title__
subtitle: _Subtitle_
author: Author
theme: CambridgeUS
#output pdf html word beamer  <<< specify output(s)
#css    style.css             <<< full path to css for html output
#engine xelatex               <<< TeX engine for normal pdf
#bib    bibliography.bib      <<< full path to bibliography
#yaml   settings.yaml         <<< full path to yaml file for additional settings
#docx   reference.docx        <<< full path to word document template
---

# A markdown file

+ bullet
    + bullet
        + bullet
+ bullet
+ bullet
\f[R]
.fi
