.TH COLMIX 1 2019\-11\-12 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]colmix\f[R] - Script to mix 2 hex colors
.SH SYNOPSIS
.IP
.nf
\f[B]
colmix [--hex|-x|--rgb|-r|--verbose|-v] \fI<ratio1>\fP:\fI<color1>\fP \fI<ratio2>\fP:\fI<color2>\fP
colmix --help|-h
\f[R]
.fi
.SH EXAMPLE
.IP
.nf
\f[B]
$ colmix 50:#00ff00 50:#002b36
  00951b
  0, 149, 27
\f[R]
.fi
.PP
So [IMAGE: #00ff00 (https://placehold.it/15/00ff00/000000?text=+)]
#00ff00 +
[IMAGE: #002b36 (https://placehold.it/15/002b36/000000?text=+)] #002b36
= [IMAGE: #00951b (https://placehold.it/15/00951b/000000?text=+)]
#00951b!
.SH OPTIONS
.PP
Final argument has to be \f[B]\fI<ratio1>\fP:\fI<color1>\fP \fI<ratio2>\fP:\fI<color2>\fP\f[R]
.PD 0
.P
.PD
+ eg.
\f[B]50:#000000 50:#ffffff\f[R]
.PD 0
.P
.PD
+ Ratios are percentages, so \f[B]\fI<ratio1>\fP + \fI<ratio2>\fP = 100\f[R]
.PP
\f[B]--hex|-x\f[R]
.PD 0
.P
.PD
Print final color in hex
.PP
\f[B]--rgb|-r\f[R]
.PD 0
.P
.PD
Print final color in rgb
.PP
\f[B]--verbose|-v\f[R]
.PD 0
.P
.PD
Print input colors and rgb versions as well
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
