.TH EDTR 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]edtr\f[R] - vim server wrapper
.SH SYNOPSIS
.IP
.nf
\f[C]
edtr [--server|-s <name>] <file>
edtr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--server|-s <name>\f[R]
.PD 0
.P
.PD
`-\f[B]<name>\f[R]' is appended to the default \f[B]--servername\f[R].
Default \f[B]--servername\f[R] is `edtr'.
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
