.TH GEDTR 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gedtr\f[R] - gvim server wrapper
.SH SYNOPSIS
.IP
.nf
\f[C]
gedtr [--server|-s <name>] <file>
gedtr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--server|-s <name>\f[R]
.PD 0
.P
.PD
Specify server name.
Default is \f[B]GVIM\f[R].
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
