.TH GEDTR 1 2019\-10\-24 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gedtr\f[R] - gvim server wrapper
.SH SYNOPSIS
.IP
.nf
\f[B]
gedtr [--server|-s \fI<name>\fP] \fI<file>\fP
gedtr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--server|-s \fI<name>\fP\f[R]
.PD 0
.P
.PD
Specify server name.
Default is \f[B]GVIM\f[R].
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
