.TH GENCVL 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gencvl\f[R] - job application cover letter generator using
\f[C]markdown\f[R] and \f[C]pandoc\f[R]
.SH SYNOPSIS
.IP
.nf
\f[C]
gencvl <name>
gencvl --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]<name>\f[R]
.PD 0
.P
.PD
\f[C]<name>\f[R] of coverletter
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
