.TH GENCVL 1 2019\-10\-24 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gencvl\f[R] - job application cover letter generator using
\f[B]markdown\f[R] and \f[B]pandoc\f[R]
.SH SYNOPSIS
.IP
.nf
\f[B]
gencvl \fI<name>\fP
gencvl --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]\fI<name>\fP\f[R]
.PD 0
.P
.PD
\f[B]\fI<name>\fP\f[R] of coverletter
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
