.TH GHB 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]ghb\f[R] - a hugo blog wrapper script
.SH DEPENDENCIES
.IP
.nf
\f[C]
hugo
\f[R]
.fi
.SH SYNOPSIS
.IP
.nf
\f[C]
ghb --post|-p|--delete|-d <name>
ghb --list|-l
ghb --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--post|-p <name>\f[R]
.PD 0
.P
.PD
\f[B]<name>\f[R] of post to create
.PP
\f[B]--list|-l\f[R]
.PD 0
.P
.PD
list all posts
.PP
\f[B]--delete|-d <name>\f[R]
.PD 0
.P
.PD
\f[B]<name>\f[R] of post to delete
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
