.TH GOSTE 1 2020\-01\-03 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]goste\f[R] - create notes, with different types, stored in
$XDG_DESKTOP_DIR/goste
.SH SYNOPSIS
.IP
.nf
\f[B]
goste --create|-c|--open|-o \fI<type>\fP
goste --list-entries|-l|--delete-type|-D \fI<type>\fP
goste --list-types|-L
goste --help|-h
goste
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[B]
i3menu edtr urxvt banner
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create defaults:
.PD 0
.P
.PD
\f[B]GOSTE_DIR\f[R] = \f[B]$HOME/Desktop/goste\f[R]
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.PP
\f[B]--create|-c \fI<type>\fP\f[R]
.PD 0
.P
.PD
Create $GOSTE_DIR/\f[B]\fI<type>\fP\f[R]
.PP
\f[B]--open|-o \fI<type>\fP\f[R]
.PD 0
.P
.PD
Open $GOSTE_DIR/\f[B]\fI<type>\fP\f[R]
.PP
\f[B]--delete-type|-D \fI<type>\fP\f[R]
.PD 0
.P
.PD
Delete $GOSTE_DIR/\f[B]\fI<type>\fP\f[R]
.PP
\f[B]--list-entries|-l\f[R]
.PD 0
.P
.PD
Print contents of $GOSTE_DIR/\f[B]\fI<type>\fP\f[R]
.PP
\f[B]--list-types|-L \fI<type>\fP\f[R]
.PD 0
.P
.PD
\f[B]ls\f[R] $GOSTE_DIR
