.TH GWC 1 2019\-12\-08 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gwc\f[R] - A script to set wallpaper, with other features.
.SH SYNOPSIS
.IP
.nf
\f[B]
gwc [--wallpaper|-w \fI<path|name|color|random|previous|next>\fP]
    [--next|-n] [--previous|-p] [--random|-r]
    [--tint|-t \fI<hex_color>\fP] [--blur|-b]
gwc --add|-a \fI<directory|path>\fP
gwc --list|-l
gwc --rename|-R \[aq]\fI<oldname>\fP \fI<newname>\fP\[aq]
gwc --delete|-d \[aq]\fI<name>\fP\[aq]
gwc --help|-h
gwc
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create default directories:
.PD 0
.P
.PD
+ \f[B]$GWCDIR/(normal|blur|cols)\f[R] + Default \f[B]gwc\f[R] database:
\f[B]GWCDIR\f[R] = \f[B]$XDG_PICTURES_DIR/gwc\f[R]
.PP
\f[B]--wallpaper|-w \fI<path|name|random|previous|next>\fP\f[R]
.PD 0
.P
.PD
Wallpaper to set:
.IP \[bu] 2
\f[B]\fI<path>\fP\f[R] - path to a picture
.IP \[bu] 2
\f[B]\fI<name>\fP\f[R] - name of wallpaper stored in \f[B]$GWCDIR/normal\f[R]
.IP \[bu] 2
\f[B]\fI<hex_color>\fP\f[R] - When the argument to this flag starts with a
\f[B]\fI<hex_color>\fP\f[R], \f[B]gwc\f[R] uses \f[B]hsetroot\f[R] to tile the
wallpaper \f[B]$GWCDIR/white\f[R] (by default), and tint it to the
specified \f[B]\fI<hex_color>\fP\f[R].
If the argument is eg.
\f[B]\fI<hex_color>\fP-paper\f[R], then \f[B]gwc\f[R] finds and uses
\f[B]$GWCDIR/white-paper\f[R] as the tiled image instead.
.IP \[bu] 2
\f[B]\fI<previous>\fP\f[R] - previous wallpaper in history
.IP \[bu] 2
\f[B]\fI<next>\fP\f[R] - next wallpaper in history
.IP \[bu] 2
\f[B]\fI<random>\fP\f[R] - Choose a random wallpaper in
\f[B]$GWCDIR/normal\f[R]
.PP
\f[B]--previous|-p\f[R]
.PD 0
.P
.PD
previous wallpaper in history
.PP
\f[B]--next|-n\f[R]
.PD 0
.P
.PD
next wallpaper in history
.PP
\f[B]--random|-r\f[R]
.PD 0
.P
.PD
Choose a random wallpaper in \f[B]$GWCDIR/normal\f[R]
.PP
\f[B]--tint|-t \fI<hex_color>\fP\f[R]
.PD 0
.P
.PD
Tint color of wallpaper, Hexadecimal color Eg.
#002b36
.PP
\f[B]--add|-a \fI<directory|path>\fP\f[R]
.PD 0
.P
.PD
Add walls from \f[B]\fI<directory>\fP\f[R], add the wallpaper in
\f[B]\fI<path>\fP\f[R], or if there\[cq]s no argument, check for pictures in
the working directory and add those to \f[B]$GWCDIR\f[R]
.PP
\f[B]--list|-l\f[R]
.PD 0
.P
.PD
View all wallpapers in the database
.PP
\f[B]--blur|-b\f[R]
.PD 0
.P
.PD
Toggle blur
.PP
\f[B]--rename|-r \[aq]\fI<oldname>\fP \fI<newname>\fP\[aq]\f[R]
.PD 0
.P
.PD
Rename \f[B]\fI<oldname>\fP\f[R] wallpaper to \f[B]\fI<newname>\fP\f[R].
If only there is only one argument, the current wallpaper is renamed to
that argument.
.PP
\f[B]--delete|-d \fI<name>\fP\f[R]
.PD 0
.P
.PD
Remove \f[B]\fI<name>\fP\f[R] wallpaper from \f[B]$GWCDIR/(normal|blur)\f[R]
If \f[B]\fI<name>\fP\f[R] is empty, the current wallpaper is removed.
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
