.TH GWMC 1 2019\-11\-04 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gawm\f[R] - manage custom \f[B]wmutils\f[R] scripts
.SH SYNOPSIS
.IP
.nf
\f[B]
gwmc \fI<commands to run>\fP
gwmc --help|-h
\f[R]
.fi
.SH DESCRIPTION
.PP
Basically runs one of the scripts in the default gwm directory.
For me, that\[cq]s \f[B]$HOME/scr/gwm\f[R].
