.TH I3BG 1 2019\-10\-22 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3bg\f[R] - A script to set wallpaper, with other features.
.SH SYNOPSIS
.IP
.nf
\f[B]
i3bg [--wallpaper|-w \fI<path|prev|next|random|name>\fP]
     [--tint|-t|--blur|-b]
i3bg [--add|-a \fI<directory>\fP]
i3bg [--list|-l]
i3bg [--rename|-r|--delete|-d \fI<name>\fP]
i3bg [--help|-h]
i3bg
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create default directories:
.PD 0
.P
.PD
+ $i3BGDIR/(normal|blur|cols) + Default i3bg folder: i3BGDIR =
$XDG_PICTURES_DIR/i3bg
.PP
\f[B]--wallpaper|-w \fI<path>\fP|prev|next|random|\fI<name>\fP\f[R]
.PD 0
.P
.PD
Wallpaper to set:
.PD 0
.P
.PD
+ \f[B]\fI<path>\fP\f[R] - path to a picture + \f[B]prev\f[R] - previous
wallpaper in history + \f[B]next\f[R] - next wallpaper in history +
\f[B]random\f[R] - random wallpaper in $i3BGDIR/normal +
\f[B]\fI<name>\fP\f[R] - name of wallpaper stored in $i3BGDIR/normal
.PP
\f[B]--tint|-t \fI<hex_color>\fP\f[R]
.PD 0
.P
.PD
Tint color of wallpaper, Hexadecimal color Eg.
#002b36
.PP
\f[B]--add|-a \fI<directory>\fP\f[R]
.PD 0
.P
.PD
Add walls from \f[B]\fI<directory>\fP\f[R]
.PP
\f[B]--list|-l\f[R]
.PD 0
.P
.PD
List available wallpapers
.PP
\f[B]--blur|-b\f[R]
.PD 0
.P
.PD
Toggle blur
.PP
\f[B]--rename|-r \fI<name>\fP\f[R]
.PD 0
.P
.PD
Rename current wallpaper to \f[B]\fI<name>\fP\f[R]
.PP
\f[B]--delete|-d \fI<name>\fP\f[R]
.PD 0
.P
.PD
Remove \f[B]\fI<name>\fP\f[R] wallpaper from $i3BGDIR/(normal|blur)
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
