.TH I3BG 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3bg\f[R] - A script to set wallpaper, with other features.
.SH SYNOPSIS
.IP
.nf
\f[C]
i3bg [--wallpaper|-w <path|prev|next|random|name>]
     [--tint|-t|--blur|-b]
i3bg [--add|-a <directory>]
i3bg [--list|-l]
i3bg [--rename|-r|--delete|-d <name>]
i3bg [--help|-h]
i3bg
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create default directories:
.PD 0
.P
.PD
+ $i3BGDIR/(normal|blur|cols) + Default i3bg folder: i3BGDIR =
$XDG_PICTURES_DIR/i3bg
.PP
\f[C]--wallpaper|-w <path>|prev|next|random|<name>\f[R]
.PD 0
.P
.PD
Wallpaper to set:
.PD 0
.P
.PD
+ \f[C]<path>\f[R] - path to a picture + \f[C]prev\f[R] - previous
wallpaper in history + \f[C]next\f[R] - next wallpaper in history +
\f[C]random\f[R] - random wallpaper in $i3BGDIR/normal +
\f[C]<name>\f[R] - name of wallpaper stored in $i3BGDIR/normal
.PP
\f[C]--tint|-t <hex_color>\f[R]
.PD 0
.P
.PD
Tint color of wallpaper, Hexadecimal color Eg.
#002b36
.PP
\f[C]--add|-a <directory>\f[R]
.PD 0
.P
.PD
Add walls from \f[C]<directory>\f[R]
.PP
\f[C]--list|-l\f[R]
.PD 0
.P
.PD
List available wallpapers
.PP
\f[C]--blur|-b\f[R]
.PD 0
.P
.PD
Toggle blur
.PP
\f[C]--rename|-r <name>\f[R]
.PD 0
.P
.PD
Rename current wallpaper to \f[C]<name>\f[R]
.PP
\f[C]--delete|-d <name>\f[R]
.PD 0
.P
.PD
Remove \f[C]<name>\f[R] wallpaper from $i3BGDIR/(normal|blur)
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
