.TH I3END 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3end\f[R] - shutdown menu for i3wm
.SH SYNOPSIS
.IP
.nf
\f[C]
i3end l|e|s|h|r|x
i3end --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
Run with no option to produce a rofi menu of options
.PP
\f[C]l\f[R]
.PD 0
.P
.PD
lock
.PP
\f[C]e\f[R]
.PD 0
.P
.PD
logout
.PP
\f[C]s\f[R]
.PD 0
.P
.PD
suspend
.PP
\f[C]h\f[R]
.PD 0
.P
.PD
hibernate
.PP
\f[C]r\f[R]
.PD 0
.P
.PD
reboot
.PP
\f[C]x\f[R]
.PD 0
.P
.PD
shutdown
