.TH I3MENU 1 2019\-12\-08 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3menu\f[R] - Rofi wrapper script
.SH SYNOPSIS
.IP
.nf
\f[B]
[STDIN |] i3menu [--prompt|-p|-error|-e|--message|-s \fI<text>\fP]
       [--boxlayout|-b \fI<p|e|l>\fP]
       [--run|-r|--drun|-d]
       [--theme|-t \fI<theme>\fP]
       [--color|-c \fI<color>\fP]
       [--orientation|-o|--normal-win|-n]
       [--window|-W|--titlebar|-T|--fullscreen|-f|--mouse|-m]
       [--width|-w|--height|-H|--xoffset|-x|--yoffset|-y \fI<integer>\fP]
       [--location|-L|--lines|-l|--padding|-D|--columns|-C \fI<integer>\fP]
i3menu --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--prompt|-p \fI<text>\fP\f[R]
.PD 0
.P
.PD
Prompt
.PP
\f[B]--message|-s \fI<text>\fP\f[R]
.PD 0
.P
.PD
Message to include, below prompt
.PP
\f[B]--error|-e \fI<text>\fP\f[R]
.PD 0
.P
.PD
Same as \f[B]--message\f[R] but turns menu red
.PP
\f[B]--run|-r\f[R]
.PD 0
.P
.PD
\f[B]rofi -show run\f[R] mode
.PP
\f[B]--drun|-d\f[R]
.PD 0
.P
.PD
\f[B]rofi -show drun\f[R] mode
.PP
\f[B]--color|-c \fI<color>\fP\f[R]
.PD 0
.P
.PD
Accent color.
The name of one of in the variable files in
\f[B]\[ti]/.config/rofi\f[R].
This will only work using the automatically created \f[B]_i3menu\f[R]
theme
.PP
\f[B]--theme|-t \fI<theme>\fP\f[R]
.PD 0
.P
.PD
Specify \f[B]\fI<theme>\fP\f[R] to use
.PP
\f[B]--titlebar|-T\f[R]
.PD 0
.P
.PD
Spawn on focussed window title-bar
.PD 0
.P
.PD
Requires \f[B]TITLEBAR_HEIGHT\f[R] in
\f[B]\[ti]/.config/rofi/.i3menuconfig\f[R]
.PP
\f[B]--mouse|-m\f[R]
.PD 0
.P
.PD
Spawn at mouse location
.PP
\f[B]--fullscreen|-F\f[R]
.PD 0
.P
.PD
Fullscreen mode
.PP
\f[B]--window|-W\f[R]
.PD 0
.P
.PD
Fill focussed window
.PP
\f[B]--normal-win|-n\f[R]
.PD 0
.P
.PD
Open menu as normal window
.PP
\f[B]--horizontal|-o\f[R]
.PD 0
.P
.PD
Make menu horizontal like \f[B]dmenu\f[R]
.PP
\f[B]--location|-L \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi location:
.IP
.nf
\f[B]
1|northwest 2|north  3|northeast
8|west      0|center 4|east
7|southwest 6|south  5|southeast
\f[R]
.fi
.PP
\f[B]--boxlayout|-b \fI<p|e|l>\fP\f[R]
.PD 0
.P
.PD
Elements of window to include: (p)rompt (e)ntry (l)istview
.PP
\f[B]--lines|-l \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Number of vertical rows
.PP
\f[B]--columns|-C \fI<integer>\fP\f[R]
.PD 0
.P
.PD
No.\ of columns
.PP
\f[B]--xoffset|-x \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Horizontal Offset
.PP
\f[B]--yoffset|-y \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Vertical Offset
.PP
\f[B]--width|-w \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi width
.PP
\f[B]--height|-H \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi height, integer less than 100
.PP
\f[B]--padding|-D \fI<text>\fP\f[R]
.PD 0
.P
.PD
Padding
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
