.TH I3MENU 1 2019\-10\-30 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3menu\f[R] - Rofi wrapper script
.SH SYNOPSIS
.IP
.nf
\f[B]
i3menu [--dmenu|-d|--apps|-s]
       [--window|-W|--titlebar|-t|--fullscreen|-f]
       [--width|-w|--height|-H|--xoffset|-x|--yoffset|-y \fI<integer>\fP]
       [--orientation|-o \fI<vertical|horizontal>\fP]
       [--location|-l|--lines|-L|--monitor|-m \fI<integer>\fP]
       [--color|-c \fI<color>\fP]
       [--prompt|-p \fI<text>\fP]
i3menu --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--prompt|-p \fI<text>\fP\f[R]
.PD 0
.P
.PD
Prompt
.PP
\f[B]--location|-l \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi location:
.IP
.nf
\f[B]
1 2 3
8 0 4
7 6 5
\f[R]
.fi
.PP
\f[B]--lines|-L \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Number of vertical rows
.PP
\f[B]--xoffset|-x \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Horizontal Offset
.PP
\f[B]--yoffset|-y \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Vertical Offset
.PP
\f[B]--color|-c \fI<color>\fP\f[R]
.PD 0
.P
.PD
Accent color.
The name of one of in the variable files in .config/rofi
.PP
\f[B]--width|-w \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi width
.PP
\f[B]--height|-H \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi height, integer less than 100
.PP
\f[B]--orientation|-o [vertical|horizontal]\f[R]
.PD 0
.P
.PD
Vertical or horizontal (like dmenu)
.PP
\f[B]--window|-W\f[R]
.PD 0
.P
.PD
Fill active window
.PP
\f[B]--dmenu|-d\f[R]
.PD 0
.P
.PD
Dmenu mode
.PP
\f[B]--apps|-s\f[R]
.PD 0
.P
.PD
Application menu mode
.PP
\f[B]--titlebar|-t\f[R]
.PD 0
.P
.PD
Spawn on i3wm title-bar
.PP
\f[B]--monitor|-m\f[R]
.PD 0
.P
.PD
Spawn at mouse location
.PP
\f[B]--fullscreen|-f\f[R]
.PD 0
.P
.PD
Fullscreen mode (in progress)
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
