.TH I3MENU 1 2019\-12\-06 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3menu\f[R] - Rofi wrapper script
.SH SYNOPSIS
.IP
.nf
\f[B]
[STDIN |] i3menu [--prompt|-p \fI<text>\fP]
       [--run|-r|--drun|-d]
       [--color|-c \fI<color>\fP]
       [--window|-W|--titlebar|-T|--fullscreen|-f|--mouse|-m]
       [--orientation|-o \fI<vertical|horizontal>\fP]
       [--width|-w|--height|-H|--xoffset|-x|--yoffset|-y \fI<integer>\fP]
       [--location|-L|--lines|-l|--padding|-P \fI<integer>\fP]
i3menu --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--prompt|-p \fI<text>\fP\f[R]
.PD 0
.P
.PD
Prompt
.PP
\f[B]--orientation|-o [vertical|horizontal]\f[R]
.PD 0
.P
.PD
Vertical or horizontal (like dmenu)
.PP
\f[B]--run|-r\f[R]
.PD 0
.P
.PD
\f[B]rofi -show run\f[R] mode
.PP
\f[B]--drun|-d\f[R]
.PD 0
.P
.PD
\f[B]rofi -show drun\f[R] mode
.PP
\f[B]--titlebar|-T\f[R]
.PD 0
.P
.PD
Spawn on focussed window title-bar
.PD 0
.P
.PD
Requires \f[B]TITLEBAR_HEIGHT\f[R] in
\f[B]\[ti]/.config/rofi/.i3menuconfig\f[R]
.PP
\f[B]--mouse|-m\f[R]
.PD 0
.P
.PD
Spawn at mouse location
.PP
\f[B]--fullscreen|-f\f[R]
.PD 0
.P
.PD
Fullscreen mode (in progress)
.PP
\f[B]--window|-W\f[R]
.PD 0
.P
.PD
Fill focussed window
.PP
\f[B]--color|-c \fI<color>\fP\f[R]
.PD 0
.P
.PD
Accent color.
The name of one of in the variable files in .config/rofi
.PP
\f[B]--location|-L \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi location:
.IP
.nf
\f[B]
1 2 3
8 0 4
7 6 5
\f[R]
.fi
.PP
\f[B]--lines|-l \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Number of vertical rows
.PP
\f[B]--xoffset|-x \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Horizontal Offset
.PP
\f[B]--yoffset|-y \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Vertical Offset
.PP
\f[B]--width|-w \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi width
.PP
\f[B]--height|-H \fI<integer>\fP\f[R]
.PD 0
.P
.PD
Rofi height, integer less than 100
.PP
\f[B]--padding|-P \fI<text>\fP\f[R]
.PD 0
.P
.PD
Padding
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
