.TH I3QUAD 1 2019\-10\-22 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3quad\f[R] - my i3 layout launcher, inspired by budlabs\[cq]
\f[B]i3fyra\f[R]
.SH SYNOPSIS
.IP
.nf
\f[B]
i3quad [--fullscreen|-F|--focus|-f|--move|-m] \fI<con>\fP
i3quad --tile|-t
i3quad --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--move|-m \fI<con>\fP\f[R]
.PD 0
.P
.PD
Move window to mark \f[B]_W\fI<con>\fP\f[R]
.PP
\f[B]--focus|-f \fI<con>\fP\f[R]
.PD 0
.P
.PD
Move window to mark \f[B]_W\fI<con>\fP\f[R]
.PP
\f[B]--fullscreen|-F \fI<con>\fP\f[R]
.PD 0
.P
.PD
Toggle mark \f[B]_W\fI<con>\fP\f[R] fullscreen
.PP
\f[B]--tile|-t\f[R]
.PD 0
.P
.PD
Tile currently focussed window
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH THE LAYOUT
.IP
.nf
\f[B]
            \[u250C]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u252C]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2510]
            \[br]  _W4   \[br] _W1 \[br]\[u2592]
            \[u251C]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u253C]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2524]\[u2592]
            \[br]  _W3   \[br] _W2 \[br]\[u2592]
            \[br]        \[br]     \[br]\[u2592]
            \[u2514]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2534]\[u2508]\[u2508]\[u2508]\[u2508]\[u2508]\[u2518]\[u2592]
              \[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]\[u2592]
\f[R]
.fi
.SH IN PROGRESS
.PP
\f[B]--focus-last|-l\f[R]
.PD 0
.P
.PD
Focus last focussed window moving launched window to
