.TH LCH 1 2020\-01\-03 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]i3lch\f[R] - launch a program in i3 but with added perks
.SH SYNOPSIS
.IP
.nf
\f[B]
i3lch [--class|-c|--instance|-i|--name|-n \fI<class|instance|name>\fP]
      [--exec|-e \fI<command>\fP]
      [--toggle|-t]
i3lch --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--class|-c \fI<class>\fP\f[R]
.PD 0
.P
.PD
Focus window with class \f[B]\fI<class>\fP\f[R]
.PP
\f[B]--instance|-i \fI<instance>\fP\f[R]
.PD 0
.P
.PD
Focus window with instance \f[B]\fI<instance>\fP\f[R]
.PP
\f[B]--name|-n \fI<name>\fP\f[R]
.PD 0
.P
.PD
Focus window with name \f[B]\fI<name>\fP\f[R]
.PP
\f[B]--exec|-e \fI<command>\fP\f[R]
.PD 0
.P
.PD
Command to run if \f[B]\fI<class|instance|name>\fP\f[R] not found
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH IN PROGRESS
.PP
\f[B]--toggle|-t\f[R]
.PD 0
.P
.PD
+ send to scratchpad if on current workspace.
+ bring to current workspace if not on current workspace and hidden.
+ bring to current workspace if on current scratchpad.
