.TH MANNER 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]manner\f[R] - generates man pages for scripts
.SH SYNOPSIS
.IP
.nf
\f[C]
manner [--directory|-d <directory>] [--install|-i copy|link]
manner --script|-s <script>
manner --help|-h
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[C]
pandoc
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--directory|-d <directory>\f[R]
.PD 0
.P
.PD
Change target directory
\f[C]--script|-s <script>\f[R]
.PD 0
.P
.PD
Call specified
.PP
with \f[C]--help\f[R] flag, and convert the output to a man page with
\f[C]pandoc -s -t man\f[R].
.PP
\f[C]--install|-i copy|link\f[R]
.PD 0
.P
.PD
Install all the manpages in man to \f[C]/usr/share/man/man1\f[R] if they
do not already exist.
.PP
Argument to this option determines whether the scripts are copied or
linked.
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH DESCRIPTION
.PP
All my bash scripts that have a help function are just called with the
\f[C]--help\f[R] flag and the output piped to
\f[C]pandoc -s -t man\f[R], and that output redirected to the directory
\f[C]<directory>\f[R]man.
The default directory is \f[C]$HOME/scr\f[R], so the resulting manpages
will be redirected to the appropriate file in \f[C]$HOME/scrman\f[R].
.PP
Note that this only works because all my help functions are written in
markdown.
.PP
The \f[C]--script\f[R] flag can be used to automatically pipe the output
of the specified script to a man page.
