.TH MKSCR 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]mkscr\f[R] - make bash script
.SH SYNOPSIS
.IP
.nf
\f[C]
mkscr [--subdirectory|-s <directory>]
      [--template|-t <file>]
      [--generate-help|-g]
      <name>
mkscr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
Last argument is always the \f[C]<name>\f[R] of the new script
.PP
\f[C]--subdirectory|-s <directory>\f[R]
.PD 0
.P
.PD
Create script in subdirectory \f[C]<directory>\f[R]
.PP
\f[C]--generate-help|-g\f[R]
.PD 0
.P
.PD
Generate help function
.PP
\f[C]--template|-t <file>\f[R]
.PD 0
.P
.PD
Use \f[C]<file>\f[R] as template
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
