.TH MKSCR 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]mkscr\f[R] - make bash script
.SH SYNOPSIS
.IP
.nf
\f[B]
mkscr [--subdirectory|-s \fIdirectory\fP]
      [--template|-t \fIfile\fP]
      [--generate-help|-g]
      \fIname\fP
mkscr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
Last argument is always the \f[B]\fIname\fP\f[R] of the new script
.PP
\f[B]--subdirectory|-s \fIdirectory\fP\f[R]
.PD 0
.P
.PD
Create script in subdirectory \f[B]\fIdirectory\fP\f[R]
.PP
\f[B]--generate-help|-g\f[R]
.PD 0
.P
.PD
Generate help function
.PP
\f[B]--template|-t \fIfile\fP\f[R]
.PD 0
.P
.PD
Use \f[B]\fIfile\fP\f[R] as template
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
