.TH NOTER 1 2019\-10\-31 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]noter\f[R] - create notes, with different entries, stored in
$XDG_DESKTOP_DIR, usually $HOME/Desktop
.SH SYNOPSIS
.IP
.nf
\f[B]
noter [--type|-t \fI<note_type>\fP] [--entry|-e \fI<entry>\fP]
noter --list|-l|--delete-type|-D \fI<note_type>\fP
noter --delete|-d \fI<entry>\fP
noter --list-types|-L
noter --help|-h
noter
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create defaults:
.PD 0
.P
.PD
\f[B]NOTE_DIR\f[R] = \f[B]$HOME/Desktop\f[R]
.PD 0
.P
.PD
\f[B]NOTE_TYPE\f[R] = \f[B]OTHER|NOTES|WATCHLIST|TODO\f[R]
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.PP
\f[B]--type|-t \fI<note_type>\fP\f[R]
.PD 0
.P
.PD
Create $NOTE_DIR/\f[B]\fI<note_type>\fP\f[R]
.PP
\f[B]--entry|-e \fI<entry>\fP\f[R]
.PD 0
.P
.PD
\f[B]\fI<entry>\fP\f[R] to add to the note
.PP
\f[B]--delete|-d \fI<entry>\fP\f[R]
.PD 0
.P
.PD
Delete line containing \f[B]\fI<entry>\fP\f[R] in note file
.PP
\f[B]--delete-type|-D \fI<note_type>\fP\f[R]
.PD 0
.P
.PD
Delete $NOTE_DIR/\f[B]\fI<note_type>\fP\f[R]
.PP
\f[B]--list|-l\f[R]
.PD 0
.P
.PD
Print contents of $NOTE_DIR/\f[B]\fI<note_type>\fP\f[R]
.PP
\f[B]--list-types|-L \fI<note_type>\fP\f[R]
.PD 0
.P
.PD
\f[B]ls\f[R] $NOTE_DIR
