.TH NOTER 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]noter\f[R] - create notes, with different entries, stored in
$XDG_DESKTOP_DIR, usually $HOME/Desktop
.SH SYNOPSIS
.IP
.nf
\f[C]
noter [--type|-t <note_type>] [--entry|-e <entry>]
noter --list|-l|--delete-type|-D <note_type>
noter --delete|-d <entry>
noter --list-types|-L
noter --help|-h
noter
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create defaults:
.PD 0
.P
.PD
\f[C]NOTE_DIR\f[R] = \f[C]$HOME/Desktop\f[R]
.PD 0
.P
.PD
\f[C]NOTE_TYPE\f[R] = \f[C]OTHER|NOTES|WATCHLIST|TODO\f[R]
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.PP
\f[C]--type|-t <note_type>\f[R]
.PD 0
.P
.PD
Create $NOTE_DIR/\f[C]<note_type>\f[R]
.PP
\f[C]--entry|-e <entry>\f[R]
.PD 0
.P
.PD
\f[C]<entry>\f[R] to add to the note
.PP
\f[C]--delete|-d <entry>\f[R]
.PD 0
.P
.PD
Delete line containing \f[C]<entry>\f[R] in note file
.PP
\f[C]--delete-type|-D <note_type>\f[R]
.PD 0
.P
.PD
Delete $NOTE_DIR/\f[C]<note_type>\f[R]
.PP
\f[C]--list|-l\f[R]
.PD 0
.P
.PD
Print contents of $NOTE_DIR/\f[C]<note_type>\f[R]
.PP
\f[C]--list-types|-L <note_type>\f[R]
.PD 0
.P
.PD
\f[C]ls\f[R] $NOTE_DIR
