.TH PBCAT 1 2019\-10\-21 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]pbcat\f[R] - script to create lots of polybar ipc modules
.SH SYNOPSIS
.IP
.nf
\f[C]
pbcat [--foreground|-f <hex>]
      [--background|-b <hex>]
      [--invert|-i]
      --module|-m <module>
      <text>
pbcat --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
Final argument is \f[B]<text>\f[R] to print to \f[B]<module>\f[R].
All modules are stored in \f[B]$HOME/.config/pbcat\f[R].
.PP
\f[B]--module|-m <module>\f[R]
.PD 0
.P
.PD
\f[B]<module>\f[R] to update
.PP
\f[B]--foreground|-f <hex>\f[R]
.PD 0
.P
.PD
Foreground colour
.PP
\f[B]--background|-b <hex>\f[R]
.PD 0
.P
.PD
Background colour
.PP
\f[B]--invert|-i\f[R]
.PD 0
.P
.PD
Invert foreground and background colours
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
