.TH PBCAT 1 2019\-10\-24 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]pbcat\f[R] - script to create lots of polybar ipc modules
.SH SYNOPSIS
.IP
.nf
\f[B]
pbcat [--foreground|-f \fI<hex>\fP]
      [--background|-b \fI<hex>\fP]
      [--invert|-i]
      --module|-m \fI<module>\fP
      \fI<text>\fP
pbcat --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
Final argument is \f[B]\fI<text>\fP\f[R] to print to \f[B]\fI<module>\fP\f[R].
All modules are stored in \f[B]$HOME/.config/pbcat\f[R].
.PP
\f[B]--module|-m \fI<module>\fP\f[R]
.PD 0
.P
.PD
\f[B]\fI<module>\fP\f[R] to update
.PP
\f[B]--foreground|-f \fI<hex>\fP\f[R]
.PD 0
.P
.PD
Foreground colour
.PP
\f[B]--background|-b \fI<hex>\fP\f[R]
.PD 0
.P
.PD
Background colour
.PP
\f[B]--invert|-i\f[R]
.PD 0
.P
.PD
Invert foreground and background colours
.PP
\f[B]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
