.TH ROFIND 1 2019\-12\-08 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]rofind\f[R] - \f[B]find\f[R] wrapper with \f[B]rofi\f[R]
.SH DEPENDENCIES
.IP
.nf
\f[B]
rofi
i3menu
\f[R]
.fi
.SH SYNOPSIS
.IP
.nf
\f[B]
rofind
rofind --help|-h
\f[R]
.fi
.SH DESCRIPTION
.PP
Just a \f[B]rofi\f[R] wrapper for \f[B]find\f[R], and opens the chosen
item using an appropriate application.
