.TH WEBGEN 1 2020\-09\-19 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]webgen\f[R] - manage a static website, using \f[B]pandoc\f[R] +
\f[B]markdown\f[R]
.SH DEPENDENCIES
.IP
.nf
\f[B]
pandoc
\f[R]
.fi
.SH SYNOPSIS
.IP
.nf
\f[B]
webgen --gensite|-g|--pushsite|-s
webgen --newpage|-n|--newpost|-p \fI<name>\fP
webgen --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[B]--gensite|-g\f[R]
.PD 0
.P
.PD
Generates website in \f[B]local/\f[R] folder.
.PD 0
.P
.PD
The links will still be local so you can still view your changes
locally.
.PP
\f[B]--pushsite|-s\f[R]
.PD 0
.P
.PD
Runs \f[B].webgen\f[R] script to upload the site to wherever you want.
Put anything you want in the script
.PP
\f[B]--newpage|-n \fI<name>\fP\f[R]
.PD 0
.P
.PD
Create a new page
.PP
\f[B]--newpost|-p \fI<name>\fP\f[R]
.PD 0
.P
.PD
Create a new blog post
.PP
\f[B]--help\f[R]
.PD 0
.P
.PD
Displays this help
