.TH XBMER 1 2019\-12\-06 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]xbmer\f[R] - \f[B]xsetroot\f[R] front-end for setting bitmap
pattern wallpapers.
.SH SYNOPSIS
.IP
.nf
\f[B]
xbmer [--pattern|-p \fI<pattern>\fP.xbm]
      [--bg|-b \fI<backgroundhex>\fP]
      [--fg|-f \fI<foregroundhex>\fP]
xber --help|-h
\f[R]
.fi
.SH DESCRIPTION
.PP
Obviously depends on \f[B]xsetroot\f[R], and can\[cq]t be used with
\f[B]compton\f[R], until \f[B]hsetroot\f[R] can use \f[B].xbm\f[R]
files!
.PD 0
.P
.PD
\f[B].xbm\f[R] files stored in \f[B]\[ti]/Pictures/xbm\f[R] by default.
