#!/bin/bash

blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

dir=$HOME/.themes/MINE/gtk-2.0/

cd $dir

echo -e "style \"notify-window\" {" > xfce-notify.rc
echo -e "  XfceNotifyWindow::summary-bold = 1" >> xfce-notify.rc
echo -e "  XfceNotifyWindow::border-color = \"$blackd\"" >> xfce-notify.rc
echo -e "  XfceNotifyWindow::border-color-hover = \"$blackd\"" >> xfce-notify.rc
echo -e "  XfceNotifyWindow::border-radius = 3.0" >> xfce-notify.rc
echo -e "  XfceNotifyWindow::border-width = 1.0" >> xfce-notify.rc
echo -e "  XfceNotifyWindow::border-width-hover = 1.0" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  bg[NORMAL] = \"#292C36\"" >> xfce-notify.rc
echo -e "}" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "style \"notify-button\" {" >> xfce-notify.rc
echo -e "  bg[NORMAL] = \"$blackl\"" >> xfce-notify.rc
echo -e "  bg[PRELIGHT] = \"$blackl\"" >> xfce-notify.rc
echo -e "  bg[ACTIVE] = \"$blue\"" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  fg[NORMAL] = \"$whitel\"" >> xfce-notify.rc
echo -e "  fg[PRELIGHT] = \"$whitel\"" >> xfce-notify.rc
echo -e "  fg[ACTIVE] = \"$whited\"" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  engine \"murrine\" {" >> xfce-notify.rc
echo -e "    gradient_shades = { 1.0, 1.0, 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    border_shades = { 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    roundness = 2" >> xfce-notify.rc
echo -e "    textstyle = 0" >> xfce-notify.rc
echo -e "  }" >> xfce-notify.rc
echo -e "}" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "style \"notify-text\" {" >> xfce-notify.rc
echo -e "  GtkWidget::link-color = \"$blue\"" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  fg[NORMAL] = \"$whitel\"" >> xfce-notify.rc
echo -e "  fg[PRELIGHT] = \"$whitel\"" >> xfce-notify.rc
echo -e "  fg[ACTIVE] = \"$whitel\"" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  engine \"murrine\" {" >> xfce-notify.rc
echo -e "    textstyle = 0" >> xfce-notify.rc
echo -e "  }" >> xfce-notify.rc
echo -e "}" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "style \"notify-summary\" {" >> xfce-notify.rc
echo -e "    font_name = \"Bold\"" >> xfce-notify.rc
echo -e "}" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "style \"notify-progressbar\" {" >> xfce-notify.rc
echo -e "  GtkProgressBar::min-horizontal-bar-height = 4" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  xthickness   = 0" >> xfce-notify.rc
echo -e "  ythickness   = 0" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  fg[PRELIGHT] = \"$blackd\"" >> xfce-notify.rc
echo -e "  bg[NORMAL]   = \"$blue\"" >> xfce-notify.rc
echo -e "  bg[ACTIVE] = \"$blackd\"" >> xfce-notify.rc
echo -e "  bg[SELECTED] = \"$blue\"" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "  engine \"murrine\" {" >> xfce-notify.rc
echo -e "    gradient_shades = { 1.0, 1.0, 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    border_shades = { 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    trough_shades = { 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    trough_border_shades = { 1.0, 1.0 }" >> xfce-notify.rc
echo -e "    progressbarstyle = 0" >> xfce-notify.rc
echo -e "    roundness = 2" >> xfce-notify.rc
echo -e "    textstyle = 0" >> xfce-notify.rc
echo -e "  }" >> xfce-notify.rc
echo -e "}" >> xfce-notify.rc
echo -e "" >> xfce-notify.rc
echo -e "class \"XfceNotifyWindow\" style \"notify-window\"" >> xfce-notify.rc
echo -e "widget \"XfceNotifyWindow.*.summary\" style \"notify-summary\"" >> xfce-notify.rc
echo -e "widget_class \"XfceNotifyWindow.*<GtkButton>\" style \"notify-button\"" >> xfce-notify.rc
echo -e "widget_class \"XfceNotifyWindow.*.<GtkLabel>\" style \"notify-text\"" >> xfce-notify.rc
echo -e "widget_class \"XfceNotifyWindow.*.<GtkProgress>\" style \"notify-progressbar\"" >> xfce-notify.rc
echo -e "widget_class \"XfceNotifyWindow.*.<GtkProgressBar>\" style \"notify-progressbar\"" >> xfce-notify.rc
