#!/bin/bash

title=`exec mpris-ctl info "%track_name"`
artist=`exec mpris-ctl info "%artist_name"`
length="/ `exec mpris-ctl info "%track_length"`"

if [ "$(playerctl status)" = "Playing" ]; then
  echo "// Playing : $title - $artist"
else
  echo "// Paused  : $title - $artist "
fi

