#!/usr/bin/env bash

_I="%{T1}%{T-}"
CPU=$(mpstat -P ALL | \
	awk '$2 ~ /^[0-9]+$/ {sys+=$5;c+=1} END {t=(sys / c);print t}')

FSTR="$_I ${CPU%.*}"
[[ ${CPU%.*} -ge 50 ]] && REV="%{R}"
echo "$REV$FSTR"
