#!/usr/bin/env bash

PLYR=$(mpris-ctl info "%player_name")
TRCK=$(mpris-ctl info "%track_name")
RTST=$(mpris-ctl info "%artist_name")
STTS=$(mpris-ctl info "%play_status")

_TRCK=$(expr ${#TRCK} - 19)
_RTST=$(expr ${#RTST} - 19)

[[ $PLYR == "Chrome"    ]] && PLYR="%{T1}%{T-}"
[[ $PLYR == "Spotify"   ]] && PLYR="%{T1}%{T-}"
[[ $PLYR == "Rhythmbox" ]] && PLYR="%{T1}%{T-}"

[[ ${#TRCK} -ge 20 ]] && TRCK="${TRCK:0:-$_TRCK}…"
[[ ${#RTST} -ge 20 ]] && RTST="${RTST:0:-$_RTST}…"

CURR="$RTST > $TRCK"
[[ $PLYR == "%player_name" ]] || [[ -z $PLYR ]] && CURR="" && PLYR="OFF"
echo "$PLYR ${CURR}"
