#!/usr/bin/env bash
MPVT="$(xdotool getwindowname $(xdotool search --class mpv))"
MPVL=$(expr ${#MPVT} - 38)
MPVT=${MPVT%.*}
_I="%{T1}%{T-}"
[[ ${#MPVT} -ge 35 ]] && MPVT=${MPVT:0:-${MPVL}} && MPVT="${MPVT}..."
echo "$_I ${MPVT}"
