#!/bin/bash

# OA: Gavin Vales
# CREATED: Fri  3 May 15:34:40 GMT 2019

_TIT=$(xdotool getactivewindow getwindowname)
_CUT=$(expr ${#_TIT} - 29)
TIT="${_TIT}"
[[ ${#_TIT} -gt 30 ]] && TIT="${_TIT:0:-${_CUT}}…"
echo $TIT
