#!/bin/bash

# OA: Gavin Vales
# CREATED: Tue 11 Jun 14:48:08 BST 2019

cat $HOME/xrs/theme > $HOME/.Xresources
cat $HOME/xrs/1vars >> $HOME/.Xresources
cat $HOME/xrs/2colorvars >> $HOME/.Xresources
cat $HOME/xrs/3rofi >> $HOME/.Xresources
cat $HOME/xrs/4xft >> $HOME/.Xresources
cat $HOME/xrs/5xterm >> $HOME/.Xresources
cat $HOME/xrs/6xcursor >> $HOME/.Xresources
cat $HOME/xrs/7urxvt >> $HOME/.Xresources
cat $HOME/xrs/8urxvtext >> $HOME/.Xresources
xrdb -load $HOME/.Xresources
kill -1 $(pidof urxvtd)
