#!/bin/bash

# OA: Gavin Vales
# CREATED: Tue 11 Jun 14:48:08 BST 2019

XDIR=$HOME/xrs
XRS=$HOME/.Xresources
cat $XDIR/.Xresources > $XRS
xrdb -load $XRS
kill -1 $(pidof urxvtd)

#check=$(cat $XDIR/0theme.Xresources | grep '#')
#
#if [[ -n $check ]]; then
#	cat $XDIR/0theme.Xresources > $XRS
#else
#	cat > $XRS << 'EOB'
#! emacs
##define cwhtd #382f4a
##define cwhtl #262626
##define credd #b14b1d
##define credl #b14b1d
##define cgrnd #699961
##define cgrnl #699961
##define cylwd #b1951d
##define cylwl #b1951d
##define cblud #5d4d7a
##define cblul #5d4d7a
##define cgntd #0059b2
##define cgntl #0059b2
##define ccynd #619991
##define ccynl #619991
##define cblkd #d4d4d4
##define cblkl #c0c0c0
#EOB
#fi
#cat $XDIR/1vars.Xresources      >> $XRS
#cat $XDIR/2colorvars.Xresources >> $XRS
#cat $XDIR/3rofi.Xresources      >> $XRS
#cat $XDIR/4xft.Xresources       >> $XRS
#cat $XDIR/5xterm.Xresources     >> $XRS
#cat $XDIR/6xcursor.Xresources   >> $XRS
#cat $XDIR/7urxvt.Xresources     >> $XRS
#cat $XDIR/8urxvtext.Xresources  >> $XRS
