#!/usr/bin/env bash

bkd="\033[1;30m"
bkl="\033[1;30m"
red="\033[1;31m"
grn="\033[1;32m"
ylw="\033[1;33m"
blu="\033[1;34m"
gnt="\033[1;35m"
cyn="\033[1;36m"
wtd="\033[1;37m"
nrm="\033[0m"

fnt="-f 3-d"

help () {
	echo -e "${blu}$(figlet $fnt " banner"| \
		sed $'s/\*/\u2588/g;s/\//\u2592/g')${nrm}"
cat << 'EOB'
 	-- Simple figlet wrapper
 
 Usage
 -----
 banner --help|-h   ┼ print this help
 banner --centre|-c ┼ centre
EOB
exit
}

while true; do
	case $1 in
		--centre | -c ) fnt+=" -c" ;;
		--help   | -h ) help       ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -n ${@:-} ]] && echo -e "${blu}$(echo -e " ${@:-}" | figlet ${fnt} | \
	sed $'s/\*/\u2588/g;s/\//\u2592/g')"

# >>>> unused
#	banner -s ┼ slant
#	banner -b ┼ banner3
#	banner -i ┼ larry3d
#	banner -l ┼ letters
#	banner -r ┼ roman
#	banner -m ┼ smisome1
#	banner -t ┼ trek
#	banner -f ┼ speed
#	banner -k ┼ smkeyboard
#		s) fnt="${fnt/3-d/slant}"                                                 ;;
#		b) fnt="${fnt/3-d/banner3}" regex=" | sed $'s/\#/\u2588/g'"               ;;
#		i) fnt="${fnt/3-d/larry3d}"                                               ;;
#		l) fnt="${fnt/3-d/letters}"                                               ;;
#		r) fnt="${fnt/3-d/roman}"   regex=" | sed $'s/\#/\u2588/g'"               ;;
#		m) fnt="${fnt/3-d/smisome1}"                                              ;;
#		t) fnt="${fnt/3-d/trek}"                                                  ;;
#		f) fnt="${fnt/3-d/speed}"                                                 ;;
#		k) fnt="${fnt/3-d/smkeyboard}"                                            ;;
#		d) fnt="${fnt}"             regex=" | sed $'s/\*/\u2588/g;s/\//\u2592/g'" ;;
