#!/usr/bin/env bash

fnt="-f 3-d"

help () {
cat << 'EOB'
```
 ██                                                
▒██                                                
▒██       ██████   ███████  ███████   █████  ██████
▒██████  ▒▒▒▒▒▒██ ▒▒██▒▒▒██▒▒██▒▒▒██ ██▒▒▒██▒▒██▒▒█
▒██▒▒▒██  ███████  ▒██  ▒██ ▒██  ▒██▒███████ ▒██ ▒ 
▒██  ▒██ ██▒▒▒▒██  ▒██  ▒██ ▒██  ▒██▒██▒▒▒▒  ▒██   
▒██████ ▒▒████████ ███  ▒██ ███  ▒██▒▒██████▒███   
▒▒▒▒▒    ▒▒▒▒▒▒▒▒ ▒▒▒   ▒▒ ▒▒▒   ▒▒  ▒▒▒▒▒▒ ▒▒▒    
```
- Simple figlet wrapper

## Usage

```
banner [--centre|-c] <text>
banner --help|-h
```

## Usage

+ `--centre|-c <text>`
	+ centre

+ `--help|-h`
	+ print this help

## In progress

+ `--slant|-s`
	+ slant

+ `--banner3|-b`
	+ banner3

+ `--larry3d|-i`
	+ larry3d

+ `--letters|-l`
	+ letters

+ `--roman|-r`
	+ roman

+ `--smisome1|-m`
	+ smisome1

+ `--trek|-t`
	+ trek

+ `--speed|-f`
	+ speed

+ `--smkeyboard|-k`
	+ smkeyboard

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--centre | -c ) fnt+=" -c" ;;
		--help   | -h ) help       ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -n ${@:-} ]] && echo -e "$(echo -e " ${@:-}" | figlet ${fnt} | \
	sed $'s/\*/\u2588/g;s/\//\u2592/g')"

# >>>> unused
#	banner -s ┼ slant
#	banner -b ┼ banner3
#	banner -i ┼ larry3d
#	banner -l ┼ letters
#	banner -r ┼ roman
#	banner -m ┼ smisome1
#	banner -t ┼ trek
#	banner -f ┼ speed
#	banner -k ┼ smkeyboard
#		s) fnt="${fnt/3-d/slant}"                                                 ;;
#		b) fnt="${fnt/3-d/banner3}" regex=" | sed $'s/\#/\u2588/g'"               ;;
#		i) fnt="${fnt/3-d/larry3d}"                                               ;;
#		l) fnt="${fnt/3-d/letters}"                                               ;;
#		r) fnt="${fnt/3-d/roman}"   regex=" | sed $'s/\#/\u2588/g'"               ;;
#		m) fnt="${fnt/3-d/smisome1}"                                              ;;
#		t) fnt="${fnt/3-d/trek}"                                                  ;;
#		f) fnt="${fnt/3-d/speed}"                                                 ;;
#		k) fnt="${fnt/3-d/smkeyboard}"                                            ;;
#		d) fnt="${fnt}"             regex=" | sed $'s/\*/\u2588/g;s/\//\u2592/g'" ;;
