#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Thu 27 Dec 15:32:13 GMT 2018

bib=$1
refer="$(cat "$bib" | grep -v '^@' | \
	sed "s/^[ \t]*//;s/\ =\ / /g;s/^author/\%A/g;s/^booktitle/\%B/g" | \
	sed "s/^title/\%T/g;s/^year/\%D/g;s/^journal/\%J/g;s/^book/\%B/g" | \
	sed "s/^volume/\%V/g;s/^school/%I/g;s/^institution/%I/g" | \
	sed "s/^publisher/\%I/g;s/^pages/\%P/g;s/^number/\%N/g" | \
	sed "s/^organization/\%Q/g;s/^url/\%O/g;s/},//g;s/{//g;s/}//g" | \
	sed "s/\\\&/\&/g;s/[\]\"//g;s/[$]//g;s/[\]//g" | \
	sed "/^%A\ */s/\ and\ /\n%A\ /g;s/$//")"
echo "${refer}" > ${bib:0:-4}
