#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Thu 27 Dec 15:32:13 GMT 2018

main () {

bib=$1
cat "$bib" | sed "/^@/d;s/^[ \t]*//;s/\ =\ / /g;
s/^author/\%A/g;
s/^booktitle/\%B/g;
s/^title/\%T/g;
s/^year/\%D/g;
s/^journal/\%J/g;
s/^book/\%B/g;
s/^volume/\%V/g;
s/^school/%I/g;
s/^institution/%I/g;
s/^publisher/\%I/g;
s/^pages/\%P/g;
s/^number/\%N/g;
s/^organization/\%Q/g;
s/^url/\%O/g;
s/},//g;s/{//g;s/}//g;
s/\\\&/\&/g;s/[\]\"//g;s/[$]//g;s/[\]//g;
/^%A\ */s/\ and\ /\n%A\ /g;s/$//" > ${bib%.*}
}

help () {
cat << 'EOB'
# NAME

__bibtorefer__ - convert a `.bib` file to `refer` syntax

# SYNOPSIS
```
bibtorefer <file>.bib
bibtorefer --help|-h
```
EOB
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z $1 ]] && help || main "$1"
