#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Thu  4 Jul 00:27:45 BST 2019

EDITOR="gvim -f"
NEWNME="$USER_TMP_DIR/.bulkrenamenew"
OLDNME="$USER_TMP_DIR/.bulkrenameold"
FINCMD="$USER_TMP_DIR/.finalcommands"
MENOPS="-a lightblu -l 15 -L mc -w 1000"
FILES="${1}"
echo "$FILES" > $OLDNME
sed -e "s/^'//g;s/'$//g;s/'\ '/\n/g" -i $OLDNME
sed -e "s/\`/\\\`/g;s/\\\''//g" -i $OLDNME
cat $OLDNME > $NEWNME
$EDITOR $NEWNME
sed -e "s/$/\"/g;s/^/\"/g" -i $NEWNME
sed -e "s/$/\"/g;s/^/mv\ \"/g" -i $OLDNME
paste $OLDNME $NEWNME > $FINCMD
confirm () {
	cat $FINCMD | dmrap $MENOPS -p 'Correct?'
	confirm=$(echo -e "Yes\nNo" | dmrap $MENOPS -p 'RENAME?')
	[[ $confirm == "Yes" ]] && source $FINCMD
}
confirm
rm $NEWNME
rm $OLDNME
rm $FINCMD
