#!/bin/bash

# OA: Gavin Vales
# CREATED: Thu  4 Jul 00:27:45 BST 2019

EDITOR="gvim -f"
NEWNME="$HOME/.bulkrenamenew"
OLDNME="$HOME/.bulkrenameold"
FINCMD="$HOME/.finalcommands"
FILES="${1}"
echo "$FILES" > $OLDNME
sed -e "s/^'//g;s/'$//g;s/'\ '/\n/g" -i $OLDNME
sed -e "s/\`/\\\`/g;s/\\\''//g" -i $OLDNME
cat $OLDNME > $NEWNME
$EDITOR $NEWNME
sed -e "s/$/\"/g;s/^/\"/g" -i $NEWNME
sed -e "s/$/\"/g;s/^/mv\ \"/g" -i $OLDNME
paste $OLDNME $NEWNME > $FINCMD
confirm () {
	cat $FINCMD | $HOME/scr/i3menu -t -c white -o vertical \
		-r $(cat $FINCMD | wc -l) \
		-p "FINALCOMMANDS [<Esc> to confirm] "
	confirm=$(echo -e "Yes\nNo" | $HOME/scr/i3menu -t -c magenta \
		-o horizontal \
		-p "CONFIRM RENAME? ")
	[[ $confirm == "Yes" ]] && source $FINCMD
}
confirm
rm $NEWNME
rm $OLDNME
rm $FINCMD
