#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Thu  4 Jul 00:27:45 BST 2019

EDITOR="gvim -f"
NEWNME="$USER_TMP_DIR/.bulkrenamenew"
OLDNME="$USER_TMP_DIR/.bulkrenameold"
FINCMD="$USER_TMP_DIR/.finalcommands"
FILES="${1}"
echo "$FILES" > $OLDNME
sed -e "s/^'//g;s/'$//g;s/'\ '/\n/g" -i $OLDNME
sed -e "s/\`/\\\`/g;s/\\\''//g" -i $OLDNME
cat $OLDNME > $NEWNME
$EDITOR $NEWNME
sed -e "s/$/\"/g;s/^/\"/g" -i $NEWNME
sed -e "s/$/\"/g;s/^/mv\ \"/g" -i $OLDNME
paste $OLDNME $NEWNME > $FINCMD
confirm () {
	cat $FINCMD | i3menu -T -c white \
		--prompt "FINALCOMMANDS [<Esc> to confirm] "
	confirm=$(echo -e "Yes\nNo" | \
		i3menu -T -c magenta -o --prompt "CONFIRM RENAME? ")
	[[ $confirm == "Yes" ]] && source $FINCMD
}
confirm
rm $NEWNME
rm $OLDNME
rm $FINCMD
