#!/usr/bin/env bash

TRG=${1%.*}
WCPL=$(cat ${TRG}.tex | grep 'whichcompiler:' | awk '{print $NF}')
if [[ -n $WCPL ]]; then
	CPL=$WCPL
elif [[ -z $WCPL ]]; then
	CPL=pdflatex
fi

${CPL} -interaction=nonstopmode -shell-escape ${TRG}.tex

[[ -f ${TRG}.bcf ]] && {
	biber ${TRG}.bcf
	${CPL} -interaction=nonstopmode -shell-escape ${TRG}.tex
	${CPL} -interaction=nonstopmode -shell-escape ${TRG}.tex
}

[[ -f ${TRG}.nlo ]] && {
	makeindex ${TRG}.nlo -s nomencl.ist -o ${TRG}.nls
	${CPL} -interaction=nonstopmode -shell-escape ${TRG}.tex
}

raux
