#!/usr/bin/env bash

file=$1
whichcomp=$(cat $file | grep 'whichcompiler:' | awk '{print $NF}')
if [[ -n $whichcomp ]]; then
	compiler=$whichcomp
elif [[ -z $whichcomp ]]; then
	compiler=pdflatex
fi

${compiler} -interaction=nonstopmode -shell-escape ${file:0:-4}.tex
if [[ -e ${file:0:-4}.bcf ]]; then
	biber ${file:0:-4}.bcf
	${compiler} -interaction=nonstopmode -shell-escape ${file:0:-4}.tex
	${compiler} -interaction=nonstopmode -shell-escape ${file:0:-4}.tex
else
	:
fi
if [[ -e ${file:0:-4}.nlo ]]; then
	makeindex ${file:0:-4}.nlo -s nomencl.ist -o ${file:0:-4}.nls
	${compiler} -interaction=nonstopmode -shell-escape ${file:0:-4}.tex
else
	:
fi
