#!/usr/bin/env bash

TRG=$1
PDDR=$XDG_TEMPLATES_DIR/pandoc
CSDR=$XDG_TEMPLATES_DIR/css

help () {
cat << 'EOB'
# cmkd
- compile markdown files with pandoc by parsing the yaml header

## Usage

```
cmkd <file>.md
```

## Example

```markdown
---
title: __Title__
subtitle: _Subtitle_
author: Author
theme: CambridgeUS
#output pdf html word beamer  <<< specify output(s)
#css    style.css             <<< full path to css for html output
#engine xelatex               <<< TeX engine for normal pdf
#bib    bibliography.bib      <<< full path to bibliography
#yaml   settings.yaml         <<< full path to yaml file for additional settings
#docx   reference.docx        <<< full path to word document template
---

# A markdown file

+ bullet
	+ bullet
		+ bullet
+ bullet
+ bullet

```

EOB
echo "$1"
exit
}

[[ -z $1 ]] && echo 'No input file! [cmkd --help for more info]' && exit

while true; do
	case $1 in
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

BIB=$(awk '$1 ~ /^#bib$/    {$1="";gsub(/^[ \t]+/,"",$0);print $0}' $TRG )
YML=$(awk '$1 ~ /^#yaml$/   {$1="";gsub(/^[ \t]+/,"",$0);print $0}' $TRG )
WTM=$(awk '$1 ~ /^#docx$/   {$1="";gsub(/^[ \t]+/,"",$0);print $0}' $TRG )
WCS=$(awk '$1 ~ /^#css$/    {$1="";gsub(/^[ \t]+/,"",$0);print $0}' $TRG )
NGN=$(awk '$1 ~ /^#engine$/ {$1="";gsub(/^[ \t]+/,"",$0);print $0}' $TRG )

[[ -z $BIB ]] && BIB="$HOME/global.bib"
[[ -z $YML ]] && FYL="${PDDR}/settings.yaml" || FYL="${YML}"
[[ -z $WTM ]] && DXR="$PDDR/reference.docx"
[[ -n $WCS ]] && CSS="-c ${WCS}"         || CSS="-c ${CSDR}/themer.css"
[[ -n $NGN ]] && NGN="--pdf-engine=$NGN" || NGN=""

REF="-F pandoc-crossref --metadata-file ${FYL}"
CIT="--bibliography ${BIB} -F pandoc-citeproc"
WTS="--reference-doc ${DXR}"
NSC="--number-sections"

pdf    () { pandoc $REF $CIT $NGN $NSC -o ${TRG%.*}.pdf ${TRG} ; }
word   () { pandoc $REF $CIT $WTS -o ${TRG%.*}.docx ${TRG} ; }
html   () { pandoc $REF $CIT -s --toc $CSS -o ${TRG%.*}.html ${TRG} ; }
beamer () { pandoc $CIT -t beamer --incremental -o ${TRG%.*}_beamer.pdf ${TRG} ; }

for i in $(awk '$1 ~ /^#output$/ {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG ); do
	$i
done
