#!/usr/bin/env bash

TRG=$1
WTDR=$XDG_TEMPLATES_DIR/pandoc
CSDR=$XDG_TEMPLATES_DIR/css
BBDR=$HOME
YLDR=$XDG_TEMPLATES_DIR/pandoc

BIB=$(awk '$1 ~ /^#bib$/    {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG )
YML=$(awk '$1 ~ /^#yaml$/   {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG )
WTM=$(awk '$1 ~ /^#doctmp$/ {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG )
WCS=$(awk '$1 ~ /^#css$/    {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG )
NGN=$(awk '$1 ~ /^#engine$/ {$1="";gsub(/^[ \t]+/, "", $0);print $0}' $TRG )

[[ -z $BIB ]] && BIB="$HOME/global.bib"
[[ -z $YML ]] && YML=settings ; FYL="$YLDR/${YML}.yaml"
[[ -z $WTM ]] && WTM=reference
[[ -n $WCS ]] && CSS="-c ${CSDR}/${WCS}.css" || CSS="-c ${CSDR}/themer.css"
[[ -n $NGN ]] && NGN="--pdf-engine=$NGN"     || NGN=""

REF="-F pandoc-crossref --metadata-file ${FYL}"
CIT="--bibliography ${BIB} -F pandoc-citeproc"
WTS="--reference-doc ${WTDR}/${WTM}.docx"
NSC="--number-sections"

pdf () { pandoc $REF $CIT $NGN $NSC -o ${TRG:0:-3}.pdf ${TRG} ; }
word () { pandoc $REF $CIT $WTS -o ${TRG:0:-3}.docx ${TRG} ; }
html () { pandoc $REF $CIT -s --toc $CSS -o ${TRG:0:-3}.html ${TRG} ; }
beamer () { pandoc $CIT -t beamer --incremental -o ${TRG:0:-3}.pdf ${TRG} ; }

output=$(cat $TRG | sed '/^#output /!d;s/[^ ]* *//')
[[ -n $output ]] && $output || html
