#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Fri 19 Jul 14:19:32 BST 2019

help () {
cat << 'EOB'
# colmix
- Script to mix 2 hex colors

## Usage

```
colmix [--hex|-x|--rgb|-r] '<ratio1>:<color1> <ratio2>:<color2>'
colmix --help|-h
```

## Options

+ Final argument has to be `<ratio1>:<color1> <ratio2>:<color2>`
	+ eg. `50:#000000 50:#ffffff`
	+ Ratios are percentages, so `<ratio1> + <ratio2> = 100`

+ `--hex|-x`
	+ Print final color in hex

+ `--rgb|-r`
	+ Print final color in rgb

+ `--help|-h`
	+ Print this help

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--hex  | -x ) PRINT=HEX ;;
		--rgb  | -r ) PRINT=RGB ;;
		--help | -h ) help ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z ${@:-} ]] && help 'No input specified' || echo ${@:-} | awk -F "" -v PRINT="$PRINT" '{
		RAT1=$1$2;
		RAT2=$12$13;
		ONER=$5$6;ONEG=$7$8;ONEB=$9$10;
		TWOR=$16$17;TWOG=$18$19;TWOB=$20$21;
		ONRR=strtonum("0x" ONER); ONRG=strtonum("0x" ONEG); ONRB=strtonum("0x" ONEB);
		TWRR=strtonum("0x" TWOR); TWRG=strtonum("0x" TWOG); TWRB=strtonum("0x" TWOB);
		CL3R=int((ONRR * RAT1 + TWRR * RAT2) / 100);
		CL3G=int((ONRG * RAT1 + TWRG * RAT2) / 100);
		CL3B=int((ONRB * RAT1 + TWRB * RAT2) / 100);
		CL3XR=sprintf("%x",CL3R); CL3XG=sprintf("%x",CL3G); CL3XB=sprintf("%x",CL3B);
		if (length(CL3XR)==1) {CL3XR="0"CL3XR}
		if (length(CL3XG)==1) {CL3XG="0"CL3XG}
		if (length(CL3XB)==1) {CL3XB="0"CL3XB}
		if (PRINT=="HEX") {
			print "#" CL3XR CL3XG CL3XB ;
		} else if (PRINT=="RGB") {
			print "" CL3R ", " CL3G ", " CL3B ;
		} else {
			print CL3XR     CL3XG     CL3XB ;
			print CL3R ", " CL3G ", " CL3B  ;
		}
	}'
