#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Fri 19 Jul 14:19:32 BST 2019

help () {
cat << 'EOB'
# NAME

__colmix__ - Script to mix 2 hex colors

# SYNOPSIS

```
colmix [--hex|-x|--rgb|-r|--verbose|-v] <ratio1>:<color1> <ratio2>:<color2>
colmix --help|-h
```

# EXAMPLE

```sh
$ colmix 50:#00ff00 50:#002b36
  00951b
  0, 149, 27
```

So ![#00ff00](https://placehold.it/15/00ff00/000000?text=+) #00ff00 +
   ![#002b36](https://placehold.it/15/002b36/000000?text=+) #002b36 =
   ![#00951b](https://placehold.it/15/00951b/000000?text=+) #00951b!

# OPTIONS

Final argument has to be `<ratio1>:<color1> <ratio2>:<color2>`  
+ eg. `50:#000000 50:#ffffff`
+ Ratios are percentages, so `<ratio1> + <ratio2> = 100`

`--hex|-x`  
Print final color in hex

`--rgb|-r`  
Print final color in rgb

`--verbose|-v`  
Print input colors and rgb versions as well

`--help|-h`  
Print this help

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--hex     | -x ) PRINT=HEX ;;
		--rgb     | -r ) PRINT=RGB ;;
		--verbose | -v ) PRINT=VER ;;
		--help    | -h ) help      ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z ${@:-} ]] && help 'No input specified' || \
	echo ${@:-} | awk -F "" -v PRINT="$PRINT" '{
		RAT1=$1$2;
		RAT2=$12$13;
		ONER=$5$6;ONEG=$7$8;ONEB=$9$10;
		TWOR=$16$17;TWOG=$18$19;TWOB=$20$21;
		ONRR=strtonum("0x" ONER); ONRG=strtonum("0x" ONEG); ONRB=strtonum("0x" ONEB);
		TWRR=strtonum("0x" TWOR); TWRG=strtonum("0x" TWOG); TWRB=strtonum("0x" TWOB);
		CL3R=int((ONRR * RAT1 + TWRR * RAT2) / 100);
		CL3G=int((ONRG * RAT1 + TWRG * RAT2) / 100);
		CL3B=int((ONRB * RAT1 + TWRB * RAT2) / 100);
		C3XR=sprintf("%x",CL3R); C3XG=sprintf("%x",CL3G); C3XB=sprintf("%x",CL3B);
		if (length(C3XR)==1) {C3XR="0"C3XR}
		if (length(C3XG)==1) {C3XG="0"C3XG}
		if (length(C3XB)==1) {C3XB="0"C3XB}
		if (PRINT=="HEX") {
			print "#"C3XR    C3XG    C3XB;
		} else if (PRINT=="RGB") {
			print    CL3R", "CL3G", "CL3B;
		} else if (PRINT=="VER") {
			print "#"ONER    ONEG    ONEB;
			print    ONRR", "ONRG", "ONRB;
			print "#"TWOR    TWOG    TWOB;
			print    TWRR", "TWRG", "TWRB;
			print "#"C3XR    C3XG    C3XB;
			print    CL3R", "CL3G", "CL3B;
		} else {
			print "#"C3XR    C3XG    C3XB;
			print    CL3R", "CL3G", "CL3B;
		}
	}'
