#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
#source $HOME/.config/user-dirs.dirs

SRC=${1}
EXT=${SRC##*.}

case $EXT in
	tex) ctex "$SRC" ;;
	rmd) echo "require(rmarkdown); render('$SRC')" | R --vanilla ;;
	md)  cmkd "$SRC" ;;
	ms)  crff "$SRC" ;;
esac
