#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
#source $HOME/.config/user-dirs.dirs

help () {
cat << 'EOB'
# NAME

__compiler__ - compile markup documents using one
of my compiler scripts

# SYNOPSIS

```
compiler <file>
compiler --help|-h
```

EOB
exit
}

[[ -z $1 ]] && help || SRC=${1}
EXT=${SRC##*.}

case $EXT in
	tex) ctex "$SRC" ;;
	rmd) echo "require(rmarkdown); render('$SRC')" | R --vanilla ;;
	md)  cmkd "$SRC" ;;
	ms)  crff "$SRC" ;;
esac
