#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__crff__ - compile `.ms` groff files into pdf

# SYNOPSIS

```
crff <file>.ms
crff --help|-h
```
EOB
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z $1 ]] && help

SRC=$1
TRG=${SRC%.*}
#groff -ms ${SRC} -T pdf > ${TRG}.pdf
refer -PS -p $HOME/global -e "${SRC}" | groff -me -ms -keEjpt -T pdf > ${TRG}.pdf
