#!/usr/bin/env bash

#while true; do
#	case $1 in
##		--<++> | -<++> ) <++>="${2:-}" ; shift ;;
#		--help ) help ;;
#		-h ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
#		-- ) shift ; break ;;
#		*  ) break         ;;
#	esac
#	shift
#done

declare -A TMR
eval "$(themer --list varsh)"
#echo "${TMR[bg1]}"
#echo "${TMR[fg1]}"
#echo "${TMR[acf]}"
#echo "${TMR[bg1]}"
#echo "${TMR[bg1]}"
#echo "${TMR[ylw]}"
#echo "${TMR[acf]}"
#echo "${TMR[ylw]}"
dmenu_run -fn "luximono:size=15" ${@:-} \
	-nb  "${TMR[acb]}" -nf  "${TMR[fg1]}" -sb  "${TMR[acf]}" -sf  "${TMR[acb]}" \
	-nhb "${TMR[acb]}" -nhf "${TMR[ylw]}" -shb "${TMR[acf]}" -shf "${TMR[ylw]}"
