#!/usr/bin/env bash

CMD=dmenu
ACC=acb
declare -A TMR
eval "$(themer --list varsh)"

help () {
cat << 'EOB'
# NAME

__dmrap__ - dmenu wrapper

# SYNOPSIS

```
dmrap
```
EOB
exit
}

while true; do
	case $1 in
		--run    | -r ) CMD=dmenu_run ;;
		--font   | -f ) FONT="${2:-}" ; shift ;;
		--accent | -a ) ACC="${2:-}"  ; shift ;;
		--help ) help ;;
		-h ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

if [[ $CMD == "dmenu" ]]; then
	cat /dev/stdin | dmenu ${@} -fn "${FONT:-"Iosevka 18"}" \
		-nb  "${TMR[$ACC]}" -nf  "${TMR[fg1]}" \
		-sb  "${TMR[fg1]}"  -sf  "${TMR[$ACC]}" \
		-nhb "${TMR[$ACC]}" -nhf "${TMR[bg1]}" \
		-shb "${TMR[fg1]}"  -shf "${TMR[bg1]}" \
		-hb  "${TMR[$ACC]}" -hf  "${TMR[acf]}" \
		-ib  "${TMR[$ACC]}" -if  "${TMR[bg1]}"
else
	dmenu_run -p run ${@} -fn "${FONT:-"Iosevka 18"}" \
		-nb  "${TMR[$ACC]}" -nf  "${TMR[fg1]}" \
		-sb  "${TMR[fg1]}"  -sf  "${TMR[$ACC]}" \
		-nhb "${TMR[$ACC]}" -nhf "${TMR[bg1]}" \
		-shb "${TMR[fg1]}"  -shf "${TMR[bg1]}" \
		-hb  "${TMR[$ACC]}" -hf  "${TMR[acf]}" \
		-ib  "${TMR[$ACC]}" -if  "${TMR[bg1]}"
fi
