#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 30 Mar 18:22:18 GMT 2019

help () {
cat << 'EOB'
# edtr
- vim server wrapper

## Synopsis
```
edtr [--server|-s <name>] <file>
edtr [--help|-h]
```

## Options

+ `--server|-s <name>`
	+ '-`<name>`' is appended to the default `--servername`
	+ Default `--servername` is 'edtr'

+ `--help|-h`
	+ Print this help

EOB
exit
}

SVR=edtr

while true; do
	case $1 in
		--server | -s ) SVO="${2:-}" ; shift ;;
		--help   | -h ) help         ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TRG="${@:-}"

EXT="${TRG##*/}" ; EXT="${EXT##*.}"

TYP="$(file $(readlink -f "$TRG"))"
TYP="${TYP#*:}" ; TYP="${TYP#* }" ; TYP="${TYP%% *}"
[[ $TYP == "Bourne-Again" ]] && TPF=bash

case $EXT in
	Xres*|Xdef*) EXF=Xfiles  ;;
	*conf*)      EXF=configs ;;
	*bash*)      EXF=bash    ;;
	sh)          EXF=sh      ;;
	*vim*)       EXF=vim     ;;
	yaml)        EXF=yaml    ;;
	html)        EXF=html    ;;
	py)          EXF=py      ;;
	ms)          EXF=groff   ;;
	css)         EXF=css     ;;
	md|rmd)      EXF=md      ;;
	bib)         EXF=bib     ;;
	tex)         EXF=tex     ;;
esac

[[ -n $TPF ]] && SVR="edtr-$TPF"
[[ -n $EXF ]] && SVR="edtr-$EXF"
[[ -n $SVO ]] && SVR="$SVO"

urxvtc -name "${SVR}" -fn "xft:Luxi Mono:size=13" \
	-e vim --servername "${SVR}" --remote-tab \
	"${TRG}" &>/dev/null &
