#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 30 Mar 18:22:18 GMT 2019

help () {
cat << 'EOB'
# NAME

__edtr__ - vim server wrapper using `rxvt-unicode`

# SYNOPSIS

```
edtr [--server|-s <name>] [--fontsize|-S <integer>] <file>
edtr --help|-h
```

# OPTIONS

`--server|-s <name>`  
`--servername` changed to `<name>`.
Default `--servername` is 'edtr'.

`--help|-h`  
Print this help

# MORE

`edtr` will also decide the `--servername` based
on filetype (from `file` output) and file extension:

|  Filetype      |  servername  |  urxvt instance name  |
| --------------:|:------------ |:--------------------- |
| `Bourne-Again` | `bash-edtr`  | `bash - edtr`         |

|  Extension    |  servername    |  urxvt instance name  |
| -------------:|:-------------- |:--------------------- |
| `Xres*/Xdef*` | `edtr-Xfiles`  | `Xfiles - edtr`       |
| `*conf*`      | `edtr-configs` | `configs - edtr`      |
| `*bash*`      | `edtr-bash`    | `bash - edtr`         |
| `sh`          | `edtr-sh`      | `sh - edtr`           |
| `*vim*`       | `edtr-vim`     | `vim - edtr`          |
| `yaml`        | `edtr-yaml`    | `yaml - edtr`         |
| `html`        | `edtr-html`    | `html - edtr`         |
| `py`          | `edtr-py`      | `py - edtr`           |
| `ms`          | `edtr-groff`   | `groff - edtr`        |
| `css`         | `edtr-css`     | `css - edtr`          |
| `md|rmd`      | `edtr-md`      | `md - edtr`           |
| `bib`         | `edtr-bib`     | `bib - edtr`          |
| `tex`         | `edtr-tex`     | `tex - edtr`          |
EOB
exit
}

FNT="Iosevka"
SZE=18
SVR=edtr
INS=edtr

while true; do
	case $1 in
		--font     | -f ) FNT="${2:-}" ; shift ;;
		--server   | -s ) SVO="${2:-}" ; shift ;;
		--fontsize | -S ) SZE="${2:-}" ; shift ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TRG="${@:-}"

EXT="${TRG##*/}" ; [[ ${EXT} =~ "." ]] && EXT="${EXT##*.}"

TYP="$(file $(readlink -f "$TRG"))"
TYP="${TYP#*:}" ; TYP="${TYP#* }" ; TYP="${TYP%% *}"
[[ $TYP == "Bourne-Again" ]] && TPF=bash

case $EXT in
	Xres*|Xdef*) EXF=Xfiles  ; FNT="Iosevka" ;;
	*conf*)      EXF=configs ; FNT="Iosevka" ;;
	*bash*)      EXF=bash    ; FNT="Iosevka" ;;
	sh)          EXF=sh      ; FNT="Iosevka" ;;
	*vim*)       EXF=vim     ; FNT="Iosevka" ;;
	yaml)        EXF=yaml    ; FNT="Iosevka" ;;
	html)        EXF=html    ; FNT="Iosevka" ;;
	py)          EXF=py      ; FNT="Iosevka" ;;
	ms)          EXF=groff   ; FNT="Iosevka" ;;
	css)         EXF=css     ; FNT="Iosevka" ;;
	bib)         EXF=bib     ; FNT="Iosevka" ;;
	md|rmd)      EXF=md  ; FNT="$(themer -v 'editfont ')" ;;
	tex)         EXF=tex ; FNT="$(themer -v 'editfont ')" ;;
esac

[[ -n $TPF ]] && SVR="edtr-$TPF" INS="$TPF - edtr"
[[ -n $EXF ]] && SVR="edtr-$EXF" INS="$EXF - edtr"
[[ -n $SVO ]] && SVR="$SVO"      INS="$SVO"

#urxvtc -name "${INS}" -fn "xft:${FNT}:size=${SZE}" \
st -n "${INS}" -f "${FNT}:size=${SZE}" \
	-e vim --servername "${SVR}" --remote-tab \
	"${TRG}" &>/dev/null &
