#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue 25 Dec 21:35:29 GMT 2018

file="$1"

case "$file" in
	*\.tar.gz)
		mkdir "${file/.tar.gz/}"
		tar -xvf "${file}" -C "${file/.tar.gz/}"
		;;
	*\.tar.xz)
		mkdir "${file/.tar.xz/}"
		tar -xJf "${file}" -C "${file/.tar.xz/}"
		;;
	*\.zip) unzip "${file}" -d "${file%.*}" ;;
	*\.gz) gunzip "${file}" -d "${file%.*}" ;;
	*\.rar) unrar x "${file}" ;;
esac
