#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue 25 Dec 21:35:29 GMT 2018

file="$1"

case "$file" in
	*\.tar.gz) tar -xvf "${file}" ;;
	*\.tar.xz) tar -xJf "${file}" ;;
	*\.zip) unzip "${file}" -d "${file:0:-4}" ;;
	*\.gz) gunzip "${file}" -d "${file:0:-3}" ;;
	*\.rar) unrar x "${file}" ;;
esac
