#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 30 Mar 18:22:18 GMT 2019
help () {
cat << 'EOB'
# NAME

__gedtr__ - gvim server wrapper

# SYNOPSIS

```
gedtr [--server|-s <name>] <file>
gedtr --help|-h
```

# OPTIONS

`--server|-s <name>`  
Specify server name. Default is `GVIM`.

`--help|-h`  
Print this help

EOB
exit
}

SVR=GVIM

while true; do
	case $1 in
		--server | -s ) SVR="${2:-}" ; shift ;;
		--help | -h ) help ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done


TRG="${@:-}"

gvim --servername $SVR --remote-tab "${TRG}" &>/dev/null &
