#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 22 Jul 19:53:50 BST 2019

CLDIR=$XDG_DOCUMENTS_DIR/personal/coverletters
PLT=$XDG_TEMPLATES_DIR/tex/coverletter/coverletter.tex
[[ -n $1 ]] && TIT="$1" || \
	TIT="$(echo "" | i3menu -p "Enter title of Cover Letter... " -c yellow -W -L 0)"
EDITOR="gvim -f"

#while getopts :t: opts; do
#	case $opts in
#		t)
#			TIT="$OPTARG"
#			;;
#	esac
#done

FLD="$(echo ${TIT} | sed 's/\ //g')"
#TIT="$(echo $TIT | sed 's/\ /\\\ /g')"
echo $FLD
echo $TIT

[[ ! -f $CLDIR ]] && mkdir $CLDIR
cd $CLDIR
[[ ! -f $CLDIR ]] && mkdir $FLD
cd $FLD
cp $PLT ${FLD}.tex
sed -e "s/TITLE/$TIT/g" -i ${FLD}.tex
#touch maintext.tex
$EDITOR maintext.tex
$SCR_DIR/clatex ${FLD}.tex
