#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 22 Jul 19:53:50 BST 2019

CLDIR=$XDG_DOCUMENTS_DIR/mine/cvl
PLT=$XDG_TEMPLATES_DIR/md/cvl.md
EDITOR="gvim -f"

help () {
cat << 'EOB'
                                             ██
   █████                                    ▒██
  ██▒▒▒██  █████  ███████   █████  ██    ██ ▒██
 ▒██  ▒██ ██▒▒▒██▒▒██▒▒▒██ ██▒▒▒██▒██   ▒██ ▒██
 ▒▒██████▒███████ ▒██  ▒██▒██  ▒▒ ▒▒██ ▒██  ▒██
  ▒▒▒▒▒██▒██▒▒▒▒  ▒██  ▒██▒██   ██ ▒▒████   ▒██
   █████ ▒▒██████ ███  ▒██▒▒█████   ▒▒██    ███
  ▒▒▒▒▒   ▒▒▒▒▒▒ ▒▒▒   ▒▒  ▒▒▒▒▒     ▒▒    ▒▒▒ 
	-- job appliction cover letter generator
	     using latex

Usage
-----

gencvl -h        ┼ print this help
gencvl -n [NAME] ┼ create new coverletter
                 │   with name NAME
EOB
}

while getopts :n:h opts; do
	case $opts in
		n) TIT="$OPTARG" ;;
		h) help && exit  ;;
	esac
done

[[ -n $TIT ]] || TIT="$(echo "" | i3menu -c yellow -w 500 -p "Enter title: ")"
[[ -n $TIT ]] || exit

FLD="$(echo "${TIT}" | sed 's/\ //g')"
[[ ! -d $CLDIR ]] && mkdir $CLDIR
cd $CLDIR
[[ ! -d $FLD ]] && mkdir $FLD
cd $FLD
cp $PLT ${FLD}.md
sed -e "s/TITLE/$TIT/g" -i ${FLD}.md
$EDITOR ${FLD}.md
compiler ${FLD}.md
raux
