#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 22 Jul 19:53:50 BST 2019

CLDIR=$XDG_DOCUMENTS_DIR/mine/cvl
PLT=$XDG_TEMPLATES_DIR/md/cvl.md
EDITOR="gvim -f"

help () {
cat << 'EOB'
# gencvl
- job application cover letter generator using latex

## Synopsis

```
gencvl <name>
gencvl [--help|-h]
```

## Options

+ `<name>`
	+ `<name>` of coverletter

+ `--help|-h`
	+ Print this help

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help | -h ) help ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TIT="${@:-}"

[[ -n $TIT ]] || TIT="$(echo "" | i3menu -c yellow -w 500 -p "Enter title: ")"
[[ -n $TIT ]] || help

FLD="$(echo "${TIT}" | sed 's/\ //g')"
[[ ! -d $CLDIR ]] && mkdir $CLDIR
cd $CLDIR
[[ ! -d $FLD ]] && mkdir $FLD
cd $FLD
cp $PLT ${FLD}.md
sed -e "s/TITLE/$TIT/g" -i ${FLD}.md
$EDITOR ${FLD}.md
compiler ${FLD}.md
raux
