#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
#source $HOME/.config/user-dirs.dirs

DIR="$USER_REPO_DIR/ghb"
EDITOR="gvim -f"
[[ -d $DIR ]] && cd $DIR || {
#	echo "NEED TO RUN hugo new site quickstart IN THE APPROPRIATE DIRECTORY"
	mkdir ${DIR%/*}
	cd ${DIR%/*}
	hugo new site quickstart
	mv quickstart ${DIR##*/}
	cd $DIR
	}

new () {
	[[ -n $1 ]] && POST="$1" || \
		POST=$(ls content/posts | sed '/.md$/!d;s/.md//g' | i3menu -c green)
	[[ -z $POST ]] && exit
	[[ -f content/posts/${POST}.md ]] || hugo new posts/${POST}.md
	hugo server &>/dev/null &
	i3launch 'surf localhost:1313' _W2 &>/dev/null &
	i3-msg -q [con_mark="_W3"] focus
	$EDITOR content/posts/${POST}.md
	killall hugo
	killall surf
	cd $DIR
	hugo
}

list () { ls content/posts | sed '/.md$/!d' ; }

delete () { rm -rf content/posts/${1}.md ; }

help () {
	cat << 'EOB'
          ██      ██     
   █████ ▒██     ▒██     
  ██▒▒▒██▒██     ▒██     
 ▒██  ▒██▒██████ ▒██████ 
 ▒▒██████▒██▒▒▒██▒██▒▒▒██
  ▒▒▒▒▒██▒██  ▒██▒██  ▒██
   █████ ▒██  ▒██▒██████ 
  ▒▒▒▒▒  ▒▒   ▒▒ ▒▒▒▒▒   
	-- a hugo blog wrapper script

 Dependencies
 ____________
 
 hugo
 
 Usage
 _____
 
 ghb --post|-p   [NAME] ┼ NAME of post to create
 ghb --list|-l          ┼ list posts in content/posts
 ghb --delete|-d [NAME] ┼ NAME of post to delete
 ghb --help|-h          ┼ print this help
EOB
exit
}

while true; do
	case $1 in
		--post   | -p ) new "${2:-}"    ; shift ;;
		--list   | -l ) list            ; shift ;;
		--delete | -d ) delete "${2:-}" ; shift ;;
		--help   | -h ) help            ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done
