#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
#source $HOME/.config/user-dirs.dirs

DIR="$USER_REPO_DIR/ghb"
EDITOR="gvim -f"
[[ -d $DIR ]] && cd $DIR || {
#	echo "NEED TO RUN hugo new site quickstart IN THE APPROPRIATE DIRECTORY"
	mkdir ${DIR%/*}
	cd ${DIR%/*}
	hugo new site quickstart
	mv quickstart ${DIR##*/}
	cd $DIR
	}

help () {
cat << 'EOB'
# NAME

__ghb__ - a hugo blog wrapper script

# DEPENDENCIES

```
hugo
```

# SYNOPSIS

```
ghb --post|-p|--delete|-d <name>
ghb --list|-l
ghb --help|-h
```

# OPTIONS

`--post|-p <name>`  
`<name>` of post to create

`--list|-l`  
list all posts

`--delete|-d <name>`  
`<name>` of post to delete

`--help|-h`  
Print this help

EOB
echo "$1"
exit
}

new () {
	[[ -n $1 ]] && POST="$1" || \
		POST=$(ls content/posts | sed '/.md$/!d;s/.md//g' | i3menu -c green)
	[[ -z $POST ]] && exit
	[[ -f content/posts/${POST}.md ]] || hugo new posts/${POST}.md
	hugo server &>/dev/null &
	surf localhost:1313 &>/dev/null &
	$EDITOR content/posts/${POST}.md
	killall hugo
	killall surf
	cd $DIR
	hugo
}

list () { ls content/posts | sed '/.md$/!d' ; }

delete () { rm -rf content/posts/${1}.md ; }

while true; do
	case $1 in
		--post   | -p ) new "${2:-}"    ; shift ;;
		--list   | -l ) list            ; shift ;;
		--delete | -d ) delete "${2:-}" ; shift ;;
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done
