#!/usr/bin/env bash

cd $USER_REPO_DIR
[[ -n $1 ]] && RPO="$1" || \
	RPO="$(ls | dmrap -f 'Iosevka 17' -a lightylw -w 300 -L mc -l 15 -p gitcommit)"

herbe "Updating your $RPO git repo..." &
cd ${RPO}
pwd
git add .
git commit -m "$(date +"%c")"
git fetch
git merge origin/master
git push -u origin master
herbe "... $RPO repo updated." &
