#!/usr/bin/env bash

notify-send "Syncing Drive folder..." -i ${USER_SCR_DIR}pic/drivesyncing.png
cd $USER_DRV_DIR
grive
cd
notify-send "... Drive folder synced." -i ${USER_SCR_DIR}pic/googledrive.png
