#!/usr/bin/env bash

# OA: Gavin Vales

CTXT=" "

update () {
	CRLN=$(readlink -f $XDG_PICTURES_DIR/gwc/current)
#	_I="%{A1:$(basename $0)       :}%{T1}%{T-}%{A}"
	_I=" "
	_P="%{A1:$(basename $0) previous:}%{T1}%{T-}%{A}"
	_N="%{A1:$(basename $0)     next:}%{T1}%{T-}%{A}"
	_R="%{A1:$(basename $0)   random:}%{T1}%{T-}%{A}"
	_D="%{A1:$(basename $0)   delete:}%{T1}%{T-}%{A}"
	_E="%{A1:$(basename $0)   rename:}%{T1}%{T-}%{A}"
	_C="%{A1:$(basename $0)     list:}${CRLN##*/}%{A}"
	if [[ $CTXT == "$_I" ]]; then
		_F=" $_P $_R $_E $_D $_N $_C"
	else
		_F="$_I"
	fi
	pbcat --module gwc "$_F"
}

case $1 in
	show) CTXT=$(pbcat -m gwc) && update ;;
	blur|previous|next|random) gwc -${1:0:1} && update ;;
	delete)
		CONFIRM=$(echo -e "Yes\nNo" | i3menu -y 0 -M -c red)
		[[ $CONFIRM == "YES" ]] && {
			gwc -d
			gwc -r
			update
		}
		;;
	rename)
		NAME=$(echo "" | i3menu -M -x 65 -y -10 -c black)
		[[ -n $NAME ]] && {
			gwc -R "$NAME"
			gwc -w "$NAME"
			update
		}
		;;
	list)
		wall=$(ls $XDG_PICTURES_DIR/gwc/normal | i3menu -M -l 10 -w 300)
		[[ -n $wall ]] && gwc -w $wall && update
		;;
esac
