#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon  4 Nov 00:10:18 GMT 2019

CHK=$(pidof cwm)
[[ -n $CHK ]] || echo "cwm not running" && exit 1
GWMDIR=$HOME/.config/gwm
CONF=$GWMDIR/config

defaults () {
cat > $CONF << 'EOB'
GAPS=20
BORDER=2
W1W=
W1H=
EOB
exit
}

[[ -f $CONF ]] || defaults
[[ -d $GWMDIR ]] || mkdir $GWMDIR
cd $GWMDIR 

help () {
cat << 'EOB'
# NAME

__gwmc__ - manage custom `wmutils` scripts

# SYNOPSIS

```
gwmc <commands to run>
gwmc --help|-h
```

# DESCRIPTION

Basically runs one of the scripts in the default gwm directory.
For me, that's `$HOME/.config/gwm/bin`.

EOB
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

cd ${GWMDIR}/bin
CMD="${@#* }"
ARG="${@/${CMD}/}"
echo $PWD
echo $CMD
echo $ARG
#./${CMD} "${ARG}"
