#!/bin/bash

# OA: Gavin Vales

CTXT=" "

update () {
	CRLN=$(readlink -f $XDG_PICTURES_DIR/i3bg/current)
	PBSCR=$HOME/scr/pb
#	_I="%{A1:i3bgc       :}%{T1}%{T-}%{A}"
	_I=" "
	_P="%{A1:i3bgc   prev:}%{T1}%{T-}%{A}"
	_N="%{A1:i3bgc   next:}%{T1}%{T-}%{A}"
	_R="%{A1:i3bgc random:}%{T1}%{T-}%{A}"
	_D="%{A1:i3bgc delete:}%{T1}%{T-}%{A}"
	_E="%{A1:i3bgc rename:}%{T1}%{T-}%{A}"
	_C="%{A1:i3bgc   list:}${CRLN##*/}%{A}"
	if [[ $CTXT == "$_I" ]]; then
		_F=" $_P $_R $_E $_D $_N $_C"
	else
		_F="$_I"
	fi
	pbcat --module i3bg "$_F"
}

case $1 in
	show)   CTXT=$(pbcat -m i3bg) && update ;;
	blur)   i3bg -b                         ;;
	prev)   i3bg -w prev          && update ;;
	next)   i3bg -w next          && update ;;
	random) i3bg -w random        && update ;;
	delete)
		CONFIRM=$(echo -e "Yes\nNo" | i3menu -y 0 -m -c red)
		[[ $CONFIRM == "YES" ]] && {
			i3bg -d ""
			i3bg -w RANDOM
			update
		}
		;;
	rename)
		NAME=$(echo " " | i3menu -m -L 0 -x 65 -y -10 -c black)
		[[ -n $NAME ]] && {
			i3bg -r "$NAME"
			i3bg -w "$NAME"
			update
		}
		;;
	list)
		wall=$(ls $XDG_PICTURES_DIR/i3bg/normal | i3menu -m -L 10 -w 300)
		[[ -n $wall ]] && i3bg -w $wall && update
		;;
esac
