#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat  6 Jul 00:50:41 BST 2019

# COMMAND TO UPDATE BLUR OF BLURS
# for i in $(ls); do convert "${i}" -blur $blr "${PWD/normal/blur}/${i}"; echo "$i"; done

WDIR="$XDG_PICTURES_DIR/i3bg"
NORM="${WDIR}/normal"
BLUR="${WDIR}/blur"
COLS="${WDIR}/cols"
[[ -d $WDIR ]] || {
	mkdir $WDIR
	mkdir $NORM
	mkdir $BLUR
	mkdir $COLS
}
NWFD="$NORM"
CURR="${WDIR}/current"
WHT="${WDIR}/white.jpg"
CRLN="$(readlink -f $CURR)"
HIST="${WDIR}/.history"
MONDIM=$(xdpyinfo | awk '/dimensions/ {print $2}')
MX=${MONDIM%x*}
MY=${MONDIM#*x}
blr=0x16

add-wall () {
	SRC="$1"
	TRG="${1##*/}"
	TRG="${TRG%.*}"
	TRG="$(echo $TRG | sed -e "s/1920x1080//g;s/,//g;s/\ //g")"
	echo "$SRC >> $NORM/$TRG"
	[[ -f ${NORM}/${TRG} ]] || {
		convert "${SRC}" -resize "${MX}x${MY}^" -gravity center \
			-extent "${MX}x${MY}" "${NORM}/${TRG}"
		convert "${NORM}/${TRG}" -blur $blr "${BLUR}/${TRG}"
		}
	WPP="$TRG"
}

add () {
	[[ -d $1 ]] || { echo "Directory doesn't exist." ; exit ; }
	cd "$1"
	count=0
	total=$(ls | wc -l)
	echo "Adding..."
	IFS=$'\n'
	for i in $(find -type f); do
		count=$((count + 1))
		SRC="$i"
		SRC="${SRC#*/}"
		TRG="${i#*/}"
		TRG="${TRG%.*}"
		TRG="$(echo $TRG | sed -e "s/1920x1080//g;s/,//g;s/\ //g")"
		echo -ne "${count}/${total} $TRG"\\r
		[[ ! -f ${NORM}/${TRG} ]] && convert "${SRC}" \
			-resize "${MX}x${MY}^" \
			-gravity center \
			-extent "${MX}x${MY}" "${NORM}/${TRG}"
		[[ ! -f ${BLUR}/${TRG} ]] && convert "${NORM}/${TRG}" \
			-blur $blr "${BLUR}/${TRG}"
	done
	exit
}

tint () {
	CRTNT="${NORM}/${CRLN##*/}-${TNT/\#/}"
	[[ -f $CRTNT ]] || {
		convert "$CURR" -fill "${TNT}" -tint 100 "$CRTNT"
		convert "${CRTNT}" -blur 0x4 "${CRTNT/normal/blur}"
		}
	ln -sf "$CRTNT" $CURR
	CRLN=$(readlink -f $CURR)
}

colour () {
	[[ ! -f ${COLS}/${WPP/\#/} ]] && \
		convert $WHT -fill $WPP \
		-draw 'color 0,0 replace' "${COLS}/${WPP/\#/}"
	ln -sf "${COLS}/${WPP/\#/}" $CURR
	set-wall
}

change-current () {
	ln -sf "${NWFD}/${WPP}" $CURR
	CRLN="$(readlink -f $CURR)"
}

set-wall () {
	feh --bg-center $CURR
	echo "${CRLN##*/}"
}

list () {
	cd $NORM
	$HOME/scr/openimage "$(ls | head -n 1)"
	exit
}

history () {
	[[ ! -f $HIST ]] && touch $HIST
	sed -e "/"${1}"/d" -i $HIST
	echo -e "${1}\n$(cat $HIST)" > $HIST
}

delete () {
	[[ -n ${1} ]] && DEL="${1}" || DEL="${CRLN##*/}"
	rm -rf ${NORM}/${DEL}
	rm -rf ${BLUR}/${DEL}
	[[ ! -f ${NORM}/${DEL} ]] && echo "Deleted ${NORM}/${DEL}"
	[[ ! -f ${BLUR}/${DEL} ]] && echo "Deleted ${BLUR}/${DEL}"
	exit
}

rename () {
	NWNM="$1"
	[[ -n $1 ]] && {
		cd $NORM && mv "${CRLN##*/}" "${1}"
		cd $BLUR && mv "${CRLN##*/}" "${1}"
		}
	exit
}

next () {
	WPP="$(sed -n "/"${CRLN##*/}"/{n;p;}" $HIST)"
	[[ -z $WPP ]] && WPP="$(head -n 1 $HIST)"
}

prev () {
	WPP="$(sed -n "/"${CRLN##*/}"/{g;1!p;};h" $HIST)"
	[[ -z $WPP ]] && WPP="$(tail -n 1 $HIST)"
}

help () {
cat << 'EOB'
  ██  ████  ██             
 ▒▒  █▒▒▒ █▒██       █████ 
  ██▒    ▒█▒██      ██▒▒▒██
 ▒██   ███ ▒██████ ▒██  ▒██
 ▒██  ▒▒▒ █▒██▒▒▒██▒▒██████
 ▒██ █   ▒█▒██  ▒██ ▒▒▒▒▒██
 ▒██▒ ████ ▒██████   █████ 
 ▒▒  ▒▒▒▒  ▒▒▒▒▒    ▒▒▒▒▒  
 	-- A script to set wallpaper, with other features.

 Usage
 -----
 i3bg                            ┼ Create default directories:
                                 │   WALL_DIR/(normal|blur|cols)
 i3bg --help|-h                  ┼ Print this help
 i3bg --wallpaper|-w [PATH|prev| ┼ Wallpaper to set 
                     next|random │
                       |NAME]    │
 i3bg --tint|-t      [HEX COLOR] ┼ Tint color of wallpaper
 i3bg --add|-a       [DIRECTORY] ┼ Add walls from DIRECTORY
 i3bg --list|-l                  ┼ List available wallpapers
 i3bg --blur|-b                  ┼ Toggle blur
 i3bg --rename|-r         [NAME] ┼ Rename current wallpaper
 i3bg --delete|-d                ┼ Remove wallpaper from
                                 │   WALL_DIR/(normal|blur)
 
 WALL_DIR  ┼ Default i3bg folder:
           │   $XDG_PICTURES_DIR/i3bg
 DIRECTORY ┼ is a path to a directory containing pictures
 HEX COLOR ┼ Hexadecimal color Eg. #002b36
 PATH      ┼ is a path to a picture
 prev      ┼ previous wallpaper in history
 next      ┼ next wallpaper in history
 NAME      ┼ name of wallpaper stored in WALL_DIR/normal
 random    ┼ random wallpaper in WALL_DIR/normal

EOB
exit
}

while true; do
	case $1 in
		--wallpaper | -w ) WPP="${2:-}" WPPACT="${2:-}" ; shift ;;
		--tint      | -t ) TNT="${2:-}"                 ; shift ;;
		--add       | -a ) add "${2:-}"                 ; shift ;;
		--delete    | -d ) delete "${2:-}"              ; shift ;;
		--rename    | -r ) rename "${2:-}"              ; shift ;;
		--list      | -l ) list                         ; shift ;;
		--blur      | -b ) BLURT=TRUE                   ; shift ;;
		--help      | -h ) help                         ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

if [[ -n $WPP ]]; then
	[[ $WPP =~ "#" ]]          && colour && exit
	[[ $WPP == "random" ]]     && WPP=$(ls $NORM | shuf -n 1)
	[[ $WPP == "prev" ]]       && prev
	[[ $WPP == "next" ]]       && next
	WPC=${WPP##*/}
	[[ ! -f $NORM/${WPC%.*} ]] && echo "Adding ${WPC%.*}" && add-wall "$WPP"
	change-current
	[[ ! -f "$WPP" ]]          && [[ ! -f "$NORM/${WPC%.*}" ]] && help \
		&& echo "Wallpaper doesn't exist"
fi

[[ $BLURT == "TRUE" ]] && {
	CRFD=${CRLN%/*}
	CRFD=${CRFD##*/}
	[[ ${CRFD} == "normal" ]] \
		&& ln -sf  ${CRLN/\/normal\//\/blur\/} $CURR && NWFD="$BLUR" \
		|| ln -sf  ${CRLN/\/blur\//\/normal\/} $CURR
}

[[ -n $TNT ]] && tint
set-wall
[[ $WPPACT == "NEXT" ]] || [[ $WPPACT == "PREV" ]] || history ${CRLN##*/}
