#!/usr/bin/env bash

# OA: Gavin Vales

CTXT=" "

update () {
	CRLN=$(readlink -f $XDG_PICTURES_DIR/gwc/current)
	PBSCR=$HOME/scr/pb
#	_I="%{A1:i3bgc       :}%{T1}%{T-}%{A}"
	_I=" "
	_P="%{A1:i3bgc previous:}%{T1}%{T-}%{A}"
	_N="%{A1:i3bgc     next:}%{T1}%{T-}%{A}"
	_R="%{A1:i3bgc   random:}%{T1}%{T-}%{A}"
	_D="%{A1:i3bgc   delete:}%{T1}%{T-}%{A}"
	_E="%{A1:i3bgc   rename:}%{T1}%{T-}%{A}"
	_C="%{A1:i3bgc     list:}${CRLN##*/}%{A}"
	if [[ $CTXT == "$_I" ]]; then
		_F=" $_P $_R $_E $_D $_N $_C"
	else
		_F="$_I"
	fi
	pbcat --module i3bg "$_F"
}

case $1 in
	show) CTXT=$(pbcat -m i3bg) && update ;;
	blur|previous|next|random) gwc -${1:0:1} && update ;;
	delete)
		CONFIRM=$(echo -e "Yes\nNo" | i3menu -y 0 -m -c red)
		[[ $CONFIRM == "YES" ]] && {
			gwc -d
			gwc -r
			update
		}
		;;
	rename)
		NAME=$(echo " " | i3menu -m -L 0 -x 65 -y -10 -c black)
		[[ -n $NAME ]] && {
			gwc -R "$NAME"
			gwc -w "$NAME"
			update
		}
		;;
	list)
		wall=$(ls $XDG_PICTURES_DIR/gwc/normal | i3menu -m -L 10 -w 300)
		[[ -n $wall ]] && gwc -w $wall && update
		;;
esac
