#!/usr/bin/env bash

case $1 in
	inc) light -A 5 ;;
	dec) light -U 5 ;;
esac

BLR=$(light -G)
BL=${BLR%.*}

if [[ $BL -ge 100 ]]; then
	BAR="████████████████████"
elif [[ $BL -ge 90 ]]; then
	BAR="██████████████████"
elif [[ $BL -ge 80 ]]; then
	BAR="████████████████"
elif [[ $BL -ge 70 ]]; then
	BAR="██████████████"
elif [[ $BL -ge 60 ]]; then
	BAR="████████████"
elif [[ $BL -ge 50 ]]; then
	BAR="██████████"
elif [[ $BL -ge 40 ]]; then
	BAR="████████"
elif [[ $BL -ge 30 ]]; then
	BAR="██████"
elif [[ $BL -ge 20 ]]; then
	BAR="████"
elif [[ $BL -ge 10 ]]; then
	BAR="██"
else
	BAR=""
fi

polybar-msg hook backlight 1

dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/brightness-full.png " ${BL}% $BAR "
