#!/usr/bin/env bash

nightmode () {
	NMFL=$USER_TMP_DIR/nightmode
	[[ -f $NMFL ]] || echo off > $NMFL
	CRMD=$(cat $NMFL)

	if [[ $CRMD == "off" ]]; then
		redshift -P -O 3700
		echo on > $NMFL
	elif [[ $CRMD == "on" ]]; then
		redshift -x
		echo off > $NMFL
	fi
}

case $1 in
	nm)  nightmode         ;;
	inc) xbacklight -inc 5 ;;
	dec) xbacklight -dec 5 ;;
#	inc) light -A 5        ;;
#	dec) light -U 5        ;;
esac

BLR=$(light -G)
BL=${BLR%.*}

update () {
	NM=$(cat $USER_TMP_DIR/nightmode)
	_NM="%{T1} %{T-}"
	[[ $NM == "on" ]] && _NM="%{T1} %{T-}"
	_MS="%{A1:i3brightness nm:}%{A4:i3brightness inc:}%{A5:i3brightness dec:}${_NM}${BL}%{A}%{A}%{A}"
	pbcat -m backlight -v "${_MS}"
}

if [[ $BL -ge 100 ]]; then
	BAR="████████████████████"
elif [[ $BL -ge 90 ]]; then
	BAR="██████████████████"
elif [[ $BL -ge 80 ]]; then
	BAR="████████████████"
elif [[ $BL -ge 70 ]]; then
	BAR="██████████████"
elif [[ $BL -ge 60 ]]; then
	BAR="████████████"
elif [[ $BL -ge 50 ]]; then
	BAR="██████████"
elif [[ $BL -ge 40 ]]; then
	BAR="████████"
elif [[ $BL -ge 30 ]]; then
	BAR="██████"
elif [[ $BL -ge 20 ]]; then
	BAR="████"
elif [[ $BL -ge 10 ]]; then
	BAR="██"
else
	BAR=""
fi

update
dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/brightness-full.png " ${BL}% $BAR "
