#!/usr/bin/env bash

blr=$(light -G)
declare -i bl=$(printf "%.0f" $blr)

case $1 in
	inc) light -A 5 ;;
	dec) light -U 5 ;;
esac

if [[ $bl -ge 100 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "██████████████████"
elif [[ $bl -ge 90 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "████████████████"
elif [[ $bl -ge 80 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "██████████████"
elif [[ $bl -ge 70 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "████████████"
elif [[ $bl -ge 60 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "██████████"
elif [[ $bl -ge 50 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "████████"
elif [[ $bl -ge 40 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "██████"
elif [[ $bl -ge 30 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "████"
elif [[ $bl -ge 20 ]]; then
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png "██"
else
	dunstify -r 1234 --raw_icon=$HOME/scrpic/brightness-full.png ""
fi

polybar-msg hook backlight 1

echo $bl
