#!/usr/bin/env bash

# with openrc use loginctl
#switch_user
#switch_user) dm-tool switch-to-greeter                    ;;

help () {
cat << 'EOB'
# NAME

__i3end__ - shutdown menu for i3wm

# SYNOPSIS

```
i3end l|e|s|h|r|x
i3end --help|-h
```

# OPTIONS

Run with no option to produce a rofi menu of options

`l`  
lock

`e`  
logout

`s`  
suspend

`h`  
hibernate

`r`  
reboot

`x`  
shutdown

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

OPT=${1}

[[ -z $OPT ]] && OPT=$(printf "%s\n" "l lock" "e logout" \
	"s suspend" "r reboot" "h hibernate" "x shutdown" | \
	i3menu --prompt "SHUTDOWN [<ESC> to cancel]" -c red -F | \
	awk '{print $1}')

[[ -z $OPT ]] && exit

case $OPT in
	l) lscr                                   ;;
	e) i3-msg exit                            ;;
	s) lscr && sleep 0.5 && $logind suspend   ;;
	h) lscr && sleep 0.5 && $logind hibernate ;;
	r) $logind reboot                         ;;
	x) $logind poweroff                       ;;
esac

exit 0
