#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue  4 Dec 15:23:43 GMT 2018

APP="$1"
WSP=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
[[ $USER_I3LAUNCH_WS == $WSP ]] || {
	$APP &>/dev/null &
	exit
}

MRK="$2"
MKS=$(i3-msg -t get_marks)
LF=$(xdotool getactivewindow)
POS=$(xdotool getactivewindow getwindowgeometry | grep Position | awk '{print $2}')
YP=${GEO#*,}
XP=${GEO%,*}
GEO=$(xdotool getactivewindow getwindowgeometry | grep Geometry | awk '{print $2}')
HGT=${GEO#*x}
WDT=${GEO%x*}

lmk3 () {
	$APP &>/dev/null &
	sleep 1
	i3-msg split h
	i3-msg layout tabbed
	i3-msg focus parent
	i3-msg mark _W3
	i3-msg "mark --add _sticky_3"
	i3-msg focus child
}

lmk1 () {
	i3-msg [con_mark="_W3"] focus
	$APP &>/dev/null &
	sleep .5
	i3-msg split toggle
	i3-msg layout tabbed
	i3-msg focus parent
	i3-msg mark _W1
	i3-msg "mark --add _sticky_1"
	i3-msg focus child
	i3-msg [con_mark="_W1"] resize set 492 402
}

lmk2 () {
	i3-msg [con_mark="_W1"] focus
	i3-msg split v
	$APP &>/dev/null &
	sleep .5
	i3-msg split h
	i3-msg layout tabbed
	i3-msg focus parent
	i3-msg mark _W2
	i3-msg "mark --add _sticky_2"
	i3-msg focus child
	i3-msg [con_mark="_W1"] resize set 492 402
}

lmk4 () {
	i3-msg [con_mark="_W3"] focus
	i3-msg split v
	$APP &>/dev/null &
	sleep .5
	i3-msg split h
	i3-msg layout tabbed
	i3-msg focus parent
	i3-msg mark _W4
	i3-msg "mark --add _sticky_4"
	i3-msg move up
	i3-msg move up
	i3-msg focus child
	i3-msg resize set height 150
	i3-msg [con_mark="_W3"] split h
}

main () {
	i3-msg [con_mark=$MRK] focus
	i3-msg focus child
	$APP &>/dev/null &
}

if [[ -z $MRK ]]; then
	$APP &>/dev/null &
elif [[ $MKS =~ "$MRK" ]]; then
	echo "mark $MRK exists, launching $APP" && main
else
	case $MRK in
		*3) echo "no $MRK, making $MRK" && lmk3 ;;
		*1) echo "no $MRK, making $MRK" && lmk1 ;;
		*2) echo "no $MRK, making $MRK" && lmk2 ;;
		*4) echo "no $MRK, making $MRK" && lmk4 ;;
	esac
fi

if [[ ${3} == 'fl' ]]; then
	sleep .5
	i3-msg [id="$LF"] focus
fi

echo $MKS
