#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue  4 Dec 15:23:43 GMT 2018

WSP=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
LF=$(xdotool getactivewindow)
#MKS=$(i3-msg -t get_marks)
SRCH=""

while true; do
	case $1 in
#		--toggle   | -t ) TOGG=1 ;;
		--exec     | -e ) EXEC="${2:-}" ; shift ;;
		--class    | -c ) CLSS="${2:-}" ; shift ;;
		--instance | -i ) INST="${2:-}" ; shift ;;
		--name     | -n ) NAME="${2:-}" ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -n $INST ]] && ASCH="$INST" ISCH="instance" SRCH="--classname"
[[ -n $CLSS ]] && ASCH="$CLSS" ISCH="class"    SRCH="--class"
[[ -n $NAME ]] && ASCH="$NAME" ISCH="title"    SRCH="--name"
PID=$(xdotool search $SRCH "$ASCH")
[[ -n $PID ]] && i3-msg -q [$ISCH=\"$ASCH\"] focus || {
	[[ -n $EXEC ]] && $EXEC &>/dev/null &
	exit
	}
#HID=$(wmctrl -lx | awk -v SRCH="$ASCH" '$0 ~ SRCH {print $2}')
#[[ -n $TOGG ]] && {
#	[[ $HID == "-1" ]] && {
#		i3-msg [$ISCH="$ASCH"] scratchpad show
#		i3-msg [$ISCH="$ASCH"] focus
#		MRK=$(i3gm)
#		[[ -n $MRK ]] && i3quad -m ${MRK/_/}
#		} || i3-msg [$ISCH="$ASCH"] move scratchpad
#}
