#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__i3light__ - control backlight for i3

# SYNOPSIS

```
i3light nm|inc|dec
i3light --help|-h
```
EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z $1 ]] && help "Nothing to do!"

nightmode () {
	NMFL=$USER_TMP_DIR/nightmode
	[[ -f $NMFL ]] || echo off > $NMFL
	CRMD=$(cat $NMFL)

	if [[ $CRMD == "off" ]]; then
		redshift -P -O 3700
		echo on > $NMFL
	elif [[ $CRMD == "on" ]]; then
		redshift -x
		echo off > $NMFL
	fi
}

case $1 in
	nm)  nightmode          ;;
	inc) xbacklight -inc 5% ;;
	dec) xbacklight -dec 5% ;;
#	inc) light -A 5         ;;
#	dec) light -U 5         ;;
esac

BLR=$(light -G)
BL=${BLR%.*}

update () {
	NM=$(cat $USER_TMP_DIR/nightmode)
	_NM="%{T1} %{T-}"
	[[ $NM == "on" ]] && _NM="%{T1} %{T-}"
	_MS="%{A1:i3light nm:}%{A4:i3light inc:}%{A5:i3light dec:}${_NM}${BL}%{A}%{A}%{A}"
	pbcat --module i3light "${_MS}"
}

BBL=$(echo "(2*$BL)/10" | bc)
BAR="$(printf '█%.0s' $(seq 1 $BBL))"

update
dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/brightness-full.png " ${BL}% $BAR "
