#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sun 27 Jan 13:52:24 GMT 2019
source $HOME/.config/user-dirs.dirs

mpris=$(pidof spotify)
box=$(pidof rhythmbox)
mpv=$(pidof mpv)

if [[ -n $mpv ]]; then
	echo mpv
elif [[ -n $box ]]; then
	echo box
elif [[ -n $mpris ]]; then
	echo spotify
else
	echo mpd
fi
