#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sun 27 Jan 13:52:24 GMT 2019
#source $HOME/.config/user-dirs.dirs

spo=$(pidof spotify)
box=$(pidof rhythmbox)
mpv=$(pidof mpv)

CUR=mpmpd
[[ -n $mpv ]] && CUR=mpmpv
[[ -n $box ]] && CUR=mpgui
[[ -n $spo ]] && CUR=mpgui

echo $CUR
