#!/usr/bin/env bash

player=$($HOME/scr/i3mediaplaying)

case $1 in
	togg)
	[[ $player == "mpv" ]] && echo "cycle pause" > $HOME/mp_fifo
	[[ $player == "spotify" ]] && playerctl play-pause
	[[ $player == "box" ]] && playerctl play-pause
	[[ $player == "mpd" ]] && mpc toggle && dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Toggle Playback" "$(mpc current)"
	;;
	next)
	[[ $player == "mpv" ]] && echo "seek 10" > $HOME/mp_fifo
	[[ $player == "spotify" ]] && playerctl next
	[[ $player == "box" ]] && playerctl next
	[[ $player == "mpd" ]] && mpc next && dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Next Song" "$(mpc current)"
	;;
	prev)
	[[ $player == "mpv" ]] && echo "seek -10" > $HOME/mp_fifo
	[[ $player == "spotify" ]] && playerctl next
	[[ $player == "box" ]] && playerctl next
	[[ $player == "mpd" ]] && mpc prev && dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Previous Song" "$(mpc current)"
	;;
	stop)
	[[ $player == "mpv" ]] && kill $(pidof mpv)
	[[ $player == "spotify" ]] && kill $(pidof spotify)
	[[ $player == "box" ]] && kill $(pidof spotify)
	[[ $player == "mpd" ]] && mpc stop && dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Stopped Playing" "$(mpc current)"
	;;
esac

polybar-msg hook media 1
