#!/usr/bin/env bash

CRPL=$(i3wplyr)
BLDR=$HOME/scr/pb

update () {
	_P="%{A1:i3media prev:}%{T1}%{T-}%{A}"
	_N="%{A1:i3media next:}%{T1}%{T-}%{A}"
	_T="%{A1:i3media togg:}%{T1}%{T-}%{A}"
	_S="%{A1:i3media stop:}%{T1}%{T-}%{A}"
	_CTRLS=" $_P $_T $_S $_N"
	_NP="%{A1:i3media togg:}$(${BLDR}/${CRPL})%{A}"
	pbcat -m i3media -v "$_NP$_CTRLS"
}

case $1 in
	togg)
		[[ $CRPL == "mpmpv" ]] && echo "cycle pause" > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl play-pause
		[[ $CRPL == "mpmpd" ]] && mpc toggle && \
			dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Toggle Playback" "$(mpc current)"
		;;
	next)
		[[ $CRPL == "mpmpv" ]] && echo "seek 10"     > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl next
		[[ $CRPL == "mpmpd" ]] && mpc next && \
			dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Next Song" "$(mpc current)"
		;;
	prev)
		[[ $CRPL == "mpmpv" ]] && echo "seek -10"    > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl previous
		[[ $CRPL == "mpmpd" ]] && mpc prev && \
			dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Previous Song" "$(mpc current)"
		;;
	stop)
		[[ $CRPL == "mpmpv" ]] && kill $(pidof mpv)
		[[ $CRPL == "mpgui" ]] && kill $(pidof spotify) && kill $(pidof rhythmbox)
		[[ $CRPL == "mpmpd" ]] && mpc stop && \
			dunstify -r 1234 --raw_icon=$HOME/cover.jpg "Stopped Playing" "$(mpc current)"
		;;
esac

update
