#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 16 Mar 20:08:40 GMT 2019

prompt="${1}"
mouseX=$(xdotool getmouselocation | awk '{print $1}')
mouseY=$(xdotool getmouselocation | awk '{print $2}')
monitor=$(xdotool getmouselocation | awk '{print $3}')

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color15' | awk '{print $NF}')
accent=$(xrdb -query | grep '*color5' | awk '{print $NF}')
font=$(xrdb -query | grep 'URxvt.font' | awk '{print $NF}')
font=${font#*:}
font=${font%:*}
format="-fn "${font}:size=15" -nb "$accent" -nf "$black" -sf "$accent" -sb "$white" -l 20"
location="-xoffset ${mouseX:2} -yoffset ${mouseY:2}"

right-click () {
	rofi -dmenu -monitor ${monitor:7} -location 1 $location -lines 10 -p "${prompt}"
#	dmenu $format $location -p "${prompt}" -w 500
}

menu () {
	rofi -dmenu -monitor ${monitor:7} -location 0 -p "${prompt}"
#	dmenu $format $location -p "${prompt}" -w 500
}

if [[ ${prompt} == "-run" ]]; then
	dmenu_run $format
else
	menu
fi
