#!/usr/bin/env bash

CRPL=$(i3wplyr)
BLDR=$HOME/scr/pb

help () {
cat << 'EOB'
# i3media
- control whatever media player is currently active,
uses `i3wplyr` to decide the hierarchy of which player
to control

## Usage
```
i3media togg|next|prev|stop
i3media --help|-h
```

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z $1 ]] && help "Nothing to do!"

update () {
	_P="%{A1:i3media prev:}%{T1}%{T-}%{A}"
	_N="%{A1:i3media next:}%{T1}%{T-}%{A}"
	_T="%{A1:i3media togg:}%{T1}%{T-}%{A}"
	_S="%{A1:i3media stop:}%{T1}%{T-}%{A}"
	_CTRLS=" $_P $_T $_S $_N"
	_NP="%{A1:i3media togg:}$(${BLDR}/${CRPL})%{A}"
	pbcat --module i3media "$_NP$_CTRLS"
}

case $1 in
	togg)
		[[ $CRPL == "mpmpv" ]] && echo "cycle pause" > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl play-pause
		[[ $CRPL == "mpmpd" ]] && mpc toggle && \
			dunstify -r 1234 --raw_icon=$USER_TMP_DIR/cover.jpg "Toggle Playback" "$(mpc current)"
		;;
	next)
		[[ $CRPL == "mpmpv" ]] && echo "seek 10"     > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl next
		[[ $CRPL == "mpmpd" ]] && mpc next && \
			dunstify -r 1234 --raw_icon=$USER_TMP_DIR/cover.jpg "Next Song" "$(mpc current)"
		;;
	prev)
		[[ $CRPL == "mpmpv" ]] && echo "seek -10"    > $USER_TMP_DIR/mppipe
		[[ $CRPL == "mpgui" ]] && playerctl previous
		[[ $CRPL == "mpmpd" ]] && mpc prev && \
			dunstify -r 1234 --raw_icon=$USER_TMP_DIR/cover.jpg "Previous Song" "$(mpc current)"
		;;
	stop)
		[[ $CRPL == "mpmpv" ]] && kill $(pidof mpv)
		[[ $CRPL == "mpgui" ]] && kill $(pidof spotify) && kill $(pidof rhythmbox)
		[[ $CRPL == "mpmpd" ]] && mpc stop && \
			dunstify -r 1234 --raw_icon=$USER_TMP_DIR/cover.jpg "Stopped Playing" "$(mpc current)"
		;;
esac

update
