#!/usr/bin/env bash

DRN=$1
cd $HOME
i3-msg -t get_tree > get_tree
sed 's/},{/\n/g' get_tree > tree_new
FCS=$(cat tree_new | grep '"focused":true')
TBD=$(cat tree_new | grep 'tabbed')
echo $TBD

GEO=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry' | awk '{print $NF}'
WDT=${GEO%x*}
HGT=${GEO#*x}
IGO=\"width\":${WDT},\"height\":${HGT}

if [[ $TBD =~ $IGO ]]; then
	i3-msg "focus parent; move $DRN; focus child"
else
	i3-msg move $DRN
fi

rm get_tree tree_new
