#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue  4 Dec 15:23:43 GMT 2018

I3="i3-msg -q"
PID=$(pidof i3)
I3QTMP=$USER_TMP_DIR/i3quadwindows
[[ -n $PID ]] && WSP=$(i3-msg -t get_workspaces | \
	jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
[[ -n $PID ]] && MKS=$(i3-msg -t get_marks)
XID=$(xdotool getactivewindow)
XID=${XID%% *}
[[ $USER_I3LAUNCH_WS == $WSP ]] || exit

help () {
cat << 'EOB'
# NAME

__i3quad__ - my i3 layout launcher, inspired by budlabs' `i3fyra`

# SYNOPSIS

```
i3quad [--fullscreen|-F|--focus|-f|--move|-m] <con>
i3quad --resize|-r '<con> +|-|%|<integer|*> +|-|%|<integer|*>'
i3quad --tile|-t
i3quad --help|-h
```

# OPTIONS

`--move|-m <con>`  
Move window to mark `_W<con>`

`--focus|-f <con>`  
Move window to mark `_W<con>`

`--resize|-r '<con> +|-|%|<integer|*> +|-|%|<integer|*>'`  
Resize/set container `_W<con>`'s dimensions. First argument
is the target container, second is the width increment/value,
third is the height increment/value. Eg.

+ `i3quad -r '1 +20 -40'`  
Increases width of container 1 by 20 px or 20 ppt.  
Decreases height of container 1 by 40 px or 40 ppt.
+ `i3quad -r '2 %20 +40'`  
Sets width of container 2 to 20% of screen.  
increases height of container 2 by 40 px or 40 ppt.
+ `i3quad -r '3 20 40'`  
Sets width of container 3 to 20 pixels.  
Sets height of container 3 to 20 pixels.
+ `i3quad -r '4 * -40'`  
Doesn't change width of container 4.  
Decreases height of container 4 by 40 px or 40 ppt.

`--fullscreen|-F <con>`  
Toggle mark `_W<con>` fullscreen

`--tile|-t`  
Tile currently focussed window

`--help|-h`  
Print this help

# THE LAYOUT

```
			┌┈┈┈┈┈┈┈┈┬┈┈┈┈┈┐
			│  _W4   │ _W1 │▒
			├┈┈┈┈┈┈┈┈┼┈┈┈┈┈┤▒
			│  _W3   │ _W2 │▒
			│        │     │▒
			└┈┈┈┈┈┈┈┈┴┈┈┈┈┈┘▒
			  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
```

# IN PROGRESS

`--focus-last|-l`  
Focus last focussed window moving launched window to <con>

EOB
echo "$1"
exit
}

history () {
	CHK=$(cat $I3QTMP | grep "$XID")
	[[ -z $CHK ]] && echo "$XID    ${1}" >> $I3QTMP
}

CMK3 () {
	$I3 floating disable
	$I3 split h
	$I3 layout tabbed
	$I3 focus parent
	$I3 mark _W3
	$I3 focus child
	$I3 "mark --add _3"
}
CMK1 () {
	$I3 floating disable
	$I3 move to mark _W3
	$I3 [con_mark="_W3"] focus
	$I3 focus child
	$I3 move up
	$I3 move right
	$I3 split v
	$I3 layout tabbed
	$I3 focus parent
	$I3 mark _W1
	$I3 focus child
	$I3 "mark --add _1"
	$I3 [con_mark="_W1"] resize set 492 402
}
CMK2 () {
	$I3 floating disable
	$I3 move to mark _W1
	$I3 [con_mark="_W1"] focus
	$I3 split v
	$I3 focus child
	$I3 move down
	$I3 split h
	$I3 split v
	$I3 layout tabbed
	$I3 focus parent
	$I3 mark _W2
	$I3 focus child
	$I3 "mark --add _2"
	$I3 [con_mark="_W1"] resize set 492 402
}
CMK4 () {
	$I3 floating disable
	$I3 move to mark _W3
	$I3 [con_mark="_W3"] focus
	$I3 split v
	$I3 focus child
	$I3 move up
	$I3 split h
	$I3 layout tabbed
	$I3 focus parent
	$I3 mark _W4
	$I3 focus child
	$I3 "mark --add _4"
	$I3 resize set height 150
	$I3 [con_mark="_W3"] split h
}

O_resize () {
	MRK=_W${1%% *} CMD="i3-msg [con_mark=$MRK] resize "
	W=${1% *}
	W=${W#* }  WD=${W:0:1}
	H=${1##* } HD=${H:0:1}

	if   [[ $WD == "+" ]]; then WDT="${CMD}grow width ${W/+/} px or ${W/+/} ppt"
	elif [[ $WD == "-" ]]; then WDT="${CMD}shrink width ${W/-/} px or ${W/-/} ppt"
	elif [[ $WD == "%" ]]; then WDT="${CMD}set width ${W/\%/} ppt"
	elif [[ $WD == "*" ]]; then WDT=""
	else                        WDT="${CMD}set width  $W"  ; fi

	if   [[ $HD == "+" ]]; then HDT="${CMD}grow height ${H/+/} px or ${H/+/} ppt"
	elif [[ $HD == "-" ]]; then HDT="${CMD}shrink height ${H/-/} px or ${H/-/} ppt"
	elif [[ $HD == "%" ]]; then HDT="${CMD}set height ${H/\%/} ppt"
	elif [[ $HD == "*" ]]; then HDT=""
	else                        HDT="${CMD}set height $H"  ; fi

	eval "$(echo $WDT)"
	eval "$(echo $HDT)"
	exit
}

EXISTS () {
	$I3 floating disable
	$I3 move to mark $MRK
	$I3 [con_mark="$MRK"] focus
	$I3 focus child
	[[ -z $(i3gm) ]] && $I3 "mark --add _${MRK/_W/}"
	history "$MRK"
	exit
}

O_tile       () { $I3 floating disable && history "_tiled" ; exit ; }
O_fullscreen () { $I3 "[con_mark=_W${1}] focus; fullscreen toggle; focus child" ; exit ; }
O_focus      () { $I3 "[con_mark=_W${1}] focus; focus child" ; exit ; }

while true; do
	case $1 in
		--move       | -m ) MRK="_W${2:-}" ; shift ;;
		--fullscreen | -F ) O_fullscreen  "${2:-}" ;;
		--focus      | -f ) O_focus       "${2:-}" ;;
		--resize     | -r ) O_resize      "${2:-}" ;;
		--tile       | -t ) O_tile ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done


[[ $MKS =~ "$MRK" ]] && EXISTS || {
	notify-send "no $MRK, making $MRK"
	CMK${MRK/_W/}
	history "$MRK"
}

[[ -n $FL ]] && sleep .5 && $I3 [id="$LF"] focus
