#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Tue 29 Jan 11:32:27 GMT 2019

OP=${1}
NSZE=${2}

WDTH=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry:' | sed 's/x/\ /g' | awk '{print $2}')
HGHT=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry:' | sed 's/x/\ /g' | awk '{print $3}')

XP=$(xdotool getactivewindow getwindowgeometry | grep 'Position:' | sed 's/,/\ /g' | awk '{print $2}')
YP=$(xdotool getactivewindow getwindowgeometry | grep 'Position:' | sed 's/,/\ /g' | awk '{print $3}')

XM=$(xdotool getdisplaygeometry | awk '{print $1}')
YM=$(xdotool getdisplaygeometry | awk '{print $2}')

XM2=$(expr $XM / 2)
YM2=$(expr $YM / 2)

if [[ $XP -lt $XM2 ]] && [[ $YP -lt $YM2 ]]; then
	echo 'grab bottomright'
	i3-msg resize ${OP} right	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} down	${NSZE} px or ${NSZE} ppt
elif [[ $XP -lt $XM2 ]] && [[ $YP -gt $YM2 ]]; then
	echo 'grab topright'
	i3-msg resize ${OP} right	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} up		${NSZE} px or ${NSZE} ppt
elif [[ $(expr $XP + $WDTH) -lt $XM2 ]] && [[ $(expr $YP + $HGHT) -gt $YM2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${OP} right	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} up		${NSZE} px or ${NSZE} ppt
elif [[ $(expr $XP + $WDTH) -gt $XM2 ]] && [[ $(expr $YP + $HGHT) -gt $YM2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${OP} left	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} up		${NSZE} px or ${NSZE} ppt
elif [[ $XP -gt $XM2 ]] && [[ $YP -lt $YM2 ]]; then
	echo 'grab bottomleft'
	i3-msg resize ${OP} left ${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} down ${NSZE} px or ${NSZE} ppt
elif [[ $XP -gt $XM2 ]] && [[ $YP -gt $YM2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${OP} left	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} up		${NSZE} px or ${NSZE} ppt
else
	echo 'grab bottomright'
	i3-msg resize ${OP} right	${NSZE} px or ${NSZE} ppt
	i3-msg resize ${OP} down	${NSZE} px or ${NSZE} ppt
fi

#echo "$WDTH $HGHT"
#echo "$XP $YP"
#echo "$XM $YM"
#echo "$XM2 $YM2"
