#!/usr/bin/env bash

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

OPT=$(echo "
lock
logout
switch_user
suspend
hibernate
reboot
shutdown" | \
	i3menu -c red -w 500 -p "SHUTDOWN [<ESC> to cancel]")

[[ -z $OPT ]] && exit

case "$OPT" in
	lock)        lockscreen                                   ;;
	logout)      i3-msg exit                                  ;;
	switch_user) dm-tool switch-to-greeter                    ;;
	suspend)     lockscreen && sleep 0.5 && $logind suspend   ;;
	hibernate)   lockscreen && sleep 0.5 && $logind hibernate ;;
	reboot)      $logind reboot                               ;;
	shutdown)    $logind poweroff                             ;;
esac

exit 0
