#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__i3vol__ - control volume for i3

# SYNOPSIS

```
i3vol mute|inc|dec
i3vol --help|-h
```

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h )
			help | \
				sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
				sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

[[ -z $1 ]] && help "Nothing to do!"

case $1 in
	inc)  pactl set-sink-volume 0 +2%  ;;
	dec)  pactl set-sink-volume 0 -2%  ;;
	mute) pactl set-sink-mute 0 toggle ;;
esac

RVL=$(amixer get Master | tail -n 1 | grep %)
VOL=${RVL%\%*}
VOL=${VOL#*[}
STT=${RVL%]*}
STT=${STT##*[}
ICN="%{T1}%{T-}"

update () {
	_VOL=$VOL
	((VOL==0))  && ICN="%{T1}%{T-}"
	((VOL<=30)) && ICN="%{T1}%{T-}"
	((VOL>=30)) && ICN="%{T1}%{T-}"
	[[ $STT == "off" ]] && ICN="%{T1}%{T-}" REV="%{R}" _VOL=" ---" ALT='!'
	FSTR="${REV} %{A4:i3vol inc:}%{A5:i3vol dec:}%{A1:i3vol mute:}${ICN} ${_VOL}%{A}%{A}%{A}$REV "
	pbcat --module i3vol "$FSTR"
}

#BVL=$(echo "(2*$VOL)/10" | bc)
#BAR="$(printf '█%.0s' $(seq 1 $BVL))"

#dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/speaker-full.png " ${VOL}% $BAR "
update
echo $VOL$ALT > $USER_TMP_DIR/XOBVOL
