#!/usr/bin/env bash

case $1 in
	inc) pactl set-sink-volume 0 +2% ;;
	dec) pactl set-sink-volume 0 -2% ;;
	mute) pactl set-sink-mute 0 toggle ;;
esac

volraw=$(amixer get Master|tail -1|grep -oh "\w*%\w*")
stat=$(amixer get Master|tail -1|awk '{print $NF}')
VOL=${volraw:0:-1}

if [[ $VOL -ge 100 ]]; then
	BAR="████████████████████"
elif [[ $VOL -ge 90 ]]; then                                       
	BAR="██████████████████"
elif [[ $VOL -ge 80 ]]; then                                       
	BAR="████████████████"
elif [[ $VOL -ge 70 ]]; then                                       
	BAR="██████████████"
elif [[ $VOL -ge 60 ]]; then                                       
	BAR="████████████"
elif [[ $VOL -ge 50 ]]; then                                       
	BAR="██████████"
elif [[ $VOL -ge 40 ]]; then                                       
	BAR="████████"
elif [[ $VOL -ge 30 ]]; then                                       
	BAR="██████"
elif [[ $VOL -ge 20 ]]; then                                       
	BAR="████"
elif [[ $VOL -ge 10 ]]; then                                       
	BAR="██"
elif [[ $VOL -lt 10 ]]; then                                       
	BAR=""
else
	BAR="MUTED"
fi

dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/speaker-full.png " ${VOL}% $BAR "
