#!/usr/bin/env bash

case $1 in
	inc)  pactl set-sink-volume 0 +2%  ;;
	dec)  pactl set-sink-volume 0 -2%  ;;
	mute) pactl set-sink-mute 0 toggle ;;
esac

RVL=$(amixer get Master | tail -n 1 | grep %)
VOL=${RVL%\%*}
VOL=${VOL#*[}
STT=${RVL%]*}
STT=${STT##*[}
ICN="%{T1}%{T-}"

update () {
	_VOL=$VOL
	[[ $VOL == 0 ]]     && ICN="%{T1}%{T-}"
	[[ $VOL -le 30 ]]   && ICN="%{T1}%{T-}"
	[[ $VOL -ge 30 ]]   && ICN="%{T1}%{T-}"
	[[ $STT == "off" ]] && ICN="%{T1}%{T-}" REV="%{R}" _VOL=" ---"
	FSTR="${REV} \
%{A4:i3vol inc:}%{A5:i3vol dec:}\
%{A1:i3vol mute:}${ICN} ${_VOL}%{A}%{A}%{A} "
	pbcat -m i3vol -v "$FSTR"
}

BVL=$(echo "(2*$VOL)/10" | bc)
BAR="$(printf '█%.0s' $(seq 1 $BVL))"

dunstify -r 1234 --raw_icon=${USER_SCR_DIR}pic/speaker-full.png " ${VOL}% $BAR "
update
