#!/bin/bash

# OA: Gavin Vales
# CREATED: Sat  6 Jul 00:50:41 BST 2019

WDIR="$HOME/pic/walls"
WHT="${WDIR}/white.jpg"
NORM="${WDIR}/normal"
BLUR="${WDIR}/blur"
COLS="${WDIR}/cols"
NWFD="$NORM"
CURR="${WDIR}/current"
CRLN="$(readlink -f ${WDIR}/current)"
HIST="${WDIR}/.history"
MONDIM=$(xdpyinfo | grep dimensions: | awk '{print $2}')
MX=${MONDIM%x*}
MY=${MONDIM#*x}

help () {
cat << 'EOB'
    -h -- print this help
    -w -- wallpaper to set. Can be picture or hex color (requires white.jpg in 
              i3wallpaper's directory)
    -t -- color to tint wallpaper with
    -a -- add walls contained in specified dir to i3wallpaper's directory
    -l -- open wallpapers in i3wallpaper's directory in sxiv
    -b -- toggle blur
EOB
}

add-wall () {
	SRC="$1"
	TRG="${1##*/}"
	TRG="${TRG%.*}"
	TRG="${TRG/1920x1080/}"
	TRG="${TRG/,/}"
	TRG="${TRG/,/}"
	TRG="${TRG/,/}"
	TRG="${TRG/ /}"
	TRG="${TRG/ /}"
	TRG="${TRG/ /}"
	TRG="${TRG/ /}"
	TRG="${TRG/ /}"
	echo "
	TRG=$TRG
	SRC=$SRC"
	convert "${SRC}" -resize "${MX}x${MY}^" -gravity center -extent "${MX}x${MY}" "${NORM}/${TRG}"
	convert "${NORM}/${TRG}" -blur 0x4 "${BLUR}/${TRG}"
	WPP="$TRG"
}

add () {
	cd "$1"
	IFS=$'\n'
	for i in $(find -type f); do
		SRC="$i"
		SRC="${SRC#*/}"
		TRG="${i#*/}"
		TRG="${TRG%.*}"
		echo "
	TRG=$TRG
	SRC=$SRC"
		[[ ! -f ${NORM}/${TRG} ]] && convert "${SRC}" \
			-resize "${MX}x${MY}^" \
			-gravity center \
			-extent "${MX}x${MY}" "${NORM}/${TRG}"
		[[ ! -f ${BLUR}/${TRG} ]] && convert "${NORM}/${TRG}" \
			-blur 0x4 "${BLUR}/${TRG}"
	done
}

tint () {
	CRTNT="${NORM}/${CRLN##*/}-${TNT/\#/}"
	[[ ! -f $CRTNT ]] && {
		convert "$CURR" -fill "${TNT}" -tint 100 "$CRTNT"
		convert "${CRTNT}" -blur 0x4 "${CRTNT/normal/blur}"
	}
	ln -sf "$CRTNT" $CURR
	CRLN=$(readlink -f $CURR)
}

colour () {
	[[ ! -f ${COLS}/${WPP/\#/} ]] && \
		convert $WHT -fill $WPP \
		-draw 'color 0,0 replace' "${COLS}/${WPP/\#/}"
	ln -sf "${COLS}/${WPP/\#/}" $CURR
	set-wall
}

change-current () {
	ln -sf "${NWFD}/${WPP}" $CURR
	CRLN="$(readlink -f ${WDIR}/current)"
}

set-wall () {
	feh --bg-center $CURR
	echo "SETTING WALLPAPER TO ${CRLN##*/}"
}

list () {
	cd $NORM
	$HOME/scr/openimage "$(ls | head -n 1)"
}

history () {
	[[ ! -f $HIST ]] && touch $HIST
	sed -e "/"${1}"/d" -i $HIST
	echo -e "${1}\n$(cat $HIST)" > $HIST
}

while getopts :w:t:a:lbh opts; do
	case $opts in
		w) WPP="${OPTARG}" WPPACTUAL="${OPTARG}" ;;
		t) TNT="${OPTARG}" ;;
		a) ADD="${OPTARG}" ;;
		l) list && exit    ;;
		b) BLURT=TRUE      ;;
		h) help && exit    ;;
	esac
done

[[ -n $ADD ]] && add "$ADD" && exit

if [[ -n $WPP ]]; then
	[[ $WPP =~ "#" ]] \
		&& echo "SETTING DESKTOP COLOR TO $WPP" && colour && exit
	[[ $WPP == "RANDOM" ]] \
		&& echo "SETTING RANDOM WALLPAPER" && WPP=$(ls $NORM | shuf -n 1)
	[[ $WPP == "PREV" ]] && {
			echo "SETTING PREVIOUS WALLPAPER IN HISTORY"
			WPP="$(sed -n "/"${CRLN##*/}"/{g;1!p;};h" $HIST)"
			[[ -z $WPP ]] && WPP="$(tail -n 1 $HIST)"
		}
	[[ $WPP == "NEXT" ]] && {
			echo "SETTING NEXT WALLPAPER IN HISTORY" 
			WPP="$(sed -n "/"${CRLN##*/}"/{n;p;}" $HIST)"
			[[ -z $WPP ]] && WPP="$(head -n 1 $HIST)"
		}
	[[ ! -f $NORM/$WPP ]] \
		&& echo "WALLPAPER NOT IN WALLS DIRECTORY" && add-wall "$WPP"
	change-current
fi

[[ $BLURT == "TRUE" ]] && {
	CRFD=${CRLN%/*}
	CRFD=${CRFD##*/}
	[[ ${CRFD} == "normal" ]] \
		&& ln -sf  ${CRLN/\/normal\//\/blur\/} $CURR && NWFD="$BLUR" \
		|| ln -sf  ${CRLN/\/blur\//\/normal\/} $CURR
	echo "TOGGLING BLUR"
}

[[ -n $TNT ]] && echo "TINTING WALLPAPER $WPP TO COLOR $TNT" && tint
set-wall
[[ $WPPACTUAL != "NEXT" ]] && history ${CRLN##*/}
