#!/usr/bin/env bash

bkd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
grn=$(xrdb -query | grep '*color2' | awk '{print $NF}')
ylw=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
wtd=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blu=$(xrdb -query | grep '*color4' | awk '{print $NF}')

t="80"

B="$bkd$t"  # blank
C="$wtd$t"  # clear ish
D="$blu$t"  # default
T="${wtd}ff"  # text
W="$red$t"  # wrong
V="$grn$t"  # verifying

i3lock \
--image=$HOME/.config/wall.png \
--insidevercolor=$V \
--ringvercolor=$V \
\
--insidewrongcolor=$W \
--ringwrongcolor=$W \
\
--insidecolor=$D \
--ringcolor=$D \
--linecolor=$D \
--separatorcolor=$D \
\
--verifcolor=$V \
--wrongcolor=$W \
--timecolor=$T \
--datecolor=$T \
--layoutcolor=$T \
--keyhlcolor=$W \
--bshlcolor=$W \
\
--screen 0 \
--blur 5 \
--clock \
--indicator \
--timestr="%H:%M:%S" \
--datestr="%A, %m %Y" \
--keylayout 2 \
