#!/usr/bin/env bash

IMG=$(readlink -f ~/pic/walls/current)
bg0=$($HOME/scr/themer -v "bg0 ") fg0=$($HOME/scr/themer -v "fg0 ")
acc=$($HOME/scr/themer -v "acc ") grn=$($HOME/scr/themer -v "grn ")
ylw=$($HOME/scr/themer -v "ylw ") red=$($HOME/scr/themer -v "red ")
SCR=$(xdpyinfo | grep 'name of display:' | awk '{print $2}')
SCR=${SCR/:/}
RES=$(xdpyinfo  | grep 'dimensions:' | awk '{print $2}')
FNT=$($HOME/scr/themer -v "font ")
XP=1 YP=90 XRES=${RES%x*} YRES=${RES#*x}
X=$(echo "(${XRES}*${XP})/100" | bc) Y=$(echo "(${YRES}*${YP})/100" | bc)
t="ff"

B="${bg0}${t}"  # blank
C="${fg0}${t}"  # clear ish
D="${acc}00"    # default
T="${fg0}${t}"  # text
W="${red}${t}"  # wrong
V="${grn}${t}"  # verifying

#--indicator \
i3lock \
	-f \
	-p default \
	--bar-indicator \
	--bar-width=5 \
	--bar-color=$D \
	--bar-direction=0 \
	--bar-max-height=150 \
	--bar-orientation=horizontal \
	--indpos="$X:$Y" \
	--image=${IMG/\/normal\//\/blur\/} \
	--insidevercolor=$V \
	--ringvercolor=$V \
	\
	--insidewrongcolor=$W \
	--ringwrongcolor=$W \
	\
	--insidecolor=$D \
	--ringcolor=$D \
	--linecolor=$D \
	--separatorcolor=$D \
	\
	--verifcolor=$V \
	--wrongcolor=$W \
	--timecolor=$T \
	--datecolor=$T \
	--layoutcolor=$T \
	--keyhlcolor=$W \
	--bshlcolor=$W \
	\
	--verif-align=1 \
	--wrong-align=1 \
	--time-align=1 \
	--date-align=1 \
	--layout-align=1 \
	--verif-font=$FNT \
	--wrong-font=$FNT \
	--time-font=$FNT \
	--date-font=$FNT \
	--layout-font=$FNT \
	--verifsize=75 \
	--wrongsize=75 \
	--timesize=75 \
	--datesize=30 \
	--layoutsize=25 \
	\
	--radius 120 \
	--screen $SCR \
	--blur 5 \
	--clock \
	--timestr="%H:%M:%S" \
	--datestr="%A, %m %Y" \
	--keylayout 2 &>/dev/null &
