#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__lscr__ - i3lock-color wrapper

# SYNOPSIS

```
lscr
lscr --help|-h
```
EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

PID=$(pidof i3lock)
IMG=$(readlink -f $XDG_PICTURES_DIR/gwc/current)
bg0=$(themer -v "bg0 ") fg0=$(themer -v "acb ") acc=$(themer -v "acc ")
grn=$(themer -v "grn ") ylw=$(themer -v "ylw ") red=$(themer -v "red ")
SCR=$(xdpyinfo | grep 'name of display:' | awk '{print $2}')
SCR=${SCR/:/}
RES=$(xdpyinfo  | grep 'dimensions:' | awk '{print $2}')
FNT=$(themer -v "font ")
XP=$(themer -v "ltimex") YP=$(themer -v "ltimey")
XRES=${RES%x*} YRES=${RES#*x}
X=$(echo "(${XRES}*${XP})/100" | bc)
Y=$(echo "(${YRES}*${YP})/100" | bc)
t="ff"

B="${bg0}${t}"  # blank
C="${fg0}${t}"  # clear ish
D="${acc}00"    # default
T="${fg0}${t}"  # text
W="${red}${t}"  # wrong
V="${grn}${t}"  # verifying

#--indicator \
[[ -z $PID ]] && \
i3lock \
	-f \
	-p default \
	--bar-indicator \
	--bar-width=5 \
	--bar-color=$D \
	--bar-direction=0 \
	--bar-max-height=150 \
	--bar-orientation=horizontal \
	--indpos="$X:$Y" \
	--image=${IMG/\/normal\//\/blur\/} \
	--insidevercolor=$V \
	--ringvercolor=$V \
	\
	--insidewrongcolor=$W \
	--ringwrongcolor=$W \
	\
	--insidecolor=$D \
	--ringcolor=$D \
	--linecolor=$D \
	--separatorcolor=$D \
	\
	--verifcolor=$V \
	--wrongcolor=$W \
	--timecolor=$T \
	--datecolor=$T \
	--layoutcolor=$T \
	--keyhlcolor=$W \
	--bshlcolor=$W \
	\
	--verif-align=1 \
	--wrong-align=1 \
	--time-align=1 \
	--date-align=1 \
	--layout-align=1 \
	--verif-font=$FNT \
	--wrong-font=$FNT \
	--time-font=$FNT \
	--date-font=$FNT \
	--layout-font=$FNT \
	--verifsize=75 \
	--wrongsize=75 \
	--timesize=75 \
	--datesize=30 \
	--layoutsize=25 \
	\
	--radius 120 \
	--screen $SCR \
	--blur 5 \
	--clock \
	--timestr="%H:%M:%S" \
	--datestr="%A, %m %Y" \
	--keylayout 2 &>/dev/null &
