#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon  7 Oct 23:04:04 BST 2019
# source /home/gavarch/.config/user-dirs.dirs

SDR=${USER_SCR_DIR}
MANDIR=/usr/share/man/man1

help () {
cat << 'EOB'
# NAME

__manner__ - generates man pages for scripts

# SYNOPSIS

```
manner [--directory|-d <directory>] [--install|-i copy|link]
       [--delete|-D]
manner --script|-s <script>
manner --help|-h
```

# DEPENDENCIES

```
pandoc
```

# OPTIONS

`--directory|-d <directory>`  
Change target directory

`--delete|-D`  
Delete all occurences of your scripts' installed manpages

`--script|-s <script>`  
Call specified `<script>` with `--help` flag, and convert
the output to a man page with `pandoc -s -t man`.

`--install|-i copy|link`  
Install all the manpages in `<directory>`man to
`/usr/share/man/man1` if they do not already exist.  
Argument to this option determines whether the scripts
are copied or linked.

`--help|-h`  
Print this help

# DESCRIPTION

All my bash scripts that have a help function are just
called with the `--help` flag and the output piped to
`pandoc -s -t man`, and that output redirected to the
directory `<directory>`man. The default directory is
`$HOME/scr`, so the resulting manpages will be
redirected to the appropriate file in `$HOME/scrman`.

Note that this only works because all my help functions
are written in markdown. All precode is converted to bold
text.

The `--script` flag can be used to automatically pipe the
output of the specified script to a man page.

EOB
exit
}

O_delete () { ls ${SDR}man | xargs -I {} sudo rm ${MANDIR}/{} ; exit 1 ; }

while true; do
	case $1 in
		--directory | -d ) SDR="${2:-}" ;;
		--delete    | -D ) O_delete     ;;
		--install   | -i ) INS="${2:-}" ;;
		--script    | -s ) ${2:-} --help | pandoc -s -t man | man -l - ; exit ;;
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

SRC=${SDR}
TRG=${SDR}man

cd $SRC

for i in $(ls -l | sed '/^d/d;/^total/d' | awk '{print $NF}'); do
	[[ -n $(grep '\-\-help' $i) ]] && {

		echo "$i"
		echo ".TH ${i^^} 1 $(date +%F | sed 's/-/\\-/g') Linux \"User Manuals\"" > ${TRG}/${i}.1

		$i --help | pandoc -s -t man | sed \
			'/^.\\"/d;/.TH "" "" "" "" ""/d;s/\\f\[C\]/\\f\[B\]/g;s/</\\fI</g;s/>/>\\fP/g' \
			>> ${TRG}/${i}.1

		[[ -n $INS ]] && {
			[[ $INS == "copy" ]] && sudo cp      ${TRG}/${i}.1 ${MANDIR}/${i}.1
			[[ $INS == "link" ]] && sudo ln -sf  ${TRG}/${i}.1 ${MANDIR}/${i}.1
			}

		}
done
