#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon  7 Oct 23:04:04 BST 2019
# source /home/gavarch/.config/user-dirs.dirs

SDR=${USER_SCR_DIR:-"${HOME}/scr"}
MANDIR=/usr/share/man/man1

help () {
cat << 'EOB'
# NAME

__manner__ - generates man pages for scripts

# SYNOPSIS

```
manner [--source-directory|-d <source-directory>]
       [--man-directory|-m <man-directory>]
       [--install|-i copy|link]
manner --delete|-D
manner --script|-s <script>
manner --help|-h
```

# DEPENDENCIES

```
pandoc
```

# OPTIONS

`--source-directory|-d <source-directory>`  
Directory that contains your source scripts

`--man-directory|-m <man-directory>`  
Directory to output your new manpages

`--install|-i copy|link`  
Install all the manpages in `<source-directory>`man to
`/usr/share/man/man1` if they do not already exist.  
Argument to this option determines whether the scripts
are copied or linked.

`--delete|-D`  
Delete all occurences of generated manpages from `/usr/share/man/man1`

`--script|-s <script>`  
Call specified `<script>` with `--help` flag, and convert
the output to a man page with `pandoc -s -t man`

`--help|-h`  
Print this help

# DESCRIPTION

Looks for all scripts in `<source-directory>` that
contain a `--help` string, and pipe `<script> --help`
through `pandoc -s -t man` and redirect the output to
a manpage named `<script>.1` in `<man-directory>`

> NOTE THAT THIS ONLY WORKS BECAUSE ALL MY HELP FUNCTIONS
> ARE WRITTEN IN `markdown`. All precode is converted to bold
> text.

The `--install` flag can be used to install the manpages in
`<man-directory>` to `/usr/share/man/man1`

__In progress__  
The `--script` flag can be used to automatically pipe the
output of the specified script to a man page.

EOB
exit
}

O_delete () { ls ${MDR} | xargs -I {} sudo rm ${MANDIR}/"{}" ; exit ; }

while true; do
	case $1 in
		--source-directory | -d ) SDR="${2:-}" ; shift ;;
		--man-directory    | -m ) MDR="${2:-}" ; shift ;;
		--install          | -i ) INS="${2:-}" ; shift ;;
		--delete           | -D ) DEL=1 ;;
		--script           | -s ) "${2:-}" --help | pandoc -s -t man | man -l - ; exit ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

SRC=${SDR}
[[ -z ${MDR} ]] && MDR=${SRC}man
[[ -d ${MDR} ]] || mkdir -p $MDR
TRG=${MDR}

[[ -n $DEL ]] && O_delete

cd $SRC
for i in $(ls -l | sed '/^d/d;/^total/d' | awk '{print $NF}'); do
	[[ -n $(grep '\-\-help' $i) ]] && {

		echo "$i"
		echo ".TH ${i^^} 1 $(date +%F | sed 's/-/\\-/g') Linux \"User Manuals\"" > ${TRG}/${i}.1

		$i --help | pandoc -s -t man | sed \
			'/^.\\"/d;/.TH "" "" "" "" ""/d;s/\\f\[C\]/\\f\[B\]/g;s/</\\fI</g;s/>/>\\fP/g' \
			>> ${TRG}/${i}.1

		[[ -n $INS ]] && {
			[[ $INS == "copy" ]] && sudo cp      ${TRG}/${i}.1 ${MANDIR}/${i}.1
			[[ $INS == "link" ]] && sudo ln -sf  ${TRG}/${i}.1 ${MANDIR}/${i}.1
			}

		}
done
