#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Wed 28 Aug 16:27:25 BST 2019

RFDR="${HOME}/.config/rofi"
#		${RFDR}/rofi-fontawesome/icon-list.txt \
CHO=$(cat ${RFDR}/.menunicon \
		${RFDR}/rofi-fontawesome/fa5-icon-list.txt \
		${RFDR}/rofi-fontawesome/unicode-list.txt | \
	i3menu -l 15 -w 50 -C 4)

if [[ $CHO =~ ^\<span ]]; then
	echo -ne $(echo "$CHO" | awk -F';' -v RS='>' '
		NR==2{sub("&#x","",$1);print "\\u" $1;exit}') | \
		xclip -selection clipboard
else
	echo -n ${CHO:0:1} | xsel -i; xsel -o | xsel -i -b
fi

#xdotool key 'ctrl+v'
