#!/bin/bash

# OA: Gavin Vales
# CREATED: Thu 30 May 22:45:53 GMT 2019

rofiDir="$HOME/.config/rofi"

bkd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
bkl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
grn=$(xrdb -query | grep '*color2' | awk '{print $NF}')
ylw=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
wtd=$(xrdb -query | grep '*color7' | awk '{print $NF}')
wtl=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blu=$(xrdb -query | grep '*color4' | awk '{print $NF}')
gnt=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyn=$(xrdb -query | grep '*color6' | awk '{print $NF}')
fnt="Iosevka Semibold Oblique"
fsz="12"


echo "* {" > $rofiDir/white.rasi
echo "accent: $wtl;" >> $rofiDir/white.rasi
echo "bg2: $bkd;" >> $rofiDir/white.rasi
echo "bg1: $bkl;" >> $rofiDir/white.rasi
echo "fg2: $wtd;" >> $rofiDir/white.rasi
echo "fg1: $wtl;" >> $rofiDir/white.rasi
echo "redish: $red;" >> $rofiDir/white.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/white.rasi
echo "}" >> $rofiDir/white.rasi

echo "* {" > $rofiDir/black.rasi
echo "accent: $bkd;" >> $rofiDir/black.rasi
echo "fg1: $bkd;" >> $rofiDir/black.rasi
echo "fg2: $bkl;" >> $rofiDir/black.rasi
echo "bg1: $wtd;" >> $rofiDir/black.rasi
echo "bg2: $wtl;" >> $rofiDir/black.rasi
echo "redish: $red;" >> $rofiDir/black.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/black.rasi
echo "}" >> $rofiDir/black.rasi

echo "* {" > $rofiDir/blue.rasi
echo "accent: $blu;" >> $rofiDir/blue.rasi
echo "bg1: $bkd;" >> $rofiDir/blue.rasi
echo "bg2: $bkl;" >> $rofiDir/blue.rasi
echo "fg1: $wtd;" >> $rofiDir/blue.rasi
echo "fg2: $wtl;" >> $rofiDir/blue.rasi
echo "redish: $red;" >> $rofiDir/blue.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/blue.rasi
echo "}" >> $rofiDir/blue.rasi

echo "* {" > $rofiDir/red.rasi
echo "accent: $red;" >> $rofiDir/red.rasi
echo "bg1: $bkd;" >> $rofiDir/red.rasi
echo "bg2: $bkl;" >> $rofiDir/red.rasi
echo "fg1: $wtd;" >> $rofiDir/red.rasi
echo "fg2: $wtl;" >> $rofiDir/red.rasi
echo "redish: $red;" >> $rofiDir/red.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/red.rasi
echo "}" >> $rofiDir/red.rasi

echo "* {" > $rofiDir/green.rasi
echo "accent: $grn;" >> $rofiDir/green.rasi
echo "bg1: $bkd;" >> $rofiDir/green.rasi
echo "bg2: $bkl;" >> $rofiDir/green.rasi
echo "fg1: $wtd;" >> $rofiDir/green.rasi
echo "fg2: $wtl;" >> $rofiDir/green.rasi
echo "redish: $red;" >> $rofiDir/green.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/green.rasi
echo "}" >> $rofiDir/green.rasi

echo "* {" > $rofiDir/yellow.rasi
echo "accent: $ylw;" >> $rofiDir/yellow.rasi
echo "bg1: $bkd;" >> $rofiDir/yellow.rasi
echo "bg2: $bkl;" >> $rofiDir/yellow.rasi
echo "fg1: $wtd;" >> $rofiDir/yellow.rasi
echo "fg2: $wtl;" >> $rofiDir/yellow.rasi
echo "redish: $red;" >> $rofiDir/yellow.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/yellow.rasi
echo "}" >> $rofiDir/yellow.rasi

echo "* {" > $rofiDir/magenta.rasi
echo "accent: $gnt;" >> $rofiDir/magenta.rasi
echo "bg1: $bkd;" >> $rofiDir/magenta.rasi
echo "bg2: $bkl;" >> $rofiDir/magenta.rasi
echo "fg1: $wtd;" >> $rofiDir/magenta.rasi
echo "fg2: $wtl;" >> $rofiDir/magenta.rasi
echo "redish: $red;" >> $rofiDir/magenta.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/magenta.rasi
echo "}" >> $rofiDir/magenta.rasi

echo "* {" > $rofiDir/cyan.rasi
echo "accent: $cyn;" >> $rofiDir/cyan.rasi
echo "bg1: $bkd;" >> $rofiDir/cyan.rasi
echo "bg2: $bkl;" >> $rofiDir/cyan.rasi
echo "fg1: $wtd;" >> $rofiDir/cyan.rasi
echo "fg2: $wtl;" >> $rofiDir/cyan.rasi
echo "redish: $red;" >> $rofiDir/cyan.rasi
echo "font1: \"$fnt $fsz\";" >> $rofiDir/cyan.rasi
echo "}" >> $rofiDir/cyan.rasi
