#!/usr/bin/env bash

cd $HOME
TDR=$USER_SCR_DIR

help () {
cat << 'EOB'
# NAME

__mkscr__ - make bash script

# SYNOPSIS

```
mkscr [--targetdirectory|-d <directory>]
      [--subdirectory|-s <directory>]
      [--template|-t <file>]
      [--generate-help|-g]
      <name>
mkscr --help|-h
```

# OPTIONS

Last argument is always the `<name>` of the new script

`--subdirectory|-s <directory>`  
Create script in subdirectory `<directory>`

`--generate-help|-g`  
Generate help function

`--template|-t <file>`  
Use `<file>` as template

`--help|-h`  
Print this help

EOB
exit
}

template () {
	cd $TDR
	cp "${TEMP}" "${TRG}"
	vim ${TRG}
}

main () {
[[ -d $TDR ]] && cd $TDR || { mkdir $TDR ; cd $TDR ; }
[[ -n $SDR ]] && { [[ -d $SDR ]] || mkdir $SDR ; cd $SDR ; }

[[ -f $TRG ]] && vim $TRG || {
cat > $TRG << 'EOB'
#!/usr/bin/env bash

EOB

	[[ -n $GHP ]] && {
	cat >> $TRG << 'EOB'
help () {
BSE=$(basename $0)
cat << EOB
# NAME
__${BSE}__ - <++>

# SYNOPSIS

```
${BSE} [--<++>|-<++>]
${BSE} --help|-h
```
\EOB
echo $1
exit
}

EOB
	}

cat >> $TRG << 'EOB'
while true; do
	case $1 in
#		--<++> | -<++> ) <++>="${2:-}" ; shift ;;
		--help ) help ;;
		-h ) help | \
			sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
			sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g'
			exit
			;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

EOB
}

chmod +x $TRG
vim $TRG
}

while true; do
	case $1 in
		--subdirectory    | -s ) SDR="${2:-}"  ; shift ;;
		--targetdirectory | -d ) TDR="${2:-}"  ; shift ;;
		--template        | -t ) TEMP="${2:-}" ; shift ;;
		--generate-help   | -g ) GHP=1                 ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TRG=${@:-}
[[ -n ${TEMP} ]] && template || main
