#!/usr/bin/env bash

cd $HOME
DIR=$USER_SCR_DIR

help () {
	cat << 'EOB'
               ██                           
              ▒██                           
   ██████████ ▒██  ██  ██████  █████  ██████
  ▒▒██▒▒██▒▒██▒██ ██  ██▒▒▒▒  ██▒▒▒██▒▒██▒▒█
   ▒██ ▒██ ▒██▒████  ▒▒█████ ▒██  ▒▒  ▒██ ▒ 
   ▒██ ▒██ ▒██▒██▒██  ▒▒▒▒▒██▒██   ██ ▒██   
   ███ ▒██ ▒██▒██▒▒██ ██████ ▒▒█████ ▒███   
  ▒▒▒  ▒▒  ▒▒ ▒▒  ▒▒ ▒▒▒▒▒▒   ▒▒▒▒▒  ▒▒▒    
	-- make bash script

 Usage
 -----
 mkscr --subdirectory|-s  ┼ Create script in
                    [DIR] │   subdirectory DIR
 mkscr --generate-help|-g ┼ Generate help function
 mkscr --template|-t      ┼ Use FILE as template
                   [FILE] │
 mkscr --help|-h          ┼ print this help
EOB
exit
}

template () {
	cd $DIR
	cp "${TEMP}" "${TRG}"
	vim ${TRG}
}

main () {
	[[ -d $DIR ]] && cd $DIR || {
		mkdir $DIR
		cd $DIR
		}

	[[ -n $SDR ]] && {
		[[ -d $SDR ]] && cd $SDR || {
			mkdir $SDR && cd $SDR
			}
		}

	[[ -f $TRG ]] && vim $TRG || {
		cat > $TRG <<EOB
#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
# source $HOME/.config/user-dirs.dirs

while true; do
	case \$1 in
		--<++> | -<++> ) <++>="\${2:-}" ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

EOB
		[[ -n $GHP ]] && {
		cat >> $TRG <<EOB
help () {
$(banner $TRG)
	-- <++>

 Usage
 -----
 $TRG --<++>|-<++> ┼ <++>
 $TRG --help|-h    ┼ Print this help
}
EOB
			}
		chmod +x $TRG
		vim $TRG
	}
}

while true; do
	case $1 in
		--subdirectory  | -s ) SDR="${2:-}"  ; shift ;;
		--template      | -t ) TEMP="${2:-}" ; shift ;;
		--generate-help | -g ) GHP=1                 ;;
		--help          | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TRG=${@:-}
[[ -n ${TEMP} ]] && template || main
