#!/usr/bin/env bash

cd $HOME
DIR=$USER_SCR_DIR

help () {
	cat <<EOB
$(banner ${0##*/})
	-- generate bash script

 Usage
 -----
 ${0##*/} --subdirectory|-s  [DIR] ┼ Create script in
                                │   subdirectory DIR
 ${0##*/} --generate-help|-g       ┼ Generate help function
 ${0##*/} --help|-h                ┼ print this help
EOB
exit
}

main () {
	[[ -d $DIR ]] && cd $DIR || {
		mkdir $DIR
		cd $DIR
		}

	[[ -n $SDR ]] && {
		[[ -d $SDR ]] && cd $SDR || {
			mkdir $SDR && cd $SDR
			}
		}

	[[ -f $TRG ]] && vim $TRG || {
		cat > $TRG <<EOB
#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
# source $HOME/.config/user-dirs.dirs

while true; do
	case \$1 in
		--<++> | -<++> ) <++>="\${2:-}" ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

EOB
		[[ -n $GHP ]] && {
		cat >> $TRG <<EOB
help () {
$(banner $TRG)
	-- <++>

 Usage
 -----
 $TRG --<++>|-<++> ┼ <++>
 $TRG --help|-h    ┼ Print this help
}
EOB
			}
		chmod +x $TRG
		vim $TRG
	}
}

while true; do
	case $1 in
		--subdirectory  | -s ) SDR="${2:-}" ; shift ;;
		--generate-help | -g ) GHP=1 ;;
		--help          | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

TRG=${@:-}
main
