#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sun 16 Dec 18:22:14 GMT 2018

thmDir=$HOME/thm
TRG=$HOME/thm/pywal
wal -q -e -n -s -t -i "${1}"
WALL="${1}"

cd $thmDir

name=${1##*/}
name=${name/%.*}
name=${name/%(*}
name=$(echo "$name" | sed "s/1920x1080//g;s/,//g;s/\ //g")
echo "# vim:ft=perl" > $TRG
echo "name      ${name}" >> $TRG
echo "wallpaper ${name}" >> $TRG
cat $HOME/.cache/wal/colors-kitty.conf | grep 'color' | \
sed "/color10/d;/color11/d;/color12/d;/color13/d;/color14/d;/color9/d;/color8/d;\
s/color15/fg0\ /g;\
s/color0/bg0/g;\
s/color1/red/g;\
s/color2/grn/g;\
s/color3/ylw/g;\
s/color4/acc/g;\
s/color5/gnt/g;\
s/color6/cyn/g;\
/color7/d" \
>> $TRG

i3wallpaper -w "$WALL"
themer -c pywal
reloadconfs &>/dev/null &
themer -x post-build-apply \
       -a /home/gavarch/numix-solarized-gtk-theme &>/dev/null &
