#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sun 16 Dec 18:22:14 GMT 2018

thmDir=$HOME/themes

#feh --bg-scale "${1}"
wal -q -i "${1}"
WALL="${1}"

#rm "$HOME/.config/wall.png"
#cp "${1}" "$HOME/.config/wall.png"
#feh --bg-scale "${1}"

cd $thmDir

echo "wallpaper   "${WALL}"" > .current
name=${1/%.*}
name=${name/%(*}
name=${name/1920x1080/}
name=${name/,/}
name=${name/,/}
name=${name/,/}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name/ /}
name=${name##*/}
echo "name        ${name}" >> .current
cat $HOME/.cache/wal/colors-kitty.conf | grep 'color' | \
sed "/color10/d;/color11/d;\
/color12/d;/color13/d;\
/color14/d;/color9/d;/color8/d;\
s/color15\ \ \ \ \ /foreground\ /g;\
s/color0\ \ \ \ \ /background/g;\
s/color1\ \ \ \ \ /red\ \ \ \ \ \ \ /g;\
s/color2\ \ \ \ \ /green\ \ \ \ \ /g;\
s/color3\ \ \ \ \ /yellow\ \ \ \ /g;\
s/color4\ \ \ \ \ /accent\ \ \ \ /g;\
s/color5\ \ \ \ \ /magenta\ \ \ /g;\
s/color6\ \ \ \ \ /cyan\ \ \ \ \ \ /g;\
/color7/d" \
>> .current

$HOME/scr/reloadconfs &>/dev/null &
$HOME/scr/themer -g &>/dev/null &
