#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__multimon__ - rofi monitor control for i3

# SYNOPSIS

```
multimon
multimon --help|-h
```
EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

ALL=$(xrandr -q | grep 'connected'    | awk '{print $1}')
CNN=$(xrandr -q | grep ' connected'   | awk '{print $1}')
DCN=$(xrandr -q | grep 'disconnected' | awk '{print $1}')
LCN=$(echo $CNN | wc -w)
MNOP="-w 100"

onecon () {
	xrandr --output "${CNN/ /}" --primary --auto
	OFF=${ALL/${CNN/ /}/}

	for i in $(echo ${OFF}); do
		xrandr --output "$i" --off
	done
	exit
}

1_mon () {
	MN1=$(printf "%s\n" $CNN | i3menu --prompt "Choose primary monitor " $MNOP)
	xrandr --output "$MN1" --primary --auto
	OFF=${ALL/${MN1}/}
	echo ${OFF} | xargs -I {} xrandr --output "{}" --off
}

2_mon () {
	MN1=$(printf "%s\n" $CNN | i3menu --prompt "Choose primary monitor " $MNOP)
	CNN=${CNN/${MN1}/}
	OFF=${ALL/${MN1}/}

	MN2=$(printf "%s\n" $CNN | i3menu --prompt "Choose 2nd monitor " $MNOP)
	OFF=${OFF/${MN2}/}
	M2D=$(printf "%s\n" left-of right-of above below same-as | \
		i3menu --prompt "2nd monitor position from 1st " $MNOP)

	xrandr --output "$MN1" --primary --auto --output "$MN2" --"$M2D" "$MN1" --auto

	echo ${OFF} | xargs -I {} xrandr --output "{}" --off
}

3_mon () {
	MN1=$(printf "%s\n" $CNN | i3menu --prompt "Choose primary monitor " $MNOP)
	CNN=${CNN/${MN1}/}
	OFF=${ALL/${MN1}/}

	MN2=$(printf "%s\n" $CNN | i3menu --prompt "Choose 2nd monitor " $MNOP)
	CNN=${CNN/${MN2}/}
	OFF=${OFF/${MN2}/}
	M2D=$(printf "%s\n" left-of right-of above below same-as | \
		i3menu --prompt "2nd monitor position from 1st " $MNOP)

	MN3=$(printf "%s\n" $CNN | i3menu --prompt "Choose 3nd monitor " $MNOP)
	OFF=${OFF/${MN3}/}
	M3D=$(printf "%s\n" left-of right-of above below same-as | \
		i3menu --prompt "3rd monitor position " $MNOP)
	WCH=$(printf "%s\n" $MN1 $MN2 | i3menu --prompt "Which monitor? " $MNOP)

	xrandr --output "$MN1" --primary --auto --output "$MN2" \
		--"$M2D" "$MN1" --auto --output "$MN3" --"$M3D" "$WCH" --auto

	echo ${OFF} | xargs -I {} xrandr --output "{}" --off
}

A_mon () { arandr && exit ; }

[[ $LCN == 1 ]] && notify-send "Only one monitor connected!" && onecon
MDE=$(printf "%s\n" "1 Monitor" "2 Monitors" "3 Monitors" "A ARandR" \
	| i3menu --prompt "Choose mode" $MNOP | awk '{print $1}')
${MDE}_mon
feh --bg-fill $HOME/pic/i3wallpaper/current
