#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Fri  3 May 16:37:43 GMT 2019

help () {
cat << 'EOB'
# NAME

__mpcart__ - get album art of currently playing song in mpd

# SYNOPSIS

```
mpcart
mpcart --help|-h
```
EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

COVER=$USER_TMP_DIR/mpcart.png
rm -rf $COVER
ffmpeg -i "$XDG_MUSIC_DIR/$(mpc -f %file% | head -n1)" $COVER &>/dev/null &

#notify-send "Now Playing ♫" "$(mpc current)" -i $COVER
sleep .5
[[ ! -f $COVER ]] && cp ${USER_SCR_DIR}/pic/albartdef.jpg $COVER

dunstify -r 1234 --raw_icon=$COVER "Now Playing ♫" "$(mpc current)"

i3media &>/dev/null &
