#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 26 Jan 21:59:12 GMT 2019

VID="$1"
open="$(pidof mpv)"
fifo="$USER_TMP_DIR/mppipe"

if [[ ${VID} =~ 'youtube.com' ]]; then
	if [[ -n ${open} ]]; then
		echo "loadfile \"${VID}\"" append-play > "${fifo}"
	else
		rm "${fifo}"
		mkfifo "${fifo}"
		mpv --geometry=35%-10-10 --ytdl-format=bestvideo+bestaudio --input-file="${fifo}" "${VID}" &>/dev/null &
	fi
else
	if [[ -n ${open} ]]; then
		echo "loadfile \"${VID}\"" append-play > "${fifo}"
	else
		rm "${fifo}"
		mkfifo "${fifo}"
		mpv --input-file="${fifo}" "${VID}" &>/dev/null &
	fi
fi
