#!/usr/bin/env bash

ALL=$(xrandr -q | grep 'connected' | awk '{print $1}')
CNN=$(xrandr -q | grep ' connected' | awk '{print $1}')
DCN=$(xrandr -q | grep 'disconnected' | awk '{print $1}')
LCN=$(xrandr -q | grep ' connected' | awk '{print $1}' | wc -l)
MNOP="-l 0 -w 100 -o horizontal"

1_mon () {
	MN1=$(echo $CNN | tr ' ' '\n' | \
		i3menu -p "Choose primary monitor " $MNOP)

	OFF=$(echo $ALL | grep -v "$MN1" | awk '{print $1}')

	xrandr --output "$MN1" --primary --auto

	for i in $(echo ${OFF}); do
		xrandr --output "$i" --off
	done
}

2_mon () {
	MN1=$(echo $CNN | tr ' ' '\n' | \
		i3menu -p "Choose primary monitor " $MNOP)

	MN2=$(echo $CNN | tr ' ' '\n' | grep -v "$MN1")

	MN2DIR=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | \
		i3menu -p "2nd monitor position " $MNOP)

	xrandr --output "$MN1" --primary --auto \
		--output "$MN2" --"$MN2DIR" "$MN1" --auto
}

3_mon () {
	MN1=$(echo $CNN | tr ' ' '\n' | \
		i3menu -p "Choose primary monitor " $MNOP)

	MN2=$(echo $CNN | tr ' ' '\n' | grep -v "$MN1" | \
		i3menu -p "Choose 2nd monitor " $MNOP)

	MN3=$(echo $CNN | tr ' ' '\n' | grep -v "$MN1" | grep -v "$MN2")

	MN2DIR=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | \
		i3menu -p "2nd monitor position " $MNOP)

	MN3DIR=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | \
		i3menu -p "3rd monitor position " $MNOP)

	which=$(echo $CNN | tr ' ' '\n' | \
		i3menu -p "Which monitor?" $MNOP)

	xrandr --output "$MN1" --primary --auto --output "$MN2" \
		--"$MN2DIR" "$MN1" --auto --output "$MN3" --"$MN3DIR" "$which" --auto
}

A_mon () { arandr && exit ; }

#[[ $LCN == 1 ]] && notify-send "Only one monitor connected!" && exit
#MDE=$(echo -e "1 Monitor\n2 Monitors\n3 Monitors\nA ARandR" \
#	| i3menu -p "Choose mode" $MNOP \
#	| awk '{print $1}')
#echo ${MDE}_mon
#feh --bg-fill $HOME/pic/i3wallpaper/current
