#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Fri 17 May 18:47:08 BST 2019

NMFL=$HOME/nightmode
nightmode=$(cat $NMFL)

if [[ ! -f $NMFL ]]; then
	redshift -P -O 3700
	echo on > $NMFL
	polybar-msg hook nm 2
elif [[ -f $NMFL ]]; then
	if [[ $nightmode == "off" ]]; then
		redshift -P -O 3700
		echo on > $NMFL
		polybar-msg hook nm 2
	elif [[ $nightmode == "on" ]]; then
		redshift -x
		echo off > $NMFL
		polybar-msg hook nm 1
	fi
else
	redshift -x
	echo off > $NMFL
	polybar-msg hook nm 1
fi
