#!/bin/bash

# OA: Gavin Vales
# CREATED: Fri 17 May 18:47:08 BST 2019

nightmode=$(cat ~/nightmode)

if [[ ! -f ~/nightmode ]]; then
	redshift -P -O 3700
	echo on > ~/nightmode
	polybar-msg hook nm 2
elif [[ -f ~/nightmode ]]; then
	if [[ $nightmode == "off" ]]; then
		redshift -P -O 3700
		echo on > ~/nightmode
		polybar-msg hook nm 2
	elif [[ $nightmode == "on" ]]; then
		redshift -x
		echo off > ~/nightmode
		polybar-msg hook nm 1
	fi
else
	redshift -x
	echo off > ~/nightmode
	polybar-msg hook nm 1
fi
