#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Wed  7 Aug 14:04:15 BST 2019

NOTEDIR=$XDG_DESKTOP_DIR
DEFNOTES="NOTES\nWATCHLIST\nTODO"
[[ -d $NOTEDIR ]] || mkdir $NOTEDIR
IFS=$'\n'
for i in $(echo -e $DEFNOTES); do
	[[ -f $NOTEDIR/${i} ]] || touch "$NOTEDIR/${i}"
done

help () {
	cat << 'EOB'
                       ██
                      ▒██
   ███████   ██████  ██████  █████  ██████
  ▒▒██▒▒▒██ ██▒▒▒▒██▒▒▒██▒  ██▒▒▒██▒▒██▒▒█
   ▒██  ▒██▒██   ▒██  ▒██  ▒███████ ▒██ ▒
   ▒██  ▒██▒██   ▒██  ▒██  ▒██▒▒▒▒  ▒██
   ███  ▒██▒▒██████   ▒▒██ ▒▒██████▒███
  ▒▒▒   ▒▒  ▒▒▒▒▒▒     ▒▒   ▒▒▒▒▒▒ ▒▒▒

 Usage
 -----

 noter                              ┼ Create defaults:
                                    │   NOTE_DIR = $HOME/Desktop
                                    │   NOTE_TYPE = OTHER|NOTES|
                                    │     WATCHLIST|TODO
 noter --help|-h                    ┼ Print this help
 noter --type|-t        [NOTE_TYPE] ┼ Create NOTE_DIR/NOTE_TYPE
 noter --entry|-e       [ENTRY]     ┼ Entry to add to the note
 noter --delete|-d      [ENTRY]     ┼ Delete entry in note file
 noter --delete-type|-D [NOTE_TYPE] ┼ cat NOTE_DIR/NOTE_TYPE
 noter --list|-l                    ┼ ls NOTE_DIR
 noter --list-types|-L  [NOTE_TYPE] ┼ Delete NOTE_DIR/NOTE_TYPE

EOB
exit
}

deleteentry () { sed "/${1}/d" -i ${TYPE} ; exit ; }
deletetype  () { rm -rf "$NOTEDIR/${1}" ; exit ; }
listtypes   () { ls $NOTEDIR ; exit ; }
listnotes   () { cat $NOTEDIR/$1 || echo "$1 doesn't exist." ; exit ; }

create () {
	[[ -z ${TYPE} ]] || {
		[[ -f ${TYPE} ]] || touch ${TYPE}
		[[ -n ${NTRY} ]] && FNTRY="$NTRY" \
			|| FNTRY="$(echo "" | i3menu -o horizontal -w 800 -c green -p "${TYPE##*/} ")"
		[[ -z ${FNTRY} ]] || echo -e "${FNTRY}" >> ${TYPE}
	}
}

while true; do
	case $1 in
		--help        | -h ) help                                       ; shift ;;
		--type        | -t ) TYPE="${NOTEDIR}/${2:-}"                   ; shift ;;
		--entry       | -e ) NTRY="$(echo ${2:-} | sed "s/_/\n\ \ /g")" ; shift ;;
		--delete      | -d ) deleteentry "${2:-}"                       ; shift ;;
		--delete-type | -D ) deletetype "${2:-}"                        ; shift ;;
		--list        | -l ) listnotes "${2:-}"                         ; shift ;;
		--list-types  | -L ) listtypes "${2:-}"                         ; shift ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

create
