#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 14 Oct 22:43:19 BST 2019
# source /home/gavarch/.config/user-dirs.dirs

help () {
	echo help
	exit
}

INST=terminal

while true; do
	case $1 in
		--instance | -i ) INST="${2:-}" ; shift ;;
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

CMD="${@:-}"
echo $CMD
echo $INST
