#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
#source $HOME/.config/user-dirs.dirs

MODDIR=$HOME/.config/pbcat
[[ -d $MODDIR ]] || mkdir $MODDIR

help () {
cat << 'EOB'
# NAME

__pbcat__ - script to create lots of polybar ipc modules

# SYNOPSIS

```
pbcat [--foreground|-f <hex>]
      [--background|-b <hex>]
      [--invert|-i]
      --module|-m <module>
      <text>
pbcat --help|-h
```

# OPTIONS

Final argument is `<text>` to print to `<module>`.
All modules are stored in `$HOME/.config/pbcat`.

`--module|-m <module>`  
`<module>` to update

`--foreground|-f <hex>`  
Foreground colour

`--background|-b <hex>`  
Background colour

`--invert|-i`  
Invert foreground and background colours

`--help|-h`  
Print this help

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--module     | -m ) MOD="${2:-}" ; shift ;;
		--foreground | -f ) FG="${2:-}"  ; shift ;;
		--background | -b ) BG="${2:-}"  ; shift ;;
		--invert     | -i ) PRE+="%{R}" ;;
		--help ) help ;;
		-h     ) help | sed -n "/# SYNOPSIS/,/#/p" | sed '/^#/d;/^$/d;/```/d' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

VAL="${@:-}"
notify-send $VAL

[[ -f $MODDIR/$MOD ]] || echo "$MOD" > $MODDIR/$MOD
[[ -z $VAL ]] && cat $MODDIR/$MOD || {
	[[ -n $FG ]] && PRE+="%{F$FG}" END+="%{F-}"
	[[ -n $BG ]] && PRE+="%{B$BG}" END+="%{B-}"
	FVAL="$PRE$VAL$END"
	echo "$FVAL" > $MODDIR/$MOD
	polybar-msg hook $MOD 1
}
