#!/bin/bash

$HOME/scr/themer -t "$HOME/xrs" -x "xrs-reload" -g
$HOME/scr/themer -t "$HOME/.config/i3" -x "i3concat" -g
$HOME/scr/themer -t "$HOME/.config/polybar" -x "pb-reload" -g
$HOME/scr/themer -t "$HOME/.config/rofi" -x " " -g
$HOME/scr/themer -t "$HOME/.config/vis/colors" -x " " -g
$HOME/scr/themer -t "$HOME/.config/mpv" -x " " -g
$HOME/scr/themer -t "$HOME/.config/zathura" -x "reloadinst" -g
$HOME/scr/themer -t "$HOME/.config/dunst" -x "dunst-reload" -g
$HOME/scr/themer -t "$HOME/.config/qutebrowser" -x " " -g
$HOME/scr/themer -t "$HOME/git/i3rice-arch" -x " " -g
$HOME/scr/themer -t "$HOME/.vim/colors" -x " " -g
$HOME/scr/themer -t "$HOME/scr/.unused" -x " " -g
$HOME/scr/themer -t "$HOME/plt/css" -x " " -g
$HOME/scr/i3listen-toggle
#$HOME/scr/themer -t "$HOME/.config/tint2" -x " " -g
#$HOME/scr/themer -t "$HOME/git/atompackages/packages/rice-syntax/styles" -x " " -g
