#!/usr/bin/env bash

cd ${HOME}
LST="${HOME}/.config/rofi/.rofindlist"
IGN="${HOME}/.config/rofi/.rofindignore"
FOLDOPEN="thunar" FILEOPEN="$EDITOR"
IMGOPEN="openimage" VIDOPEN="openvid" MUSOPEN="mpc insert"
XBMOPEN="gthumb" PDFOPEN="zathura"
MANOPEN="${TERMINAL:-"urxvt"} -e man"
iIMG="" iVID="" iMUS="♫" iSCR=""
iXBM="🖻" iPDF="" iMAN=""
iDOC="" iXLS="" iPPT=""
#find . -type d \( -path dir1 -o -path dir2 -o -path dir3 \) -prune -o -print

help () {
cat << 'EOB'
# NAME

__rofind__  - `find` wrapper with `rofi`

# DEPENDENCIES

```
rofi
i3menu
```

# SYNOPSIS

```
rofind
rofind --help|-h
```

# DESCRIPTION

Just a `rofi` wrapper for `find`, and opens the chosen item using
an appropriate application.

EOB
exit
}

while true; do
	case $1 in
#		--<++> | -<++> ) <++>="${2:-}" ; shift ;;
		--help ) help ;;
		-h ) help | \
			sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
			sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

NORMAL () {
#	[[ -d "${1}" ]] && eval "$FOLDOPEN \"${1}\""
	[[ -d "${1}" ]] && FLIST "${1}" "${1/$HOME/}"
	[[ -f "${1}" ]] && eval "$FILEOPEN \"${1}\""
}
FLIST  () {
#		BEGIN{printf("%s","find -L . -type f -mindepth 1 ")}
#		{c++;gsub(/\.\//,"",$0);printf("-name \"%s\" ",$0)
#			if(c!=LEN){printf("%s","! ")}}
#		END{print ""}
	local DIR="$1"
	cd "$DIR"
	[[ -s $IGN ]] && CMD="$(awk '
		BEGIN{print "find -L . -type d \\( "}
		{ print "-path \""$0"\" -o" }
		END{print " \\) -prune -o -print"}
	' $IGN)" || CMD="find -L . -type d "

	TRG="$(eval "$(echo ${CMD} | sed 's/-o \\)/\\)/g')" | \
		awk -v HOME="~/" -v iSCR="$iSCR" \
		-v iIMG="$iIMG" -v iVID="$iVID" -v iMUS="$iMUS" \
		-v iXBM="$iXBM" -v iPDF="$iPDF" -v iMAN="$iMAN" \
		-v iDOC="$iDOC" -v iXLS="$iXLS" -v iPPT="$iPPT" '{
#			gsub(/^\.\//,HOME,$0)
			gsub(/^\.\//,"",$0)
			if($0 ~ /.png$|.jpeg$|.jpg$|.svg$|.xpm$/){print iIMG" "$0}
			else if($0 ~ /.mp4$|.mkv$|.mov$/){print iVID" "$0}
			else if($0 ~ /.mp3$/)            {print iMUS" "$0}
			else if($0 ~ /.xbm$/)            {print iXBM" "$0}
			else if($0 ~ /.pdf$|.epub$/)     {print iPDF" "$0}
			else if($0 ~ /.sh$|.py$|.cpp$/)  {print iSCR" "$0}
			else if($0 ~ /.1$/)              {print iMAN" "$0}
			else if($0 ~ /.docx$/)           {print iDOC" "$0}
			else if($0 ~ /.xlsx$/)           {print iXLS" "$0}
			else if($0 ~ /.pptx$/)           {print iPPT" "$0}
			else {print $0}
		}' | i3menu --prompt "${2:-"rofind"}" -H 30 -w 30 -L 2 --color green)"

	[[ -z $TRG ]] && exit || \
	case $TRG in
		$iSCR*) $FILEOPEN "${TRG/"$iSCR "/${HOME}\/}" ;;
		$iIMG*) $IMGOPEN  "${TRG/"$iIMG "/${HOME}\/}" ;;
		$iVID*) $VIDOPEN  "${TRG/"$iVID "/${HOME}\/}" ;;
		$iMUS*) $MUSOPEN  "${TRG/"$iMUS "/${HOME}\/}" ;;
		$iXBM*) $XBMOPEN  "${TRG/"$iXBM "/${HOME}\/}" ;;
		$iPDF*) $PDFOPEN  "${TRG/"$iPDF "/${HOME}\/}" ;;
		$iMAN*) $MANOPEN  "${TRG/"$iMAN "/${HOME}\/}" ;;
		$iDOC*) lowriter  "${TRG/"$iDOC "/${HOME}\/}" ;;
		$iXLS*) localc    "${TRG/"$iXLS "/${HOME}\/}" ;;
		$iPPT*) loimpress "${TRG/"$iPPT "/${HOME}\/}" ;;
		*)      NORMAL    "${HOME}/${TRG}" ;;
#		*)      NORMAL    "${TRG/''/${HOME}}" ;;
	esac
}

FLIST "${HOME}"

