#!/usr/bin/env bash

cd ${HOME}
FOLDOPEN="thunar" FILEOPEN="$EDITOR"
IMGOPEN="openimage" VIDOPEN="openvid" MUSOPEN="mpc insert"
XBMOPEN="gthumb"    PDFOPEN="zathura" MANOPEN="${TERMINAL:-"urxvt"} -e man"
iIMG="" iVID="📹" iMUS="♫" iSCR=""
iXBM="🖻" iPDF="" iMAN=""
iDOC="" iXLS="" iPPT=""
LST="${HOME}/.config/rofi/.rofindlist"
IGN="${HOME}/.config/rofi/.rofindignore"
#find . -type d \( -path dir1 -o -path dir2 -o -path dir3 \) -prune -o -print

help () {
cat << 'EOB'
# NAME

__rofind__  - `find` wrapper with `rofi`

# DEPENDENCIES

```
rofi
i3menu
```

# SYNOPSIS

```
rofind
rofind --help|-h
```

# DESCRIPTION

Just a `rofi` wrapper for `find`, and opens the chosen item using
an appropriate application.

EOB
exit
}

while true; do
	case $1 in
#		--<++> | -<++> ) <++>="${2:-}" ; shift ;;
		--help ) help ;;
		-h ) help | \
			sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
			sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

NORMAL () {
	[[ -d "${1}" ]] && echo Folder && eval "$FOLDOPEN \"${1}\""
	[[ -f "${1}" ]] && echo File   && eval "$FILEOPEN \"${1}\""
}

flist   () {
	local DIR="$1"
	cd $DIR
	[[ -s $IGN ]] && CMD="$(awk '
#		BEGIN{printf("%s","find -L . -type f -mindepth 1 ")}
#		{c++;gsub(/\.\//,"",$0);printf("-name \"%s\" ",$0)
#			if(c!=LEN){printf("%s","! ")}}
#		END{print ""}
		BEGIN{print "find -L . -type d -mindepth 1 \\( "}
		{ print "-path \""$0"\" -o" }
		END{print " \\) -prune -o -print"}
	' $IGN)" || CMD="find -L . -type d -mindepth 1 "

	eval "$(echo ${CMD} | sed 's/-o \\)/\\)/g')" | \
		awk -v HOME="~/" -v iSCR="$iSCR" \
		-v iIMG="$iIMG" -v iVID="$iVID" -v iMUS="$iMUS" \
		-v iXBM="$iXBM" -v iPDF="$iPDF" -v iMAN="$iMAN" \
		-v iDOC="$iDOC" -v iXLS="$iXLS" -v iPPT="$iPPT" '{
			gsub(/^\.\//,HOME,$0)
			if($0 ~ /.png$|.jpeg$|.jpg$|.svg$|.xpm$/){print iIMG" "$0}
			else if($0 ~ /.mp4$|.mkv$|.mov$/){print iVID" "$0}
			else if($0 ~ /.mp3$/)            {print iMUS" "$0}
			else if($0 ~ /.xbm$/)            {print iXBM" "$0}
			else if($0 ~ /.pdf$|.epub$/)     {print iPDF" "$0}
			else if($0 ~ /.sh$|.py$|.cpp$/)  {print iSCR" "$0}
			else if($0 ~ /.1$/)              {print iMAN" "$0}
			else if($0 ~ /.docx$/)           {print iDOC" "$0}
			else if($0 ~ /.xlsx$/)           {print iXLS" "$0}
			else if($0 ~ /.pptx$/)           {print iPPT" "$0}
			else {print $0}
		}'
}

TRG="$(flist "${HOME}" | i3menu --prompt "rofind" -l 15 -w 100 -L 1)"

case $TRG in
	$iSCR*) $FILEOPEN "${TRG/"$iSCR ~"/${HOME}}" ;;
	$iIMG*) $IMGOPEN  "${TRG/"$iIMG ~"/${HOME}}" ;;
	$iVID*) $VIDOPEN  "${TRG/"$iVID ~"/${HOME}}" ;;
	$iMUS*) $MUSOPEN  "${TRG/"$iMUS ~"/${HOME}}" ;;
	$iXBM*) $XBMOPEN  "${TRG/"$iXBM ~"/${HOME}}" ;;
	$iPDF*) $PDFOPEN  "${TRG/"$iPDF ~"/${HOME}}" ;;
	$iMAN*) $MANOPEN  "${TRG/"$iMAN ~"/${HOME}}" ;;
	$iDOC*) lowriter  "${TRG/"$iDOC ~"/${HOME}}" ;;
	$iXLS*) localc    "${TRG/"$iXLS ~"/${HOME}}" ;;
	$iPPT*) loimpress "${TRG/"$iPPT ~"/${HOME}}" ;;
	*)      NORMAL    "${TRG/'~'/${HOME}}" ;;
esac
