#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: $(date)
# source $HOME/.config/user-dirs.dirs

SCDIR=$USER_SCR_DIR/sc
cd $SCDIR

OPF=.outputfiles

for i in $(cat .outputfiles); do
	echo "# >>>> shortcuts" > $i
done

for i in $(ls $SCDIR | sed '/_/!d'); do
	cat $i | sed '/#/d' | awk -i "${i/_/.}" '
	NR==FNR {
		key=$1;$1=""; gsub(/^[ \t]+/, "", $0);val=$0;final();
	}'
done

notify-send "Shortcuts generated!"
