#!/usr/bin/env bash

scrotdir=scrots
picDir="$HOME/pic"

scrotname () {
	time="`date +%Y-%m-%d_%H:%M:%S`.png"
	name=$(echo -e "" | $HOME/scr/i3menu "Choose scrot name:")

	if [[ -z $name ]]; then
		scrotname=$time
	else
		scrotname="${name}.png"
	fi
}

confirmscrot () {
	action=$(echo -e "Save\nNew\nClipboard" | $HOME/scr/i3menu "Save?")
	if [[ $action == "Save" ]]; then
		scrotname
		mv $picDir/$scrotdir/tmp.png $picDir/$scrotdir/${scrotname}
		notify-send "${scrotname} saved to $picDir/${scrotdir}" -i $picDir/${scrotdir}/${scrotname}
	elif [[ $action == "New" ]]; then
		tmpscrot
	elif [[ $action == "Clipboard" ]]; then
		clipboard
	else
		rm $picDir/${scrotdir}/tmp.png
	fi
}

tmpscrot () {
	scrot_type=$(echo -e "Fullscreen\nSelection" | $HOME/scr/i3menu "Scrot type?:")

	if [[ $scrot_type == "Fullscreen" ]]; then
		sleep .25
		maim --hidecursor $picDir/${scrotdir}/tmp.png
	elif [[ $scrot_type == "Selection" ]]; then
		maim --select --hidecursor $picDir/${scrotdir}/tmp.png
	else
		:
	fi

	sxiv $picDir/${scrotdir}/tmp.png 
	[[ -n $scrot_type ]] && confirmscrot
}

clipboard () {
	xclip -selection clipboard -t image/png -i $picDir/${scrotdir}/tmp.png
	notify-send "Copied scrot to Clipboard" -i $picDir/${scrotdir}/tmp.png
	rm $picDir/${scrotdir}/tmp.png
}

tmpscrot
