#!/usr/bin/env bash

help () {
cat << 'EOB'
# screenshot
- take screenshot with `maim`

## Synopsis

```
screenshot
screenshot [--help|-h]
```
EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

SCD=$XDG_PICTURES_DIR/shot
TMP=${SCD}/tmp.png
[[ -d $SCD ]] || mkdir $SCD

scrotname () {
	TME="`date +%Y-%m-%d_%H:%M:%S`.png"
	NME=$(echo "" | i3menu -p "Choose scrot name " \
		-o vertical -w 200 -l 0)
	[[ -z $NME ]] && SCRNME=$TME || SCRNME="$NME.png"
}

confirmscrot () {
	ACT=$(printf "%s\n" Save New Clipboard | i3menu -p "Save? " \
		-o vertical -w 200 -l 0)
	if [[ $ACT == "Save" ]]; then
		scrotname
		mv $TMP $SCD/${SCRNME}
		notify-send "${SCRNME} saved to $SCD" -i ${SCD}/${SCRNME}
	elif [[ $ACT == "New" ]]; then
		tmpscrot
	elif [[ $ACT == "Clipboard" ]]; then
		clipboard
	else
		rm $TMP
	fi
}

tmpscrot () {
	SCRTPE=$(printf "%s\n" Fullscreen Selection | \
		i3menu -p "Screenshot " -o vertical -w 200 -l 0)
	if [[ $SCRTPE == "Fullscreen" ]]; then
		sleep .25
		maim --hidecursor $TMP
	elif [[ $SCRTPE == "Selection" ]]; then
		maim --select --hidecursor $TMP
	else
		:
	fi

	sxiv $TMP 
	[[ -n $SCRTPE ]] && confirmscrot
}

clipboard () {
	xclip -selection clipboard -t image/png -i $TMP
	notify-send "Copied scrot to Clipboard" -i $TMP
	rm $TMP
}

tmpscrot
