#!/usr/bin/env bash


SCRD=$HOME/pic/scrots
TMP=${SCRD}/tmp.png
[[ -d $SCRD ]] || mkdir $SCRD

scrotname () {
	TME="`date +%Y-%m-%d_%H:%M:%S`.png"
	NME=$(echo -e "" | $HOME/scr/i3menu -p "Choose scrot name " \
		-o vertical -w 200 -r 2 -l 0)
	[[ -z $NME ]] && SCRNME=$TME || SCRNME="$NME.png"
}

confirmscrot () {
	ACT=$(echo -e "Save\nNew\nClipboard" | $HOME/scr/i3menu -p "Save? " \
		-o vertical -w 200 -r 3 -l 0)
	if [[ $ACT == "Save" ]]; then
		scrotname
		mv $TMP $SCRD/${SCRNME}
		notify-send "${SCRNME} saved to $SCRD" -i ${SCRD}/${SCRNME}
	elif [[ $ACT == "New" ]]; then
		tmpscrot
	elif [[ $ACT == "Clipboard" ]]; then
		clipboard
	else
		rm $TMP
	fi
}

tmpscrot () {
	SCRTPE=$(echo -e "Fullscreen\nSelection" | \
		$HOME/scr/i3menu -p "Screenshot " -o vertical -w 200 -r 2 -l 0)
	if [[ $SCRTPE == "Fullscreen" ]]; then
		sleep .25
		maim --hidecursor $TMP
	elif [[ $SCRTPE == "Selection" ]]; then
		maim --select --hidecursor $TMP
	else
		:
	fi

	sxiv $TMP 
	[[ -n $SCRTPE ]] && confirmscrot
}

clipboard () {
	xclip -selection clipboard -t image/png -i $TMP
	notify-send "Copied scrot to Clipboard" -i $TMP
	rm $TMP
}

tmpscrot
