#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__snapper__ - take screenshot with `maim`

# SYNOPSIS

```
snapper
snapper --help|-h
```

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--full      | -f ) SCRTPE="Fullscreen" ;;
		--sel       | -s ) SCRTPE="Selection"  ;;
		--noconfirm | -n ) NOCNFM=1 ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

MENOPS="--location 1 -w 50 --color green"
SCD=$XDG_PICTURES_DIR/shot
TMP=${SCD}/tmp.png
[[ -d $SCD ]] || {
	mkdir $SCD
	mkdir $SCD/FULL
	mkdir $SCD/SEL
}

scrotname () {
	TME="`date +%Y-%m-%d_%H:%M:%S`.png"
	NME=$(echo "" | i3menu --prompt "Choose scrot name " $MENOPS)
	[[ -z $NME ]] && SCRNME=$TME || SCRNME="$NME.png"
}

confirmscrot () {
	[[ -n $NOCNFM ]] && {
		TME="`date +%Y-%m-%d_%H:%M:%S`.png"
		mv $TMP ${SCD}/${SDR}/${TME}
		notify-send "$SCRTPE" "${TME} saved to ${SCD}/${SDR}" -i ${SCD}/${SDR}/${TME}
		exit
		}
	sxiv $TMP
	ACT=$(printf "%s\n" Save New Clipboard | \
		i3menu --prompt "Save? " $MENOPS)
	if [[ $ACT == "Save" ]]; then
		scrotname
		mv $TMP ${SCD}/${SDR}/${SCRNME}
		notify-send "$SCRTPE" "${SCRNME} saved to ${SCD}/${SDR}" -i ${SCD}/${SDR}/${SCRNME}
	elif [[ $ACT == "New" ]]; then
		tmpscrot
	elif [[ $ACT == "Clipboard" ]]; then
		clipboard
	else
		rm $TMP
	fi
}

tmpscrot () {
	[[ -n $SCRTPE ]] || SCRTPE=$(printf "%s\n" Fullscreen Selection | \
		i3menu --prompt "Screenshot " $MENOPS)
	if [[ $SCRTPE == "Fullscreen" ]]; then
		sleep .25
		maim --hidecursor $TMP
		SDR=FULL
	elif [[ $SCRTPE == "Selection" ]]; then
		maim --select --hidecursor $TMP
		SDR=SEL
	else
		:
	fi
	[[ -n $SCRTPE ]] && confirmscrot
}

clipboard () {
	xclip -selection clipboard -t image/png -i $TMP
	notify-send "Copied scrot to Clipboard" -i $TMP
	rm $TMP
}

tmpscrot
