#!/usr/bin/env bash

help () {
cat << 'EOB'
# NAME

__snapper__ - take screenshot with `maim`

# SYNOPSIS

```
snapper
snapper --help|-h
```

EOB
echo "$1"
exit
}

while true; do
	case $1 in
		--full | -f ) SCRTPE="Fullscreen" ;;
		--sel  | -s ) SCRTPE="Selection" ;;
		--help ) help ;;
		-h     ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

MENOPS="--location 1 -w 50 --theme dmenu --color blue"
SCD=$XDG_PICTURES_DIR/shot
TMP=${SCD}/tmp.png
[[ -d $SCD ]] || mkdir $SCD

scrotname () {
	TME="`date +%Y-%m-%d_%H:%M:%S`.png"
	NME=$(echo "" | i3menu --prompt "Choose scrot name " $MENOPS)
	[[ -z $NME ]] && SCRNME=$TME || SCRNME="$NME.png"
}

confirmscrot () {
	ACT=$(printf "%s\n" Save New Clipboard | \
		i3menu --prompt "Save? " $MENOPS)
	if [[ $ACT == "Save" ]]; then
		scrotname
		mv $TMP $SCD/${SCRNME}
		notify-send "${SCRNME} saved to $SCD" -i ${SCD}/${SCRNME}
	elif [[ $ACT == "New" ]]; then
		tmpscrot
	elif [[ $ACT == "Clipboard" ]]; then
		clipboard
	else
		rm $TMP
	fi
}

tmpscrot () {
	[[ -n $SCRTPE ]] || SCRTPE=$(printf "%s\n" Fullscreen Selection | \
		i3menu --prompt "Screenshot " $MENOPS)
	if [[ $SCRTPE == "Fullscreen" ]]; then
		sleep .25
		maim --hidecursor $TMP
	elif [[ $SCRTPE == "Selection" ]]; then
		maim --select --hidecursor $TMP
	else
		:
	fi

	sxiv $TMP 
	[[ -n $SCRTPE ]] && confirmscrot
}

clipboard () {
	xclip -selection clipboard -t image/png -i $TMP
	notify-send "Copied scrot to Clipboard" -i $TMP
	rm $TMP
}

tmpscrot
