#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 18 Feb 19:46:53 GMT 2019

ART="${1}"
ALB="${2}"
TOT=$(ls | grep .mp3 | wc -l)

echo "
==================================================
Applying title..."
CNT=0
for i in *.mp3 ; do
	CNT=$(($CNT + 1))
	resto=${i%.*}
	id3v2 -t "${resto}" "${i}"
	echo -ne "\r($CNT/$TOT) ${i}\r"
done

CNT=0
if [[ -n $ART ]]; then
	echo "
==================================================
Changing artist to $ART..."
	for i in *.mp3 ; do
		CNT=$(($CNT + 1))
		resto=${i%.*}
		id3v2 -a "${ART}" "${i}"
		echo -ne "\r($CNT/$TOT) ${i}\r"
	done
fi

CNT=0
if [[ -n $ALB ]]; then
	echo "
==================================================
Changing album name to $ALB..."
	for i in *.mp3 ; do
		CNT=$(($CNT + 1))
		resto=${i%.*}
		id3v2 -A "${ALB}" "${i}"
		echo -ne "\r($CNT/$TOT) ${i}\r"
	done
fi
