#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 18 Feb 19:46:53 GMT 2019

artist="${1}"
album="${2}"

echo "
==================================================
Applying title...
"

for i in *.mp3 ; do
	resto=${i%.*}
	id3v2 -t "${resto}" "${i}"
	echo -ne "$resto >>> ${i}"\\r
done


if [[ -n $artist ]]; then
	echo "
==================================================
Changing artist to $artist...
"
	for i in *.mp3 ; do
		resto=${i%.*}
		id3v2 -a "${artist}" "${i}"
		echo -ne "${i}"\\r
	done
fi


if [[ -n $album ]]; then
	echo "
==================================================
Changing album name to $album...
"
	for i in *.mp3 ; do
		resto=${i%.*}
		id3v2 -A "${album}" "${i}"
		echo -ne "${i}"\\r
	done
fi
