#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon 18 Feb 19:46:53 GMT 2019

help() {
cat << 'EOB'
# NAME

__tagger__ - change artist, album name, and title of mp3's in
a directory

# SYNOPSIS

```
tagger [--artist|-a <text>]
       [--album|-b <text>]
       [--cover|-c <imagefile>]
tagger --help|-h
```
EOB
exit
}

while true; do
	case $1 in
		--artist | -a ) ART="${2:-}" ; shift ;;
		--album  | -b ) ALB="${2:-}" ; shift ;;
		--cover  | -c ) COV="${2:-}" ; shift ;;
		--help ) help ;;
		-h ) help | \
			sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | \
			sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done
TOT=$(ls | grep .mp3 | wc -l)

cat << 'EOB'
==================================================
Applying title...
EOB
CNT=0
for i in *.mp3 ; do
	CNT=$(($CNT + 1))
	resto=${i%.*}
	id3v2 -t "${resto}" "${i}"
	echo "($CNT/$TOT) ${i}"
done

CNT=0
if [[ -n $ART ]]; then
cat << 'EOB'
==================================================
Changing artist to $ART...
EOB
	for i in *.mp3 ; do
		CNT=$(($CNT + 1))
		resto=${i%.*}
		id3v2 -a "${ART}" "${i}"
		echo -ne "\r($CNT/$TOT) ${i}\r"
	done
fi

CNT=0
if [[ -n $ALB ]]; then
cat << 'EOB'
==================================================
Changing album name to $ALB...
EOB
	for i in *.mp3 ; do
		CNT=$(($CNT + 1))
		resto=${i%.*}
		id3v2 -A "${ALB}" "${i}"
		echo -ne "\r($CNT/$TOT) ${i}\r"
	done
fi
