#!/bin/bash

name="$(xdotool getactivewindow getwindowname)"
name="${name/ - File Manager/}"
title="${name/$HOME/'~'}"
title="${title/i3rice-arch/dot}"

dir="${name##*/}"

icn="xdotool key ctrl+shift+i"
lst="xdotool key ctrl+shift+l"

ora="xdotool key ctrl+shift+k"
ord="xdotool key ctrl+shift+j"

nme="xdotool key ctrl+shift+n"
dte="xdotool key ctrl+shift+d"
sze="xdotool key ctrl+shift+s"
tpe="xdotool key ctrl+shift+t"

wmctrl -r :ACTIVE: -N ${title}
i3-msg -q title_format "${title}"

$ora
$nme

case $dir in
	gavarch)
		$ora
		$nme
		$icn
		$nme
		;;
	Drive)
		$ora
		$nme
		$lst
		$nme
		;;
	dwn)
		$ord
		$dte
		$lst
		$dte
		;;
	pic)
		$ora
		$lst
		;;
	scr)
		$ora
		$lst
		;;
	gifs)
		$ora
		$icn
		;;
	meme)
		$ora
		$icn
		;;
	scrots)
		$ora
		$icn
		;;
	walls)
		$ora
		$icn
		;;
	vid)
		$ora
		$lst
		;;
	lecs)
		$ora
		$lst
		;;
	ex)
		$ora
		$lst
		;;
esac
