#!/bin/bash

name="$(xdotool getactivewindow getwindowname)"
name="${name/ - File Manager/}"
#title="${name/'gavarch'/'~'}"
title="${name/'/home/gavarch'/'~'}"
#title="${title/Pictures/pic}"
#title="${title/Videos/vid}"
#title="${title/scripts/scr}"
#title="${title/script/scr}"
#title="${title/Documents/doc}"
#title="${title/Downloads/dwn}"
#title="${title/Desktop/dsk}"
title="${title/i3rice-arch/dot}"
#title="${title/xinclude/xcnf}"
#title="${title/Templates/tmps}"

name="${name##*/}"

icn="ctrl+shift+i"
lst="ctrl+shift+l"

ora="ctrl+shift+k"
ord="ctrl+shift+j"

nme="ctrl+shift+n"
dte="ctrl+shift+d"
sze="ctrl+shift+s"
tpe="ctrl+shift+t"

wmctrl -r :ACTIVE: -N ${title}
i3-msg title_format "${title}"

xdotool key $ora
xdotool key $icn
xdotool key $nme

case $name in
#	gavarch)
#		xdotool key $ora
#		xdotool key $nme
#		xdotool key $icn
#		xdotool key $nme
#		;;
	Drive)
		xdotool key $ora
		xdotool key $nme
		xdotool key $lst
		xdotool key $nme
		;;
	dwn)
		xdotool key $ord
		xdotool key $dte
		xdotool key $lst
		xdotool key $dte
		;;
	pic)
		xdotool key $ora
		xdotool key $lst
		;;
	scr)
		xdotool key $ora
		xdotool key $lst
		;;
	gifs)
		xdotool key $ora
		xdotool key $icn
		;;
	meme)
		xdotool key $ora
		xdotool key $icn
		;;
	scrots)
		xdotool key $ora
		xdotool key $icn
		;;
	walls)
		xdotool key $ora
		xdotool key $icn
		;;
	vid)
		xdotool key $ora
		xdotool key $icn
		;;
esac

