#!/bin/bash

NME="$(xdotool getactivewindow getwindowname)"
NME="${NME/ - File Manager/}"
TTL="${NME/$HOME/'~'}"
#TTL="${TTL/i3rice-arch/dot}"
DIR="${NME##*/}"

_I="xdotool key ctrl+shift+i" _L="xdotool key ctrl+shift+l"

ora="xdotool key ctrl+shift+k" ord="xdotool key ctrl+shift+j"

nme="xdotool key ctrl+shift+n" dte="xdotool key ctrl+shift+d"
sze="xdotool key ctrl+shift+s" tpe="xdotool key ctrl+shift+t"

wmctrl -r :ACTIVE: -N ${TTL}
i3-msg -q title_format "${TTL}"

$ora; $nme

case $DIR in
	gavarch)    $_I             ;;
	Drive)      $_L             ;;
	dwn)        $ord; $dte; $_L ;;
	pic)        $_L             ;;
	favs)       $_I             ;;
	gifs)       $_I             ;;
	i3bg)       $_I             ;;
	meme)       $_I             ;;
	pics)       $_I             ;;
	scrots)     $_I             ;;
	SpotBright) $_I             ;;
	scr)        $_L             ;;
	gifs)       $_I             ;;
	meme)       $_I             ;;
	scrots)     $_I             ;;
	walls)      $_I             ;;
	vid)        $_L             ;;
	lecs)       $_L             ;;
	ex)         $_L             ;;
esac
