#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Mon  7 Oct 23:04:04 BST 2019
# source /home/gavarch/.config/user-dirs.dirs

SRC=$USER_SCR_DIR
TRG="${USER_REPO_DIR}/i3rice-arch.wiki"
BSE="${TRG}/_Sidebar.md_base"

help () {
cat << 'EOB'
# wikiud
- generates the script wikis shown in the sidebar

## Synopsis

```
wikiud
wikiud [--help|-h]
```
EOB
exit
}

while true; do
	case $1 in
		--help | -h ) help ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

cd $SRC
cat $BSE > ${BSE/_base/}

for i in $(ls -l | sed '/^d/d;/^total/d' | awk '{print $NF}'); do
	[[ -n $(grep '\-\-help' $i) ]] && {
		$i --help | awk -v SCR="${i}" -v TRG="${TRG}/doc/${i}.md" -v BSE="${BSE/_base/}" '
		BEGIN {
			c=0
			print "<div align=\"center\">" > TRG
			print "	<h1>" SCR "</h1>"     >> TRG
			print "</div>\n"              >> TRG
			print "### _[ master/scr/" SCR "](https://github.com/StillANixRookie/i3rice-arch/blob/master/scr/" SCR ")_" >> TRG
			print "### _[ raw ](https://raw.githubusercontent.com/StillANixRookie/i3rice-arch/master/scr/" SCR ")_" >> TRG
			print "|     | Table of Contents |" >> TRG
			print "|:---:|:--- |"               >> TRG
			print "- [" SCR "](https://github.com/StillANixRookie/i3rice-arch/wiki/" SCR ")" >> BSE
			}
		/^## / {
			c+=1
			key=$1;$1=""
			gsub(/^[ \t]+/, "", $0)
			OLD=$0
			gsub(/[ \t]/, "-", $0)
			NEW=tolower($0)
			print "|  "  c "  |[" OLD "](https://github.com/StillANixRookie/i3rice-arch/wiki/" SCR "#" NEW ")|" >> TRG
#			print "		- [" OLD "](https://github.com/StillANixRookie/i3rice-arch/wiki/" SCR "#" NEW ")" >> BSE
			}
		'
		$i --help | sed '/^# /d' >> ${TRG}/doc/${i}.md
		}
done
