#!/usr/bin/env bash

SRC="${XDG_PICTURES_DIR:-"$HOME/Pictures"}/xbm"
[[ -d $SRC ]] || {
mkdir -p $SRC
cat > $SRC/rain.xbm << 'EOB'
#define noname_width 16
#define noname_height 16
static char noname_bits[] = {
 0xc0,0x01,0xc0,0x01,0xe0,0x03,0xe0,0x12,0x60,0x13,0xc0,0x11,0x08,0x38,0x08,
 0x38,0x08,0x7c,0x1c,0x5c,0x1c,0x6c,0x3e,0x38,0x2e,0x00,0xb6,0x00,0x9c,0x00,
 0x80,0x00};
EOB
}


help () {
cat << 'EOB'
# NAME

__xbmer__ - `xsetroot` front-end for setting bitmap pattern
wallpapers.

# SYNOPSIS

```
xbmer [--pattern|-p <pattern>.xbm]
      [--bg|-b <backgroundhex>]
      [--fg|-f <foregroundhex>]
xber --help|-h
```

# DESCRIPTION

Obviously depends on `xsetroot`, and can't be used with
`compton`, until `hsetroot` can use `.xbm` files!  
`.xbm` files stored in `~/Pictures/xbm` by default.

EOB
exit
}

while true; do
	case $1 in
		--pattern | -p ) PAT="${2:-}" ; shift ;;
		--bg      | -b ) BG="${2:-}"  ; shift ;;
		--fg      | -f ) FG="${2:-}"  ; shift ;;
		--help ) help ;;
		-h ) help | sed -n "/^__/,/^$/p;/# SYNOPSIS/,/#/p" | sed 's/__.* - /\t/;/^#/d;/^$/d;s/```//g' && exit ;;
		-- ) shift ; break ;;
		*  ) break         ;;
	esac
	shift
done

FPT="${PAT:-"rain.xbm"}"
FBG="${BG:-"#FFFFFF"}"
FFG="${FG:-"#000000"}"

xsetroot -bitmap "${SRC}/${FPT}" -bg "$FBG" -fg "$FFG"
