#!/usr/bin/env bash

xfilesDir=$HOME/xrs

main () {
	cat ${xfilesDir}/colors/${finaltheme} > ${xfilesDir}/theme
	$HOME/scr/reloadconfs
	$HOME/scr/themer
	$HOME/scr/restartapps
}

theme () {
	theme=$(cat ${xfilesDir}/colors/.theme_list | $HOME/scr/i3menu -p \
		"Choose theme " -w 750 | awk '{print $NF}')
	echo $theme
	if [[ -z ${theme} ]]; then
		notify-send "No theme chosen" -i "~/scrpic/theme.png"
		:
	elif [[ ! -f ${xfilesDir}/colors/${theme} ]]; then
		notify-send "Theme don't exist" -i "~/scrpic/theme.png"
		:
	else
		notify-send "No variants" -i "~/scrpic/themepic.png"
		finaltheme=${theme}
		main
	fi
}

theme
