#!/usr/bin/env bash

bkd="\033[1;30m"
bkl="\033[1;30m"
red="\033[1;31m"
grn="\033[1;32m"
ylw="\033[1;33m"
blu="\033[1;34m"
gnt="\033[1;35m"
cyn="\033[1;36m"
wtd="\033[1;37m"
nrm="\033[0m"

txt=$2
#ops=$2
fnt="-f 3-d"
help () {
	echo -e "${blu}\n$(figlet $fnt -c "HELP"| \
		sed $'s/\*/\u2588/g;s/\//\u2592/g')${nrm}"
	echo ""
	echo ""
	echo "				c -- centre"
	echo "				s -- slant"
	echo "				b -- banner3"
	echo "				i -- larry3d"
	echo "				l -- letters"
	echo "				r -- roman"
	echo "				m -- smisome1"
	echo "				t -- trek"
	echo "				f -- speed"
	echo "				k -- smkeyboard"
}

if [[ $1 == "-h" ]]; then
	help
fi

while getopts :h:s:b:i:l:r:m:t:f:k:d: opts; do
	case "$opts" in
		s)
		fnt="-f slant"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c)"
		;;
		b)
		fnt="-f banner3"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c | \
			sed $'s/\#/\u2588/g')"
		;;
		i)
		fnt="-f larry3d"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c )"
		;;
		l)
		fnt="-f letters"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c )"
		;;
		r)
		fnt="-f roman"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c | \
			sed $'s/\#/\u2588/g')"
		;;
		m)
		fnt="-f smisome1"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c )"
		;;
		t)
		fnt="-f trek"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c | \
			sed $'s/B/\u2588/g;s/8/\u2588/g' | \
			sed $'s/K/\u258C/g;s/P/\u259B/g' | \
			sed $'s/d/\u259F/g;s/b/\u2599/g' | \
			sed $'s/\'/\u2598/g;s/`/\u259D/g' | \
			sed $'s/\./\u2597/g;s/_/\ /g')"
		;;
		f)
		fnt="-f speed"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c )"
		;;
		k)
		fnt="-f smkeyboard"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c )"
		;;
		d)
		fnt="-f 3-d"
		echo -e "${gnt}$(echo -e "$txt" | figlet ${fnt} -c | \
			sed $'s/\*/\u2588/g;s/\//\u2592/g')"
		;;
	esac
done
