#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')

bat=$(acpi | awk '{ print $4 }')

if [[ ${#bat} == 3 ]]; then
    rawbat=${bat:0:-1}
elif [[ ${bat} == "100%" ]]; then
    rawbat="100"
else
    rawbat=${bat:0:-2}
fi

statu=$(acpi | awk '{ print $3 }')
tim=$(acpi | awk '{ print $5 }')

if [[ -z "$tim" ]]; then
    tim2=
else
    tim2="${tim:0:-3}"
fi

if [[ $statu == "Charging," ]]; then
    stat="CHR"
elif [[ $statu == "Unknown," ]]; then
    stat="FULL"
else
    stat="DIS"
fi

if [[ $rawbat -le 50 ]]; then
    echo "<span background=\"#b58900\" foreground=\"$black\"> BAT $rawbat% $stat $tim2 </span>"
elif [[ $rawbat -le 25 ]]; then
    echo "<span background=\"#dc322f\" foreground=\"$black\"> BAT $rawbat% $stat $tim2 </span>"
elif [[ $rawbat -le 75 ]]; then
    echo "<span background=\"$white\" foreground=\"$black\"> BAT $rawbat% $stat $tim2 </span>"
elif [[ $statu == "Unknown," ]]; then
    echo "<span background=\"$blue\" foreground=\"$black\"> BAT $rawbat% $stat $tim2</span>"
else
    echo "<span background=\"$blue\" foreground=\"$black\"> BAT $rawbat% $stat $tim2 </span>"
fi
