#!/bin/bash

stat=$(xset -q | grep 'Caps Lock:' | awk '{print $4}')

if [[ $stat == "on" ]]; then
    echo "<span background=\"$(bash ~/scripts/getxcolors magenta)\" foreground=\"$(bash ~/scripts/getxcolors black)\"> CAPS LOCK </span>"
else
    :
fi
