#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')

stat=$(xset -q | grep 'Caps Lock:' | awk '{print $4}')

if [[ $stat == "on" ]]; then
    echo "<span background=\"$magenta\" foreground=\"$black\"> CAPS LOCK </span>"
else
    :
fi
