#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')

idle=$(sar 1 1|grep 'Average'|awk '{print $NF}')
let " cpu = 100 - ${idle:0:-3} "

if [[ $cpu -ge 80 ]]; then
    echo "<span background=\"#ff0000\" foreground=\"$black\"> CPU $cpu% </span>"
elif [[ $cpu -ge 50 ]]; then
    echo "<span background=\"#ffff00\" foreground=\"$black\"> CPU $cpu% </span>"
else
    echo "<span background=\"$yellow\" foreground=\"$black\"> CPU $cpu% </span>"
fi
