#!/bin/bash

file=$1
xelatex -interaction=nonstopmode -shell-escape ${file}.tex
if [[ -e ${file}.bcf ]]; then
	biber ${file}.bcf
	xelatex -interaction=nonstopmode -shell-escape ${file}.tex
	xelatex -interaction=nonstopmode -shell-escape ${file}.tex
else
    :
fi
if [[ -e ${file}.nlo ]]; then
    makeindex ${file}.nlo -s nomencl.ist -o ${file}.nls
	xelatex -interaction=nonstopmode -shell-escape ${file}.tex
else
    :
fi
