#!/bin/bash

yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')

DIR="${BLOCK_INSTANCE:-$HOME}"

avail=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $4}')
usep=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $5}')
use=${usep:0:-1}

if [[ $use -ge 90 ]]; then
    echo "<span background=\"$red\" foreground=\"$black\"> HOME $avail </span>"
else
    echo "<span background=\"$yellow\" foreground=\"$black\"> HOME $avail </span>"
fi
