#!/bin/bash

DIR="${BLOCK_INSTANCE:-$HOME}"

avail=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $4}')
usep=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $5}')
use=${usep:0:-1}

if [[ $use -ge 90 ]]; then
    echo "<span background=\"#dc322f\" foreground=\"$(bash ~/scripts/getxcolors black)\"> HOME $avail </span>"
else
    echo "<span background=\"$(bash ~/scripts/getxcolors blue)\" foreground=\"$(bash ~/scripts/getxcolors black)\"> HOME $avail </span>"
fi
