#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')

DIR="${BLOCK_INSTANCE:-$HOME}"

avail=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $4}')
usep=$(df -h -P -l "$DIR"|grep 'dev'|awk '{print $5}')
use=${usep:0:-1}

if [[ $use -ge 90 ]]; then
    echo "<span background=\"#dc322f\" foreground=\"$black\">  $avail </span>"
else
    echo "<span background=\"$blue\" foreground=\"$black\">  $avail </span>"
fi
