#!/usr/bin/env bash

ignore="grep -v 'sda' | grep -v 'sdb'"

mountd () {
	chosen=$(lsblk -ro 'name,size,type,mountpoint' | grep -v 'sda' | grep -v 'sdb' | grep -v '/' | grep 'part' | bash ~/scripts/i3menu "Mount which drive?:")
	[[ -z $chosen ]] && exit 1
	mountpoint=$(ls /run/media/${HOME:6} | bash ~/scripts/i3menu "Which mountpoint?:")
	sudo mount /dev/$(echo $chosen | awk '{print $1}') /run/media/${HOME:6}/$mountpoint
	sudo chmod 0777 /run/media/${HOME:6}/$mountpoint
	ranger /run/media/${HOME:6}/$mountpoint
}

unmountd () {
	chosen=$(lsblk -ro 'name,size,type,mountpoint' | grep -v 'sda' | grep -v 'sdb' | grep '/' | grep 'part' | bash ~/scripts/i3menu "Mount which drive?:")
	[[ -z $chosen ]] && exit 1
	sudo umount /dev/$(echo $chosen | awk '{print $1}')
}

case "$1" in
	mount) mountd ;;
	unmount) unmountd ;;
esac
