#!/usr/bin/env bash

txt=$2
#ops=$2
fnt="-f 3-d"
help () {
	if [[ -z ${txt} ]]; then
		echo "                                     HELP                                      "
		echo ""
		echo ""
		echo "------------------------------------OPTIONS------------------------------------"
		echo ""
		echo "                                c    centre"
		echo "                                s    slant"
		echo "                                b    banner3"
		echo "                                i    larry3d"
		echo "                                l    letters"
		echo "                                r    roman"
		echo "                                m    smisome1"
		echo "                                t    trek"
		echo "                                f    speed"
		echo "                                k    smkeyboard"
	fi
	exit
}

while getopts :h:s:b:i:l:r:m:t:f:k:c: opts; do
	case "$opts" in
		h) help ;;
		s) figops=${fnt/3-d/slant} ;;
		b) figops=${fnt/3-d/banner3} ;;
		i) figops=${fnt/3-d/larry3d} ;;
		l) figops=${fnt/3-d/letters} ;;
		r) figops=${fnt/3-d/roman} ;;
		m) figops=${fnt/3-d/smisome1} ;;
		t) figops=${fnt/3-d/trek} ;;
		f) figops=${fnt/3-d/speed} ;;
		k) figops=${fnt/3-d/smkeyboard} ;;
		c) figops+=" -c" ;;
	esac
done

[[ -n $txt ]] && echo "$(tput bold)$(echo -e "$txt" | figlet ${figops})" | lolcat

#if [[ $ops == *[s]* ]]; then
#	figops=$(echo ${fnt/3-d/slant})
#elif [[ $ops == *[b]* ]]; then
#	figops=$(echo ${fnt/3-d/banner3})
#elif [[ $ops == *[i]* ]]; then
#	figops=$(echo ${fnt/3-d/larry3d})
#elif [[ $ops == *[l]* ]]; then
#	figops=$(echo ${fnt/3-d/letters})
#elif [[ $ops == *[r]* ]]; then
#	figops=$(echo ${fnt/3-d/roman})
#elif [[ $ops == *[m]* ]]; then
#	figops=$(echo ${fnt/3-d/smisome1})
#elif [[ $ops == *[t]* ]]; then
#	figops=$(echo ${fnt/3-d/trek})
#elif [[ $ops == *[f]* ]]; then
#	figops=$(echo ${fnt/3-d/speed})
#elif [[ $ops == *[k]* ]]; then
#	figops=$(echo ${fnt/3-d/smkeyboard})
#fi

#if [[ $ops == *[c]* ]]; then
#	figops+=" -c"
#fi

#if [[ -z $ops ]]; then
#	echo "$(tput bold)$(echo -e "$txt" | figlet -f 3-d -c | tr '*' '#' | tr '/' '"')" | lolcat
#	if [[ $txt == "help" ]]; then
#		echo "------------------------------------OPTIONS------------------------------------"
#		echo "                                c    centre"
#		echo "                                s    slant"
#		echo "                                b    banner3"
#		echo "                                i    larry3d"
#		echo "                                l    letters"
#		echo "                                r    roman"
#		echo "                                m    smisome1"
#		echo "                                t    trek"
#		echo "                                f    speed"
#		echo "                                k    smkeyboard"
#	fi
#else
#	echo "$(tput bold)$(echo -e "$txt" | figlet ${figops})" | lolcat
#fi
