#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')

color=${1?Error: no input.}

echo "${!color}"
