#!/usr/bin/env bash

cd

repo=$(cat $SCRIPTDIR/githubrepos | $SCRIPTDIR/i3menu "Update which repo?:")

if [[ -z $repo ]]; then
	:
else
	cd $GITDIR/$repo
	notify-send "Updating your $repo git repo..." -i $SCRIPTPIC/gitwhite.png
	git add .
	git commit -m "$(date +"%c")"
	git fetch
	git merge origin/master
	git push -u origin master
	cd
	notify-send "... $repo repo updated." -i $SCRIPTPIC/gitwhite.png
fi
