#!/usr/bin/env bash

stkpar=$1
declare -i stkchl=1
marks=$(i3-msg -t get_marks)

if [[ $marks != *"_sticky_$stkpar"* ]]; then
	markfoc="i3-msg [con_id=__focused__] mark _sticky_$stkpar"
	echo True
elif [[ $marks =~ "_sticky_$stkpar" ]]; then
	while [[ $marks =~ "_sticky_$stkpar_$stkchl" ]]; do
		stkchl=$stkchl+1
	done
	markfoc="i3-msg [con_id=__focused__] mark _sticky_${stkpar}_${stkchl}"
fi

${markfoc}
