#!/usr/bin/env bash

dir=$1
cd $HOME
i3-msg -t get_tree > get_tree
sed 's/},{/\n/g' get_tree > tree_new
focussed=$(cat tree_new | grep '"focused":true')
tabbed=$(cat tree_new | grep 'tabbed')
echo $tabbed

geometry=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry' | awk '{print $NF}' | tr 'x' ' ')
width=$(echo $geometry | awk '{print $1}')
height=$(echo $geometry | awk '{print $2}')
geo=\"width\":${width},\"height\":${height}

if [[ $tabbed =~ $geo ]]; then
    i3-msg "focus parent; focus $dir; focus child"
else
    i3-msg focus $dir
fi

rm get_tree tree_new
