#!/bin/bash

# OA: Gavin Vales
# CREATED: Sat 16 Mar 20:08:40 GMT 2019

prompt="${1}"

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
font=$(xrdb -query | grep 'URxvt.font' | awk '{print $NF}')
dmenucolors="-fn "${font:4}" -nb "$black" -nf "$white" -sf "$black" -sb "$blue""

dmenu -i -p "${prompt}" $dmenucolors
