#!/usr/bin/env bash

# OA: Gavin Vales
# CREATED: Sat 16 Mar 20:08:40 GMT 2019

prompt="${1}"

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
accent=$(xrdb -query | grep '*color5' | awk '{print $NF}')
font=$(xrdb -query | grep 'URxvt.font' | awk '{print $NF}')
font=${font#*:}
font=${font%:*}
dmenucolors="-fn "${font}:size=15" -nb "$accent" -nf "$black" -sf "$accent" -sb "$white""

dmenu -i -p "${prompt}" $dmenucolors
