#!/bin/bash

# OA: Gavin Vales
# CREATED: Tue 29 Jan 11:32:27 GMT 2019

opr=${1}
delta=${2}

width=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry:' | sed 's/x/\ /g' | awk '{print $2}')
height=$(xdotool getactivewindow getwindowgeometry | grep 'Geometry:' | sed 's/x/\ /g' | awk '{print $3}')

xpos=$(xdotool getactivewindow getwindowgeometry | grep 'Position:' | sed 's/,/\ /g' | awk '{print $2}')
ypos=$(xdotool getactivewindow getwindowgeometry | grep 'Position:' | sed 's/,/\ /g' | awk '{print $3}')

xscr=$(xdotool getdisplaygeometry | awk '{print $1}')
yscr=$(xdotool getdisplaygeometry | awk '{print $2}')

xsc2=$(expr $xscr / 2)
ysc2=$(expr $yscr / 2)

if [[ $xpos -lt $xsc2 ]] && [[ $ypos -lt $ysc2 ]]; then
	echo 'grab bottomright'
	i3-msg resize ${opr} right 	${delta} px or ${delta} ppt
	i3-msg resize ${opr} down 	${delta} px or ${delta} ppt
elif [[ $xpos -lt $xsc2 ]] && [[ $ypos -gt $ysc2 ]]; then
	echo 'grab topright'
	i3-msg resize ${opr} right 	${delta} px or ${delta} ppt
	i3-msg resize ${opr} up 		${delta} px or ${delta} ppt
elif [[ $(expr $xpos + $width) -lt $xsc2 ]] && [[ $(expr $ypos + $height) -gt $ysc2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${opr} right 	${delta} px or ${delta} ppt
	i3-msg resize ${opr} up 		${delta} px or ${delta} ppt
elif [[ $(expr $xpos + $width) -gt $xsc2 ]] && [[ $(expr $ypos + $height) -gt $ysc2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${opr} left ${delta} px or ${delta} ppt
	i3-msg resize ${opr} up 	${delta} px or ${delta} ppt
elif [[ $xpos -gt $xsc2 ]] && [[ $ypos -lt $ysc2 ]]; then
	echo 'grab bottomleft'
	i3-msg resize ${opr} left ${delta} px or ${delta} ppt
	i3-msg resize ${opr} down ${delta} px or ${delta} ppt
elif [[ $xpos -gt $xsc2 ]] && [[ $ypos -gt $ysc2 ]]; then
	echo 'grab topleft'
	i3-msg resize ${opr} left ${delta} px or ${delta} ppt
	i3-msg resize ${opr} up 	${delta} px or ${delta} ppt
else
	echo 'grab bottomright'
	i3-msg resize ${opr} right 	${delta} px or ${delta} ppt
	i3-msg resize ${opr} down 	${delta} px or ${delta} ppt
fi

#echo "$width $height"
#echo "$xpos $ypos"
#echo "$xscr $yscr"
#echo "$xsc2 $ysc2"
