#!/usr/bin/env bash

atsynDir="$HOME/.atom/packages/rice-syntax/styles"

blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

(
	cd $atsynDir || exit 1
	
	echo "// These colors are specific to the theme. Do not use in a package!" > colors.less
	echo "@very-light-gray: $whitel;" >> colors.less
	echo "@light-gray: $whited;" >> colors.less
	echo "@gray: $blackl;" >> colors.less
	echo "@dark-gray: $blackd;" >> colors.less
	echo "@very-dark-gray: $blackd;" >> colors.less
	echo "@cyan: $cyan;" >> colors.less
	echo "@blue: $blue;" >> colors.less
	echo "@purple: $magenta;" >> colors.less
	echo "@green: $green;" >> colors.less
	echo "@red: $red;" >> colors.less
	echo "@orange: $yellow;" >> colors.less
	echo "@light-orange: $yellow;" >> colors.less
)
