#!/bin/bash

# align
# color
# background
# border
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

blocksDir="$HOME/scripts/"

blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

(
cd "$blocksDir" || exit 1

echo -e "# i3blocks config file" > i3blocks.conf

echo "# Global properties" >> i3blocks.conf
echo "command=~/scripts2/\$BLOCK_NAME" >> i3blocks.conf
echo "#command=/usr/lib/i3blocks/\$BLOCK_NAME" >> i3blocks.conf
echo "color=$whited" >> i3blocks.conf
echo "separator_block_width=15" >> i3blocks.conf
echo -e "markup=pango\n" >> i3blocks.conf

#echo "#[mpgui]" >> i3blocks.conf
#echo "#command=bash ~/scripts/mpgui" >> i3blocks.conf
#echo "#interval=1" >> i3blocks.conf
#echo -e "full_text=\n" >> i3blocks.conf
#
#echo -e "[separator]\n" >> i3blocks.conf

echo "[mpc]" >> i3blocks.conf
echo "command=bash ~/scripts/mpc" >> i3blocks.conf
echo "label=MPD" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "color=$magenta" >> i3blocks.conf
echo -e "full_text=\n" >> i3blocks.conf

echo -e "[separator]\n" >> i3blocks.conf

echo "[brightness]" >> i3blocks.conf
echo "command=bash ~/scripts/brightness" >> i3blocks.conf
echo "label=BL" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "separator=false" >> i3blocks.conf
echo -e "color=$cyan\n" >> i3blocks.conf

echo "[volume]" >> i3blocks.conf
echo "label=VOL" >> i3blocks.conf
echo "instance=Master" >> i3blocks.conf
echo "color=$cyan" >> i3blocks.conf
echo "#instance=PCM" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "signal=10" >> i3blocks.conf
echo -e "full_text=\n" >> i3blocks.conf

echo -e "[separator]\n" >> i3blocks.conf

echo "[disk]" >> i3blocks.conf
echo "label=HOME" >> i3blocks.conf
echo "#instance=/mnt/data" >> i3blocks.conf
echo "interval=5" >> i3blocks.conf
echo "color=$yellow" >> i3blocks.conf
echo -e "separator=false\n" >> i3blocks.conf

echo "[memory]" >> i3blocks.conf
echo "label=RAM" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo -e "separator=false\n" >> i3blocks.conf

#echo "# If the instance is not specified, use the interface used for default route." >> i3blocks.conf
#echo "# The address can be forced to IPv4 or IPv6 with -4 or -6 switches." >> i3blocks.conf
#echo "#[iface]" >> i3blocks.conf
#echo "##instance=wlan0" >> i3blocks.conf
#echo "#color=#00FF00" >> i3blocks.conf
#echo "#interval=5" >> i3blocks.conf
#echo -e "##separator=false\n" >> i3blocks.conf

echo "[cpu_usage]" >> i3blocks.conf
echo "label=CPU" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo -e "separator=false\n" >> i3blocks.conf

echo "[cpu-temp]" >> i3blocks.conf
echo "command=bash ~/scripts/temp" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "markup=pango" >> i3blocks.conf
echo -e "full_text=\n" >> i3blocks.conf

echo -e "[separator]\n" >> i3blocks.conf

#echo "#[load_average]" >> i3blocks.conf
#echo "#interval=10" >> i3blocks.conf

echo "[wifi]" >> i3blocks.conf
echo "label=NET:" >> i3blocks.conf
echo "instance=wlp3s0" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "color=$whited" >> i3blocks.conf
echo -e "separator=false\n" >> i3blocks.conf

echo "[bandwidth]" >> i3blocks.conf
echo "instance=eth0" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo "color=$whited" >> i3blocks.conf
echo -e "full_text=\n" >> i3blocks.conf

echo -e "[separator]\n" >> i3blocks.conf

echo "[battery]" >> i3blocks.conf
echo "label=BAT" >> i3blocks.conf
echo "#instance=12" >> i3blocks.conf
echo "color=$blue" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
echo -e "separator=false\n" >> i3blocks.conf

echo "[time]" >> i3blocks.conf
echo "label=TD" >> i3blocks.conf
echo "command=date '+%d-%m, %H:%M:%S'" >> i3blocks.conf
echo "color=#ffffff" >> i3blocks.conf
echo "interval=1" >> i3blocks.conf
)
