#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
#green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
#yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
#red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')

cd
echo "#" > .dmenurc
echo "# ~/.dmenurc" >> .dmenurc
echo "#" >> .dmenurc
echo "" >> .dmenurc
echo "DMENU_FN=\"Ubuntu Mono:size=13\"" >> .dmenurc
echo "DMENU_NB=\"$black\"" >> .dmenurc
echo "DMENU_NF=\"$white\"" >> .dmenurc
echo "DMENU_SB=\"$blue\"" >> .dmenurc
echo "DMENU_SF=\"$black\"" >> .dmenurc
echo "## command for the terminal application to be used:" >> .dmenurc
echo "TERMINAL_CMD=\"terminal -e\"" >> .dmenurc
echo "## export our variables" >> .dmenurc
echo "DMENU_OPTIONS=\"-fn \$DMENU_FN -nb \$DMENU_NB -nf \$DMENU_NF -sf \$DMENU_SF -sb \$DMENU_SB\"" >> .dmenurc
