#!/bin/bash

Dir=$HOME/Templates/css
blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
blackl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
green=$(xrdb -query | grep '*color2' | awk '{print $NF}')
yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
whited=$(xrdb -query | grep '*color7' | awk '{print $NF}')
whitel=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
magenta=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

(
    cd $Dir || exit 1

    echo "pre," > fixedsys.css
    echo "code {" >> fixedsys.css
    echo "  font-family: \"Fixedsys Mono\", Menlo, Monaco, \"Courier New\", monospace;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "pre {" >> fixedsys.css
    echo "  padding: .5rem;" >> fixedsys.css
    echo "  line-height: 1.25;" >> fixedsys.css
    echo "  overflow-x: scroll;" >> fixedsys.css
    echo "  background-color: $yellow;" >> fixedsys.css
    echo "  color: $blackd;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "@media print {" >> fixedsys.css
    echo "  *," >> fixedsys.css
    echo "  *:before," >> fixedsys.css
    echo "  *:after {" >> fixedsys.css
    echo "    background: transparent !important;" >> fixedsys.css
    echo "    color: $blackd !important;" >> fixedsys.css
    echo "    box-shadow: none !important;" >> fixedsys.css
    echo "    text-shadow: none !important;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  a," >> fixedsys.css
    echo "  a:visited {" >> fixedsys.css
    echo "    text-decoration: underline;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  a[href]:after {" >> fixedsys.css
    echo "    content: \" (\" attr(href) \")\";" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  abbr[title]:after {" >> fixedsys.css
    echo "    content: \" (\" attr(title) \")\";" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  a[href^=\"#\"]:after," >> fixedsys.css
    echo "  a[href^=\"javascript:\"]:after {" >> fixedsys.css
    echo "    content: \"\";" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  pre," >> fixedsys.css
    echo "  blockquote {" >> fixedsys.css
    echo "    border: 1px solid $whited;" >> fixedsys.css
    echo "    page-break-inside: avoid;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  thead {" >> fixedsys.css
    echo "    display: table-header-group;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  tr," >> fixedsys.css
    echo "  img {" >> fixedsys.css
    echo "    page-break-inside: avoid;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  img {" >> fixedsys.css
    echo "    max-width: 100% !important;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  p," >> fixedsys.css
    echo "  h2," >> fixedsys.css
    echo "  h3 {" >> fixedsys.css
    echo "    orphans: 3;" >> fixedsys.css
    echo "    widows: 3;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "  h2," >> fixedsys.css
    echo "  h3 {" >> fixedsys.css
    echo "    page-break-after: avoid;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "a," >> fixedsys.css
    echo "a:visited {" >> fixedsys.css
    echo "  color: $blue;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "a:hover," >> fixedsys.css
    echo "a:focus," >> fixedsys.css
    echo "a:active {" >> fixedsys.css
    echo "  color: $magenta;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo ".retro-no-decoration {" >> fixedsys.css
    echo "  text-decoration: none;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "html {" >> fixedsys.css
    echo "  font-size: 12px;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "@media screen and (min-width: 32rem) and (max-width: 48rem) {" >> fixedsys.css
    echo "  html {" >> fixedsys.css
    echo "    font-size: 15px;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "@media screen and (min-width: 48rem) {" >> fixedsys.css
    echo "  html {" >> fixedsys.css
    echo "    font-size: 16px;" >> fixedsys.css
    echo "  }" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "body {" >> fixedsys.css
    echo "  line-height: 1.85;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "p," >> fixedsys.css
    echo ".retro-p {" >> fixedsys.css
    echo "  font-size: 1rem;" >> fixedsys.css
    echo "  margin-bottom: 1.3rem;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h1," >> fixedsys.css
    echo ".retro-h1," >> fixedsys.css
    echo "h2," >> fixedsys.css
    echo ".retro-h2," >> fixedsys.css
    echo "h3," >> fixedsys.css
    echo ".retro-h3," >> fixedsys.css
    echo "h4," >> fixedsys.css
    echo ".retro-h4 {" >> fixedsys.css
    echo "  margin: 1.414rem 0 .5rem;" >> fixedsys.css
    echo "  font-weight: inherit;" >> fixedsys.css
    echo "  line-height: 1.42;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h1," >> fixedsys.css
    echo ".retro-h1 {" >> fixedsys.css
    echo "  margin-top: 0;" >> fixedsys.css
    echo "  font-size: 2rem;" >> fixedsys.css
    echo "  font-weight: bold;" >> fixedsys.css
    echo "  text-align: center;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h2," >> fixedsys.css
    echo ".retro-h2 {" >> fixedsys.css
    echo "  font-size: 1.5rem;" >> fixedsys.css
    echo "  font-weight: bold;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h3," >> fixedsys.css
    echo ".retro-h3 {" >> fixedsys.css
    echo "  font-size: 1rem;" >> fixedsys.css
    echo "  font-weight: bold;" >> fixedsys.css
    echo "  font-style: italic;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h4," >> fixedsys.css
    echo ".retro-h4 {" >> fixedsys.css
    echo "  font-size: .5rem;" >> fixedsys.css
    echo "  font-style: italic;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h5," >> fixedsys.css
    echo ".retro-h5 {" >> fixedsys.css
    echo "  font-size: .25rem;" >> fixedsys.css
    echo "  font-style: italic;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "h6," >> fixedsys.css
    echo ".retro-h6 {" >> fixedsys.css
    echo "  font-size: .15rem;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "small," >> fixedsys.css
    echo ".retro-small {" >> fixedsys.css
    echo "  font-size: .05rem;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo ".title {" >> fixedsys.css
    echo "  font-size: 4rem;" >> fixedsys.css
    echo "  font-weight: bold;" >> fixedsys.css
    echo "  text-align: center;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo ".subtitle {" >> fixedsys.css
    echo "  font-size: 2rem;" >> fixedsys.css
    echo "  font-weight: bold;" >> fixedsys.css
    echo "  text-align: center;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo ".author {" >> fixedsys.css
    echo "  font-size: 1rem;" >> fixedsys.css
    echo "  font-style: italic;" >> fixedsys.css
    echo "  text-align: center;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo ".date {" >> fixedsys.css
    echo "  font-size: 1rem;" >> fixedsys.css
    echo "  text-align: center;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "/* https://github.com/mrmrs/fluidity */" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "img," >> fixedsys.css
    echo "canvas," >> fixedsys.css
    echo "iframe," >> fixedsys.css
    echo "video," >> fixedsys.css
    echo "svg," >> fixedsys.css
    echo "select," >> fixedsys.css
    echo "textarea {" >> fixedsys.css
    echo "  max-width: 100%;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "html," >> fixedsys.css
    echo "body {" >> fixedsys.css
    echo "  background-color: $blackd;" >> fixedsys.css
    echo "  min-height: 100%;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "html {" >> fixedsys.css
    echo "  font-size: 18px;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "body {" >> fixedsys.css
    echo "  color: $whited;" >> fixedsys.css
    echo "  font-family: \"Fixedsys Mono\";" >> fixedsys.css
    echo "  line-height: 1.45;" >> fixedsys.css
    echo "  margin: 6rem auto 1rem;" >> fixedsys.css
    echo "  max-width: 48rem;" >> fixedsys.css
    echo "  padding: .25rem;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "pre {" >> fixedsys.css
    echo "  background-color: $yellow;" >> fixedsys.css
    echo "  color: $blackd;" >> fixedsys.css
    echo "}" >> fixedsys.css
    echo "" >> fixedsys.css
    echo "blockquote {" >> fixedsys.css
    echo "  border-left: 3px solid $blue;" >> fixedsys.css
    echo "  border-bottom: 3px solid $blue;" >> fixedsys.css
    echo "  padding-left: 1rem;" >> fixedsys.css
    echo "  padding-right: 1rem;" >> fixedsys.css
    echo "}" >> fixedsys.css
)
