#!/bin/bash

bashDir=$HOME/scripts
pyDir=$HOME/Documents/python
file=$1
subdir=$2
ft=$3

cd $HOME

if [[ ! -d $pyDir ]]; then
	mkdir $pyDir
	cd $pyDir
else
	cd $pyDir
fi

if [[ -n $subdir ]]; then
	if [[ ! -d $subdir ]]; then
		mkdir $subdir
		cd $subdir
	else
		cd $subdir
	fi
else
	:
fi

if [[ -f $file ]]; then
	vim $file
else
	echo "# OA: Gavin Vales" > $file
	echo "# CREATED: $(date)" >> $file
	echo "" >> $file
	echo "import numpy as np" >> $file
	echo "import matplotlib.pyplot as py" >> $file
	echo "" >> $file
	echo "" >> $file
	chmod +x $file
	vim $file
fi
