#!/bin/bash

# OA: Gavin Vales
# CREATED: Sat 30 Mar 15:29:03 GMT 2019

bkd=$(xrdb -query | grep '*color0' | awk '{print $NF}')
bkl=$(xrdb -query | grep '*color8' | awk '{print $NF}')
grn=$(xrdb -query | grep '*color2' | awk '{print $NF}')
ylw=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
wtd=$(xrdb -query | grep '*color7' | awk '{print $NF}')
wtl=$(xrdb -query | grep '*color15' | awk '{print $NF}')
blu=$(xrdb -query | grep '*color4' | awk '{print $NF}')
gnt=$(xrdb -query | grep '*color5' | awk '{print $NF}')
cyn=$(xrdb -query | grep '*color6' | awk '{print $NF}')

echo "\"set guifont=Ubuntu\ Mono\ Regular:h20" > $HOME/.guivimrc
echo "set guifont=Iosevka\ 15" >> $HOME/.guivimrc
echo "set guioptions-=m \"remove menu bar" >> $HOME/.guivimrc
echo "set guioptions-=T \"remove toolbar" >> $HOME/.guivimrc
echo "set guioptions-=r \"remove right-hand scroll bar" >> $HOME/.guivimrc
echo "set guioptions-=L \"remove left-hand scroll bar" >> $HOME/.guivimrc
echo "colorscheme default" >> $HOME/.guivimrc
echo "set linespace=5" >> $HOME/.guivimrc
echo "\"set lines=999 columns=999" >> $HOME/.guivimrc
echo "\"au GUIEnter * simalt ~x" >> $HOME/.guivimrc
echo "" >> $HOME/.guivimrc
echo "hi Normal guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Title gui=bold guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi StatusLineTerm guifg=${bkd} guibg=${grn}" >> $HOME/.guivimrc
echo "hi StatusLineTermNC guifg=${wtl} guibg=${grn}" >> $HOME/.guivimrc
echo "hi LineNr gui=none guifg=${wtd} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi CursorLineNr gui=bold guifg=${red} guibg=${bkl}" >> $HOME/.guivimrc
echo "hi SpecialKey guifg=${bkl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi ModeMsg gui=bold guifg=${wtl}" >> $HOME/.guivimrc
echo "hi Cursor guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi ColorColumn guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi CursorLine gui=none guibg=${bkl}" >> $HOME/.guivimrc
echo "hi Visual guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi VisualNOS guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi Type gui=bold guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Identifier gui=italic guifg=${ylw} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Comment gui=italic guifg=${wtd} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Folded gui=italic guifg=${wtd} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Constant gui=italic guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Special gui=bold guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Statement gui=bold guifg=${wtl} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi PreProc gui=none guifg=${blu} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi MatchParen gui=bold guifg=${ylw} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Search gui=none guifg=${bkd} guibg=${ylw}" >> $HOME/.guivimrc
echo "hi Error gui=none guifg=${red} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi EndOfBuffer gui=none guifg=${bkd} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi SpellBad gui=underline,bold guifg=${red} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi SpellCap gui=underline,bold guifg=${blu} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi SpellRare gui=underline,bold guifg=${gnt} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi SpellLocal gui=underline,bold guifg=${cyn} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi Pmenu gui=none guifg=${blu} guibg=${wtl}" >> $HOME/.guivimrc
echo "hi PmenuSel gui=none guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi PmenuSbar gui=none guifg=${blu} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi PmenuThumb gui=none guifg=${grn} guibg=${grn}" >> $HOME/.guivimrc
echo "hi TabLine gui=none guifg=${blu} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi TabLineSel gui=none guifg=${bkd} guibg=${blu}" >> $HOME/.guivimrc
echo "hi TabLineFill gui=none guifg=${blu} guibg=${bkd}" >> $HOME/.guivimrc
echo "hi User1 guibg=${red} guifg=${bkd}" >> $HOME/.guivimrc
echo "hi User2 guibg=${ylw} guifg=${bkd}" >> $HOME/.guivimrc
echo "hi User3 guibg=${grn} guifg=${bkd}" >> $HOME/.guivimrc
echo "hi User4 guibg=${bkl} guifg=${bkd}" >> $HOME/.guivimrc
echo "hi User5 guibg=${blu} guifg=${bkd}" >> $HOME/.guivimrc
echo "hi User6 guibg=${gnt} guifg=${bkd}" >> $HOME/.guivimrc
