#!/bin/bash

playing=$(mpc current)

if [ -z "$playing" ]
then
	:
else
	echo "<span background=\"$(bash ~/scripts/getxcolors magenta)\" foreground=\"$(bash ~/scripts/getxcolors black)\"> MPD ${playing} </span>"
fi

case $BLOCK_BUTTON in
  3) mpc prev ;;  # next song
  2) mpc toggle ;;  # next song
  1) mpc next ;;  # next song
esac
