#!/bin/bash

playername=$(mpris-ctl info "%player_name")
trackname=$(mpris-ctl info "%track_name")
tracknumber=$(mpris-ctl info "%track_number")
tracklength=$(mpris-ctl info "%track_length")
artistname=$(mpris-ctl info "%artist_name")
albumname=$(mpris-ctl info "%album_name")
albumartist=$(mpris-ctl info "%album_artist")
playstatus=$(mpris-ctl info "%play_status")
shuffle=$(mpris-ctl info "%shuffle")
volume=$(mpris-ctl info "%volume")
loopstatus=$(mpris-ctl info "%loop_status")
position=$(mpris-ctl info "%position")
bitrate=$(mpris-ctl info "%bitrate")
comment=$(mpris-ctl info "%comment")
full=$(mpris-ctl info "%full")

playing="$playername: $trackname - $artistname"

if [ -z $playstatus ]
then
	:
else
	echo "<span background=\"$(bash ~/scripts/getxcolors magenta)\" foreground=\"$(bash ~/scripts/getxcolors black)\"> ${playing:0:50} </span>"
fi

case $BLOCK_BUTTON in
  3) playerctl previous ;;  # next song
  2) playerctl play-pause ;;  # next song
  1) playerctl next ;;  # next song
esac
