#!/bin/bash

all=$(xrandr -q | grep 'connected' | awk '{print $1}')
conn=$(xrandr -q | grep ' connected' | awk '{print $1}')
declare -a disconn=($(xrandr -q | grep 'disconnected' | awk '{print $1}'))
lenconn=$(xrandr -q | grep ' connected' | awk '{print $1}' | wc -l)

 
mode=$(echo -e "1 Monitor\n2 Monitors\n3 Monitors\nARandR" | bash $HOME/scripts/i3menu "Choose mode:")

if [[ $lenconn == 1 ]]; then
	xrandr --output "$conn" --primary --auto
	for i in "${disconn[@]}"
	do
		xrandr --output "$i" --off
	done
elif [[ $mode == "1 Monitor" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | bash $HOME/scripts/i3menu "Choose primary monitor:")
	declare -a off=($(echo $all | tr ' ' '\n' | grep -v "$primary"))
	xrandr --output "$primary" --primary --auto
	for i in "${off[@]}"
	do
		xrandr --output "$i" --off
	done
elif [[ $mode == "2 Monitors" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | bash $HOME/scripts/i3menu "Choose primary monitor:")
	second=$(echo $conn | tr ' ' '\n' | grep -v "$primary")
	dir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | bash $HOME/scripts/i3menu "Choose position of second monitor:")
	xrandr --output "$primary" --primary --auto --output "$second" --"$dir" "$primary" --auto
elif [[ $mode == "3 Monitors" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | bash $HOME/scripts/i3menu "Choose primary monitor:")
	second=$(echo $conn | tr ' ' '\n' | grep -v "$primary" | bash $HOME/scripts/i3menu "Choose 2nd monitor:")
	third=$(echo $conn | tr ' ' '\n' | grep -v "$primary" | grep -v "$second")
	seconddir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | bash $HOME/scripts/i3menu "Choose position of second monitor:")
	thirddir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | bash $HOME/scripts/i3menu "Monitor 3 will be...")
	which=$(echo $conn | tr ' ' '\n' | bash $HOME/scripts/i3menu "Which monitor?")
	xrandr --output "$primary" --primary --auto --output "$second" --"$seconddir" "$primary" --auto --output "$third" --"$thirddir" "$which" --auto
elif [[ $mode == "ARandR" ]]; then
	arandr ; exit
fi

feh --bg-scale $HOME/.config/wall.png
