#!/bin/bash

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
font=$(xrdb -query | grep 'URxvt.font' | awk '{print $NF}')
dmenucolors="-fn "${font:4}" -nb "$black" -nf "$white" -sf "$black" -sb "$blue""

all=$(xrandr -q | grep 'connected' | awk '{print $1}')
conn=$(xrandr -q | grep ' connected' | awk '{print $1}')
declare -a disconn=($(xrandr -q | grep 'disconnected' | awk '{print $1}'))
lenconn=$(xrandr -q | grep ' connected' | awk '{print $1}' | wc -l)

 
mode=$(echo -e "1 Monitor\n2 Monitors\n3 Monitors\nARandR" | dmenu -i -p "Choose mode:" $dmenucolors)

if [[ $lenconn == 1 ]]; then
	xrandr --output "$conn" --auto
    for i in "${disconn[@]}"
    do
        xrandr --output "$i" --off
    done
elif [[ $mode == "1 Monitor" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | dmenu -i -p "Choose primary monitor:" $dmenucolors)
    declare -a off=($(echo $all | tr ' ' '\n' | grep -v "$primary"))
	xrandr --output "$primary" --auto
    for i in "${off[@]}"
    do
        xrandr --output "$i" --off
    done
elif [[ $mode == "2 Monitors" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | dmenu -i -p "Choose primary monitor:" $dmenucolors)
	second=$(echo $conn | tr ' ' '\n' | grep -v "$primary")
	dir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | dmenu -i -p "Choose position of second monitor:" $dmenucolors)
	xrandr --output "$primary" --auto --output "$second" --"$dir" "$primary" --auto
elif [[ $mode == "3 Monitors" ]]; then
	primary=$(echo $conn | tr ' ' '\n' | dmenu -i -p "Choose primary monitor:" $dmenucolors)
	second=$(echo $conn | tr ' ' '\n' | grep -v "$primary" | dmenu -i -p "Choose 2nd monitor:" $dmenucolors)
	third=$(echo $conn | tr ' ' '\n' | grep -v "$primary" | grep -v "$second")
	seconddir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | dmenu -i -p "Choose position of second monitor:" $dmenucolors)
	thirddir=$(echo -e "left-of\nright-of\nabove\nbelow\nsame-as" | dmenu -i -p "Monitor 3 will be..." $dmenucolors)
	which=$(echo $conn | tr ' ' '\n' | dmenu -i -p "Which monitor?" $dmenucolors)
	xrandr --output "$primary" --auto --output "$second" --"$seconddir" "$primary" --auto --output "$third" --"$thirddir" "$which" --auto
elif [[ $mode == "ARandR" ]]; then
	arandr ; exit
fi

feh --bg-scale $HOME/.config/wall.png
