#!/bin/bash

red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
blackd=$(xrdb -query | grep '*color0' | awk '{print $NF}')

stat=$(xset -q | grep 'Caps Lock:' | awk '{print $8}')

if [[ $stat == "on" ]]; then
    echo "<span background=\"$red\" foreground=\"$blackd\"> NUM LOCK </span>"
else
    :
fi
