#!/bin/bash

tot=$(free|grep 'Mem'|awk '{print $2}')
used=$(free|grep 'Mem'|awk '{print $3}')

c=$(awk -v t=${tot} -v u=${used} 'BEGIN{ print int(u/t*100) }')

if [[ $c -ge 80 ]]; then
    echo "<span background=\"#dc322f\" foreground=\"$(bash ~/scripts/getxcolors black)\"> RAM $c% </span>"
elif [[ $c -ge 50 ]]; then
    echo "<span background=\"#b58900\" foreground=\"$(bash ~/scripts/getxcolors black)\"> RAM $c% </span>"
else
    echo "<span background=\"$(bash ~/scripts/getxcolors green)\" foreground=\"$(bash ~/scripts/getxcolors black)\"> RAM $c% </span>"
fi
