#!/bin/bash

xrdb -load $HOME/.Xresources
kill -1 $(pidof urxvtd)
#notify-send '.Xresources has been reloaded' -i $HOME/scriptpics/settingswhite.png
~/scripts/mkdunsttheme
~/scripts/mkvimtheme
~/scripts/mkblocksconf
~/scripts/mkvistheme
~/scripts/mkatomtheme
~/scripts/mkfixedsyscss
~/scripts/mkzathrc
~/scripts/i3concat
killall i3bar
i3bar -t --bar_id=bar-1 &>/dev/null &
~/scripts/i3listen-toggle
