#!/usr/bin/env bash

bash ~/scripts/mkdunsttheme
bash ~/scripts/mkblocksconf
bash ~/scripts/mkvistheme
bash ~/scripts/mkatomtheme
bash ~/scripts/mkfixedsyscss
bash ~/scripts/mkzathrc
bash ~/scripts/i3concat
killall i3bar
i3bar -t --bar_id=bar-1 &>/dev/null &
bash ~/scripts/i3listen-toggle
