#!/bin/bash

scrotdir=scrots

black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')
blue=$(xrdb -query | grep '*color4' | awk '{print $NF}')
font=$(xrdb -query | grep 'URxvt.font' | awk '{print $NF}')
dmenucolors="-fn "${font:4}" -nb "$black" -nf "$white" -sf "$black" -sb "$blue""


scrotname () {
	time="`date +%Y-%m-%d_%H:%M:%S`.png"
	name=$(echo -e "" | dmenu -i -p "Choose scrot name:" $dmenucolors)

	if [[ -z $name ]]; then
		scrotname=$time
	else
		scrotname="${name}.png"
	fi
}

confirmscrot () {
	action=$(echo -e "Save\nNew" | dmenu -i -p "Save?" $dmenucolors)
	if [[ $action == "Save" ]]; then
		scrotname
		mv $HOME/Pictures/scrots/tmp.png $HOME/Pictures/scrots/${scrotname}
		notify-send "${scrotname} saved to ~/Pictures/${scrotdir}" -i ~/Pictures/${scrotdir}/${scrotname}
	else
		tmpscrot
	fi
}

tmpscrot () {
	scrot_type=$(echo -e "Fullscreen\nSelection" | dmenu -i -p "Scrot type?:" $dmenucolors)
	if [[ $scrot_type == "Fullscreen" ]]; then
		maim --hidecursor $HOME/Pictures/${scrotdir}/tmp.png
	elif [[ $scrot_type == "Selection" ]]; then
		maim --select --hidecursor $HOME/Pictures/${scrotdir}/tmp.png
	else
		:
	fi

	sxiv $HOME/Pictures/${scrotdir}/tmp.png 
	confirmscrot
}

tmpscrot
