#!/bin/bash

name=`date +%Y-%m-%d_%H:%M:%S`_`xdpyinfo  | grep -oP 'dimensions:\s+\K\S+'`.png

scrot $HOME/Pictures/ScreenShots/$name

notify-send 'Screenshot saved to ~/Pictures/ScreenShots' -i ~/Pictures/ScreenShots/$name
