#!/bin/bash

yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
white=$(xrdb -query | grep '*color7' | awk '{print $NF}')

tot=$(free|grep 'Swap'|awk '{print $2}')
used=$(free|grep 'Swap'|awk '{print $3}')

c=$(awk -v t=${tot} -v u=${used} 'BEGIN{ print int(u/t*100) }')

if [[ $c -ge 80 ]]; then
    echo "<span background=\"$red\" foreground=\"$black\"> SWAP $c% </span>"
elif [[ $c -ge 50 ]]; then
    echo "<span background=\"$yellow\" foreground=\"$black\"> SWAP $c% </span>"
else
    echo "<span background=\"$white\" foreground=\"$black\"> SWAP $c% </span>"
fi
