#!/bin/bash

yellow=$(xrdb -query | grep '*color3' | awk '{print $NF}')
red=$(xrdb -query | grep '*color9' | awk '{print $NF}')
black=$(xrdb -query | grep '*color0' | awk '{print $NF}')
cyan=$(xrdb -query | grep '*color6' | awk '{print $NF}')

volraw=$(amixer get Master|grep 'Front Left:'|awk '{print $5}')
stat=$(amixer get Master|grep 'Front Left:'|awk '{print $6}')
vol=${volraw:1:-1}
volint=${volraw:1:-2}

if [[ $volint -ge 99 ]]; then
    echo "<span background=\"$red\" foreground=\"$black\"> VOL $vol </span>"
elif [[ $volint -ge 75 ]]; then
    echo "<span background=\"$yellow\" foreground=\"$black\"> VOL $vol </span>"
elif [[ $stat == "[off]" ]]; then
    echo "<span background=\"$cyan\" foreground=\"$black\"> VOL MUTE </span>"
else
    echo "<span background=\"$cyan\" foreground=\"$black\"> VOL $vol </span>"
fi

case $BLOCK_BUTTON in
  3) pactl set-sink-mute 0 toggle ;;  #     right click, mute/unmute
  4) pactl set-sink-volume 0 +2% ;; # scroll up, increase
  5) pactl set-sink-volume 0 -2% ;; # scroll down, decrease 
esac
