#!/bin/bash

scrotdir=scrots
name=`date +%Y-%m-%d_%H:%M:%S`_`xdotool getactivewindow getwindowname`.png
scrot --select $HOME/Pictures/$scrotdir/${name}
notify-send "${name} saved to ~/Pictures/${scrotdir}" -i ~/Pictures/$scrotdir/${name}
