#!/bin/bash

lo=$(ls $HOME/.config/i3 | tr '  ' '\n' | grep '.json' | bash $HOME/scripts/i3menu "Apply which layout?")

if [[ -z $lo ]]; then
	:
else
	i3-msg "append_layout $HOME/.config/i3/${lo}"
fi
