#!/bin/bash

theme=$(ls $HOME/xinclude/colors | bash $HOME/scripts/i3menu "Choose theme:")
xfilesDir=$HOME/xinclude

main () {
	cat ${xfilesDir}/colors/${theme} > $HOME/.Xresources
	cat ${xfilesDir}/1vars >> $HOME/.Xresources
	cat ${xfilesDir}/2colorvars >> $HOME/.Xresources
	cat ${xfilesDir}/3rofi >> $HOME/.Xresources
	cat ${xfilesDir}/4xft >> $HOME/.Xresources
	cat ${xfilesDir}/6xcursor >> $HOME/.Xresources
	cat ${xfilesDir}/7urxvt >> $HOME/.Xresources
	cat ${xfilesDir}/8urxvtext >> $HOME/.Xresources
	xrdb -load $HOME/.Xresources
	kill -1 $(pidof urxvtd)
	notify-send '.Xresources has been reloaded' -i $HOME/scriptpics/settingswhite.png
	bash $HOME/scripts/reloadconfs
}

if [[ -f $xfilesDir/colors/${theme} ]]; then
	main
else
	:
fi
