#!/usr/bin/env bash

xfilesDir=$HOME/xrs

theme () {
	theme=$(ls $xfilesDir/colors | grep -v '_' | $HOME/scr/i3menu "Choose theme:")
	if [[ -z $theme ]]; then
		:
	elif [[ ! -f $xfilesDir/colors/$theme ]]; then
		:
	else
		variant=$(echo -e "Main\nAlternate" | $HOME/scr/i3menu "Variant?:")
	fi

	if [[ $variant == "Alternate" ]]; then
		theme="${theme}_"
	else
		theme="${theme}"
	fi
}

main () {
	cat ${xfilesDir}/colors/${theme} > $xfilesDir/theme
	$HOME/scr/reloadconfs
}

theme

if [[ -f $xfilesDir/colors/${theme} ]]; then
	main
else
	:
fi
