#!/usr/bin/env bash

IFU="<span face='Font Awesome 5 Free'>&#xf240;</span>"
I75="<span face='Font Awesome 5 Free'>&#xf241;</span>"
I50="<span face='Font Awesome 5 Free'>&#xf242;</span>"
I25="<span face='Font Awesome 5 Free'>&#xf243;</span>"
I00="<span face='Font Awesome 5 Free'>&#xf244;</span>"

_BAT=$(acpi | awk '{ print $4 }')
BAT=${_BAT/\%/}
BAT=${BAT/,/}

RST=$(acpi | awk '{ print $3 }')
RST=${RST/,/}
TIM=$(acpi | awk '{ print $5 }')
[[ -z "$TIM" ]] || TIM="${_TIM%:*}"

STT=""
[[ $RST == "Charging" ]] && STT="<span face='Font Awesome 5 Free'>&#xf1e6;</span>"
 [[ $RST == "Unknown" ]] && STT="<span face='Font Awesome 5 Free'>&#xf00c;</span>"
    [[ $RST == "Full" ]] && STT="<span face='Font Awesome 5 Free'>&#xf00c;</span>"

BCL="$(themer -v "acc ")"
   [[ $RST == "Full" ]] && ICF="$IFU $STT" BAT="" TIM=""
[[ $RST == "Unknown" ]] && ICF="$IFU $STT" BAT="" TIM=""
     [[ $BAT  == 100 ]] && ICF="$IFU $STT" BAT="" TIM=""
     [[ $BAT -lt 100 ]] && ICF=" $I75 $STT"
     [[ $BAT -lt  75 ]] && ICF=" $I50 $STT"
     [[ $BAT -lt  50 ]] && ICF=" $I25 $STT"
     [[ $BAT -lt  25 ]] && ICF=" $I00 $STT" BCL="#ffcc00"
     [[ $BAT -le  10 ]] && ICF=" $I00 $STT" BCL="#cc0000"
echo "<span background=\"${BCL}\"> ${BAT}${ICF}${TIM} </span>" | i3menu
