#!/usr/bin/env bash

case $BLOCK_BUTTON in
	1) nightmodetog ;;
	4) light -A 10 ;;
	5) light -U 10 ;;
esac

IN="<span face='Font Awesome 5 Free'>&#xf042;</span>"
_BL=$(light -G)
BL=${_BL%.*}

echo "${IN} ${BL}"
