#!/usr/bin/env bash

ICN="<span face='Font Awesome 5 Free'>&#xf2db;</span>"

IDL=$(top -b -n1 | sed -n 's/.* ni, \([^ ]*\).*/\1/p')
ILN=$(echo $IDL | tr ' ' '\n' | wc -l)
ITT=$(echo $IDL | tr ' ' '\n' | awk '{s+=$1} END {print s}')
CPU=${ITT%.*}

if [[ $CPU -ge 80 ]]; then
	echo "<span foreground=\"#ff0000\">$ICN $CPU</span>"
elif [[ $CPU -ge 50 ]]; then
	echo "<span foreground=\"#ffff00\">$ICN $CPU</span>"
else
	echo "$ICN $CPU"
fi
