#!/usr/bin/env bash

mpris=$(pidof spotify)
mpv=$(pidof mpv)
mpvtitle="$(xdotool getwindowname $(xdotool search --class mpv))"

blocksDir="$HOME/scr/blocks"

clr=$(xrdb -query | grep '*color7' | awk '{print $NF}')

if [[ -n $mpv ]]; then
	echo "<span foreground=\"$clr\"><span face='Font Awesome 5 Free'>&#xf03d;</span> ${mpvtitle:0:-6}</span>"
elif [[ -n $mpris ]]; then
	$blocksDir/mpgui
else
	$blocksDir/mpcblk
fi

case $BLOCK_BUTTON in
	1) $HOME/scr/i3media togg ;;
	3) $HOME/scr/i3media stop ;;
	4) $HOME/scr/i3media next ;;
	5) $HOME/scr/i3media prev ;;
esac
