#!/bin/bash

# OA: Gavin Vales
# CREATED: Sun  9 Jun 17:44:48 GMT 2019

main () {
	rm .theme_list
	thms=$(ls -l | grep -v "^total" | grep -v "themelist" | awk '{print $NF}')
	for i in $thms; do
		wtl=$(cat ${i} | grep "cwhtl" | awk '{print $NF}')
		wtd=$(cat ${i} | grep "cwhtd" | awk '{print $NF}')
		bkl=$(cat ${i} | grep "cblkl" | awk '{print $NF}')
		bkd=$(cat ${i} | grep "cblkd" | awk '{print $NF}')
		red=$(cat ${i} | grep "credd" | awk '{print $NF}')
		grn=$(cat ${i} | grep "cgrnd" | awk '{print $NF}')
		ylw=$(cat ${i} | grep "cylwd" | awk '{print $NF}')
		blu=$(cat ${i} | grep "cblud" | awk '{print $NF}')
		gnt=$(cat ${i} | grep "cgntd" | awk '{print $NF}')
		cyn=$(cat ${i} | grep "ccynd" | awk '{print $NF}')
		echo "\
<span foreground=\"#666666\" background=\"$wtl\"> fg </span>\
<span foreground=\"#666666\" background=\"$bkd\"> bg </span>\
<span foreground=\"#666666\" background=\"$blu\"> acc </span>\
 $i" >> .theme_list
	done
}

main
#<span foreground=\"#666666\" background=\"$wtd\"> com </span>\
#<span foreground=\"#666666\" background=\"$bkl\"> grey </span>\
#<span foreground=\"#666666\" background=\"$red\"> r </span>\
#<span foreground=\"#666666\" background=\"$grn\"> g </span>\
#<span foreground=\"#666666\" background=\"$ylw\"> y </span>\
#<span foreground=\"#666666\" background=\"$gnt\"> m </span>\
#<span foreground=\"#666666\" background=\"$cyn\"> c </span>\
