.TH EDTR 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]edtr\f[R] - vim server wrapper using \f[C]rxvt-unicode\f[R]
.SH SYNOPSIS
.IP
.nf
\f[C]
edtr [--server|-s <name>] [--fontsize|-S <integer>] <file>
edtr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--server|-s <name>\f[R]
.PD 0
.P
.PD
\f[C]--servername\f[R] changed to \f[C]<name>\f[R].
Default \f[C]--servername\f[R] is `edtr'.
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH MORE
.PP
\f[C]edtr\f[R] will also decide the \f[C]--servername\f[R] based on
filetype (from \f[C]file\f[R] output) and file extension:
.PP
.TS
tab(@);
r l l.
T{
Filetype
T}@T{
servername
T}@T{
urxvt instance name
T}
_
T{
\f[C]Bourne-Again\f[R]
T}@T{
\f[C]bash-edtr\f[R]
T}@T{
\f[C]bash - edtr\f[R]
T}
.TE
.PP
.TS
tab(@);
r l l.
T{
Extension
T}@T{
servername
T}@T{
urxvt instance name
T}
_
T{
\f[C]Xres*/Xdef*\f[R]
T}@T{
\f[C]edtr-Xfiles\f[R]
T}@T{
\f[C]Xfiles - edtr\f[R]
T}
T{
\f[C]*conf*\f[R]
T}@T{
\f[C]edtr-configs\f[R]
T}@T{
\f[C]configs - edtr\f[R]
T}
T{
\f[C]*bash*\f[R]
T}@T{
\f[C]edtr-bash\f[R]
T}@T{
\f[C]bash - edtr\f[R]
T}
T{
\f[C]sh\f[R]
T}@T{
\f[C]edtr-sh\f[R]
T}@T{
\f[C]sh - edtr\f[R]
T}
T{
\f[C]*vim*\f[R]
T}@T{
\f[C]edtr-vim\f[R]
T}@T{
\f[C]vim - edtr\f[R]
T}
T{
\f[C]yaml\f[R]
T}@T{
\f[C]edtr-yaml\f[R]
T}@T{
\f[C]yaml - edtr\f[R]
T}
T{
\f[C]html\f[R]
T}@T{
\f[C]edtr-html\f[R]
T}@T{
\f[C]html - edtr\f[R]
T}
T{
\f[C]py\f[R]
T}@T{
\f[C]edtr-py\f[R]
T}@T{
\f[C]py - edtr\f[R]
T}
T{
\f[C]ms\f[R]
T}@T{
\f[C]edtr-groff\f[R]
T}@T{
\f[C]groff - edtr\f[R]
T}
T{
\f[C]css\f[R]
T}@T{
\f[C]edtr-css\f[R]
T}@T{
\f[C]css - edtr\f[R]
T}
T{
\f[C]md|rmd\f[R]
T}@T{
\f[C]edtr-md\f[R]
T}@T{
\f[C]md - edtr\f[R]
T}
T{
\f[C]bib\f[R]
T}@T{
\f[C]edtr-bib\f[R]
T}@T{
\f[C]bib - edtr\f[R]
T}
T{
\f[C]tex\f[R]
T}@T{
\f[C]edtr-tex\f[R]
T}@T{
\f[C]tex - edtr\f[R]
T}
.TE
