.TH GEDTR 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gedtr\f[R] - gvim server wrapper
.SH SYNOPSIS
.IP
.nf
\f[C]
gedtr [--foreground|-f] [--server|-s <name>] <file>
gedtr --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--server|-s <name>\f[R]
.PD 0
.P
.PD
Specify server name.
Default is \f[C]GVIM\f[R].
.PP
\f[C]--foreground|-f\f[R]
.PD 0
.P
.PD
Do not detach from shell instance
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
