.TH GOSTE 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]goste\f[R] - create notes, with different types, stored in
$XDG_DESKTOP_DIR/goste
.SH SYNOPSIS
.IP
.nf
\f[C]
goste --create|-c|--open|-o <type>
goste --list-entries|-l|--delete-type|-D <type>
goste --list-types|-L
goste --help|-h
goste
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[C]
dmrap edtr urxvt banner
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create defaults:
.PD 0
.P
.PD
\f[C]GOSTE_DIR\f[R] = \f[C]$HOME/Desktop/goste\f[R]
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.PP
\f[C]--create|-c <type>\f[R]
.PD 0
.P
.PD
Create $GOSTE_DIR/\f[C]<type>\f[R]
.PP
\f[C]--open|-o <type>\f[R]
.PD 0
.P
.PD
Open $GOSTE_DIR/\f[C]<type>\f[R]
.PP
\f[C]--delete-type|-D <type>\f[R]
.PD 0
.P
.PD
Delete $GOSTE_DIR/\f[C]<type>\f[R]
.PP
\f[C]--list-entries|-l\f[R]
.PD 0
.P
.PD
Print contents of $GOSTE_DIR/\f[C]<type>\f[R]
.PP
\f[C]--list-types|-L <type>\f[R]
.PD 0
.P
.PD
\f[C]ls\f[R] $GOSTE_DIR
