.TH GWC 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gwc\f[R] - A script to set wallpaper, with other features.
.SH SYNOPSIS
.IP
.nf
\f[C]
gwc [--wallpaper|-w <path|name|color|random|previous|next>]
    [--next|-n] [--previous|-p] [--random|-r]
    [--tint|-t <hex_color>] [--blur|-b]
gwc --add|-a <directory|path>
gwc --list|-l
gwc --rename|-R \[aq]<oldname> <newname>\[aq]
gwc --delete|-d \[aq]<name>\[aq]
gwc --help|-h
gwc
\f[R]
.fi
.SH OPTIONS
.PP
Run with no options to create default directories:
.PD 0
.P
.PD
+ \f[C]$GWCDIR/(normal|blur|cols)\f[R] + Default \f[C]gwc\f[R] database:
\f[C]GWCDIR\f[R] = \f[C]$XDG_PICTURES_DIR/gwc\f[R]
.PP
\f[C]--wallpaper|-w <path|name|random|previous|next>\f[R]
.PD 0
.P
.PD
Wallpaper to set:
.IP \[bu] 2
\f[C]<path>\f[R] - path to a picture
.IP \[bu] 2
\f[C]<name>\f[R] - name of wallpaper stored in \f[C]$GWCDIR/normal\f[R]
.IP \[bu] 2
\f[C]<hex_color>\f[R] - When the argument to this flag starts with a
\f[C]<hex_color>\f[R], \f[C]gwc\f[R] uses \f[C]hsetroot\f[R] to tile the
wallpaper \f[C]$GWCDIR/white\f[R] (by default), and tint it to the
specified \f[C]<hex_color>\f[R].
If the argument is eg.
\f[C]<hex_color>-paper\f[R], then \f[C]gwc\f[R] finds and uses
\f[C]$GWCDIR/white-paper\f[R] as the tiled image instead.
.IP \[bu] 2
\f[C]<previous>\f[R] - previous wallpaper in history
.IP \[bu] 2
\f[C]<next>\f[R] - next wallpaper in history
.IP \[bu] 2
\f[C]<random>\f[R] - Choose a random wallpaper in
\f[C]$GWCDIR/normal\f[R]
.PP
\f[C]--previous|-p\f[R]
.PD 0
.P
.PD
previous wallpaper in history
.PP
\f[C]--next|-n\f[R]
.PD 0
.P
.PD
next wallpaper in history
.PP
\f[C]--random|-r\f[R]
.PD 0
.P
.PD
Choose a random wallpaper in \f[C]$GWCDIR/normal\f[R]
.PP
\f[C]--tint|-t <hex_color>\f[R]
.PD 0
.P
.PD
Tint color of wallpaper, Hexadecimal color Eg.
#002b36
.PP
\f[C]--add|-a <directory|path>\f[R]
.PD 0
.P
.PD
Add walls from \f[C]<directory>\f[R], add the wallpaper in
\f[C]<path>\f[R], or if there\[cq]s no argument, check for pictures in
the working directory and add those to \f[C]$GWCDIR\f[R]
.PP
\f[C]--list|-l\f[R]
.PD 0
.P
.PD
View all wallpapers in the database
.PP
\f[C]--blur|-b\f[R]
.PD 0
.P
.PD
Toggle blur
.PP
\f[C]--rename|-r \[aq]<oldname> <newname>\[aq]\f[R]
.PD 0
.P
.PD
Rename \f[C]<oldname>\f[R] wallpaper to \f[C]<newname>\f[R].
If only there is only one argument, the current wallpaper is renamed to
that argument.
.PP
\f[C]--delete|-d <name>\f[R]
.PD 0
.P
.PD
Remove \f[C]<name>\f[R] wallpaper from \f[C]$GWCDIR/(normal|blur)\f[R]
If \f[C]<name>\f[R] is empty, the current wallpaper is removed.
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
