.TH MANNER 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]manner\f[R] - generates man pages for scripts
.SH SYNOPSIS
.IP
.nf
\f[C]
manner [--source-directory|-d <source-directory>]
       [--man-directory|-m <man-directory>]
       [--install|-i copy|link]
manner --delete|-D
manner --script|-s <script>
manner --help|-h
\f[R]
.fi
.SH DEPENDENCIES
.IP
.nf
\f[C]
pandoc
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--source-directory|-d <source-directory>\f[R]
.PD 0
.P
.PD
Directory that contains your source scripts
.PP
\f[C]--man-directory|-m <man-directory>\f[R]
.PD 0
.P
.PD
Directory to output your new manpages
.PP
\f[C]--install|-i copy|link\f[R]
.PD 0
.P
.PD
Install all the manpages in \f[C]<source-directory>\f[R]man to
\f[C]/usr/share/man/man1\f[R] if they do not already exist.
.PD 0
.P
.PD
Argument to this option determines whether the scripts are copied or
linked.
.PP
\f[C]--delete|-D\f[R]
.PD 0
.P
.PD
Delete all occurences of generated manpages from
\f[C]/usr/share/man/man1\f[R]
.PP
\f[C]--script|-s <script>\f[R]
.PD 0
.P
.PD
Call specified \f[C]<script>\f[R] with \f[C]--help\f[R] flag, and
convert the output to a man page with \f[C]pandoc -s -t man\f[R]
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH DESCRIPTION
.PP
Looks for all scripts in \f[C]<source-directory>\f[R] that contain a
\f[C]--help\f[R] string, and pipe \f[C]<script> --help\f[R] through
\f[C]pandoc -s -t man\f[R] and redirect the output to a manpage named
\f[C]<script>.1\f[R] in \f[C]<man-directory>\f[R]
.RS
.PP
NOTE THAT THIS ONLY WORKS BECAUSE ALL MY HELP FUNCTIONS ARE WRITTEN IN
\f[C]markdown\f[R].
All precode is converted to bold text.
.RE
.PP
The \f[C]--install\f[R] flag can be used to install the manpages in
\f[C]<man-directory>\f[R] to \f[C]/usr/share/man/man1\f[R]
.PP
\f[B]In progress\f[R]
.PD 0
.P
.PD
The \f[C]--script\f[R] flag can be used to automatically pipe the output
of the specified script to a man page.
