.TH ROFIND 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]rofind\f[R] - \f[C]find\f[R] wrapper with \f[C]rofi\f[R]
.SH DEPENDENCIES
.IP
.nf
\f[C]
dmenu-gavin
dmrap
\f[R]
.fi
.SH SYNOPSIS
.IP
.nf
\f[C]
rofind
rofind --help|-h
\f[R]
.fi
.SH DESCRIPTION
.PP
Just a \f[C]rofi\f[R] wrapper for \f[C]find\f[R], and opens the chosen
item using an appropriate application.
