.TH TAGGER 1 2020\-09\-27 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]tagger\f[R] - change artist, album name, and title of mp3\[cq]s in
a directory
.SH SYNOPSIS
.IP
.nf
\f[B]
tagger [--artist|-a \fI<text>\fP]
       [--album|-b \fI<text>\fP]
       [--cover|-c \fI<imagefile>\fP]
tagger --help|-h
\f[R]
.fi
