.TH WEBGEN 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]webgen\f[R] - manage a static website, using \f[C]pandoc\f[R] +
\f[C]markdown\f[R]
.SH DEPENDENCIES
.IP
.nf
\f[C]
pandoc
\f[R]
.fi
.SH SYNOPSIS
.IP
.nf
\f[C]
webgen --gensite|-g|--pushsite|-s
webgen --newpage|-n|--newpost|-p <name>
webgen --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--gensite|-g\f[R]
.PD 0
.P
.PD
Generates website in \f[C]local/\f[R] folder.
.PD 0
.P
.PD
The links will still be local so you can still view your changes
locally.
.PP
\f[C]--pushsite|-s\f[R]
.PD 0
.P
.PD
Runs \f[C].webgen\f[R] script to upload the site to wherever you want.
Put anything you want in the script
.PP
\f[C]--newpage|-n <name>\f[R]
.PD 0
.P
.PD
Create a new page
.PP
\f[C]--newpost|-p <name>\f[R]
.PD 0
.P
.PD
Create a new blog post
.PP
\f[C]--help\f[R]
.PD 0
.P
.PD
Displays this help
