.TH WIKIUD 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]wikiud\f[R] - generates the script wikis shown in my wiki sidebars
.SH SYNOPSIS
.IP
.nf
\f[C]
wikiud [--user|-u <github-user>]
       [--repo|-r <repo>]
       [--source-dir|-s <source-directory>]
       [--target-dir|-t <target-directory>]
       [--base|-b <file>]
wikiud --help|-h
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]--user|-u <github-user>\f[R]
.PD 0
.P
.PD
Your Github username.
Used to correctly link to the raw script
.PP
\f[C]--repo|-r <github-user>\f[R]
.PD 0
.P
.PD
Name of the target repo.
Used to correctly link to the raw script
.PP
\f[C]--source-dir|-s <source-directory>\f[R]
.PD 0
.P
.PD
Source , which contains your scripts
.PP
\f[C]--target-dir|-t <target-directory>\f[R]
.PD 0
.P
.PD
Target , usually a directory named \f[C]<repo>.wiki\f[R], for simplicity
.PP
\f[C]--base|-b <file>\f[R]
.PD 0
.P
.PD
Base file for \f[C]_Sidebar.md\f[R].
Contains stuff you want before the list of scripts in the wiki sidebar
.PP
\f[C]--help|-h\f[R]
.PD 0
.P
.PD
Print this help
.SH DESCRIPTION
.PP
Basically checks for scripts that contain the \f[C]--help\f[R] string
and redirects \f[C]<script> --help\f[R] to
\f[C]<target-directory>/doc\f[R]<++>
