.TH XBMER 1 2021\-06\-01 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]xbmer\f[R] - \f[C]xsetroot\f[R] front-end for setting bitmap
pattern wallpapers.
.SH SYNOPSIS
.IP
.nf
\f[C]
xbmer [--pattern|-p <pattern>.xbm]
      [--bg|-b <backgroundhex>]
      [--fg|-f <foregroundhex>]
xber --help|-h
\f[R]
.fi
.SH DESCRIPTION
.PP
Obviously depends on \f[C]xsetroot\f[R], and can\[cq]t be used with
\f[C]compton\f[R], until \f[C]hsetroot\f[R] can use \f[C].xbm\f[R]
files!
.PD 0
.P
.PD
\f[C].xbm\f[R] files stored in \f[C]\[ti]/Pictures/xbm\f[R] by default.
