#!/bin/bash

killall -q polybar
polybar i3 &>/dev/null &
#sleep 0.5
#hideIt.sh --name "^polybar-i3_eDP1$" --wait --hover --direction top --peek 1 &>/dev/null &
#hideIt.sh --name "^polybar-fvwm_eDP1$" --wait --hover --direction top --peek 1 &>/dev/null &
